/**
 * KELİMELER.JS — Kelime Ustası Oyunu Kelime Veritabanı
 * =====================================================
 */

const DB = {
    // ─────────────────────────────────────────────
    //  3 HARFLİ KELİMELER
    // ─────────────────────────────────────────────
    3: [
        { w: "AŞK", h: "Şiddetli ve yakıcı sevgi duygusu." },
        { w: "TOP", h: "Yuvarlak, genellikle oyun için kullanılan nesne." },
        { w: "NAR", h: "İçinde yüzlerce küçük kırmızı tanesi olan meyve." },
        { w: "MUZ", h: "Sarı kabuklu, uzunca tropikal meyve." },
        { w: "GÖZ", h: "Görme organımız." },
        { w: "YAZ", h: "En sıcak mevsim." },
        { w: "KIŞ", h: "En soğuk mevsim." },
        { w: "ÇAY", h: "Genellikle kahvaltıda içilen sıcak içecek." },
        { w: "KOL", h: "Omuzdan parmaklara kadar uzanan uzuv." },
        { w: "TUZ", h: "Yemeklere tat veren beyaz mineral." },
        { w: "BAĞ", h: "Üzüm kütüklerinin dikili bulunduğu toprak parçası." },
        { w: "GÜÇ", h: "Kuvvet, takat." },
        { w: "SÜT", h: "Memelilerin yavrularını besledikleri beyaz sıvı." },
        { w: "KAN", h: "Damarlarda dolaşan hayati kırmızı sıvı." },
        { w: "YOL", h: "Karada gidiş geliş için açılmış şerit." },
        { w: "HIZ", h: "Sürat." },
        { w: "PİL", h: "Elektrik enerjisi depolayan cihaz." },
        { w: "ADA", h: "Dört tarafı sularla çevrili kara parçası." },
        { w: "ATA", h: "Baba, dede, ecdat." },
        { w: "ARA", h: "Mesafe veya boşluk." },
        { w: "KEP", h: "Siperli başlık." },
        { w: "BEL", h: "Vücudun orta kısmı." },
        { w: "BİR", h: "İlk sayı." },
        { w: "BUZ", h: "Donmuş su." },
        { w: "CAM", h: "Pencereye takılan saydam madde." },
        { w: "DAĞ", h: "Çevresine göre çok yüksek yeryüzü şekli." },
        { w: "DİŞ", h: "Çiğneme organı." },
        { w: "FİL", h: "Hortumlu büyük memeli hayvan." },
        { w: "GÜL", h: "Dikenli ve güzel kokulu bir çiçek." },
        { w: "ISI", h: "Sıcaklık enerjisi." },
        { w: "İYİ", h: "Kötü karşıtı." },
        { w: "KAŞ", h: "Gözün üzerindeki kıllar." },
        { w: "KIZ", h: "Dişi çocuk." },
        { w: "KUŞ", h: "Kanatlı, yumurtlayan hayvan." },
        { w: "NAL", h: "Atın ayağına çakılan demir." },
        { w: "ODA", h: "Evin bölümlerinden her biri." },
        { w: "RUH", h: "Can, tin." },
        { w: "SAÇ", h: "Baştaki kıllar." },
        { w: "SAF", h: "Katıksız, arı." },
        { w: "SES", h: "Kulağın duyabildiği titreşim." },
        { w: "SİS", h: "Görüşü azaltan dumanlı hava olayı." },
        { w: "SON", h: "Bitiş, nihayet." },
        { w: "TAŞ", h: "Sert, katı yeryüzü maddesi." },
        { w: "TAT", h: "Lezzet." },
        { w: "TEK", h: "Eşi olmayan, bir tane." },
        { w: "TOZ", h: "Çok ince toprak zerreleri." },
        { w: "YIL", h: "Sene, 365 gün." },
        { w: "YÜZ", h: "Çehre, surat." },
        { w: "ZAR", h: "Şans oyunlarında kullanılan küp." },
        { w: "BAL", h: "Arıların ürettiği tatlı madde." },
        { w: "JET", h: "Çok hızlı uçak." },
        { w: "TIĞ", h: "Örgü örmeye yarayan ucu eğri araç." },
        { w: "YEL", h: "Hafif rüzgar." }
    ],

    // ─────────────────────────────────────────────
    //  4 HARFLİ KELİMELER
    // ─────────────────────────────────────────────
    4: [
        { w: "ELMA", h: "Kırmızı, sarı veya yeşil kabuklu meyve." },
        { w: "KAPI", h: "Binalara girip çıkmaya yarayan yer." },
        { w: "MAVİ", h: "Gökyüzünün ve denizin rengi." },
        { w: "FARE", h: "Küçük kemirgen bir hayvan." },
        { w: "OKUL", h: "Eğitim öğretim görülen yer." },
        { w: "KEDİ", h: "Evcil, miyavlayan hayvan." },
        { w: "YURT", h: "Vatan veya öğrencilerin kaldığı yer." },
        { w: "SERT", h: "Yumuşak karşıtı." },
        { w: "KALE", h: "Düşman saldırılarına karşı yapılan korunak." },
        { w: "ÜZÜM", h: "Salkım şeklinde yetişen meyve." },
        { w: "UZAY", h: "Bütün gök cisimlerinin içinde bulunduğu sonsuz boşluk." },
        { w: "VERİ", h: "Bilgi, data." },
        { w: "DERT", h: "Sorun, sıkıntı, tasa." },
        { w: "MART", h: "Yılın üçüncü ayı." },
        { w: "PLAN", h: "Tasarı, proje." },
        { w: "AÇIK", h: "Kapalı olmayan." },
        { w: "ADIM", h: "Yürürken ayakların her atılışı." },
        { w: "AĞAÇ", h: "Odunsu gövdesi olan uzun bitki." },
        { w: "SORU", h: "Cevap bekleyen söz." },
        { w: "AİLE", h: "Anne, baba ve çocuklardan oluşan birlik." },
        { w: "AKIL", h: "Düşünme yeteneği, us." },
        { w: "AMAÇ", h: "Gaye, hedef." },
        { w: "ANIT", h: "Abide." },
        { w: "ARZU", h: "İstek, heves." },
        { w: "ASIR", h: "Yüzyıl." },
        { w: "ATEŞ", h: "Yanıcı maddelerin tutuşmasıyla beliren ısı ve ışık." },
        { w: "ATOM", h: "Maddenin en küçük yapı taşı." },
        { w: "AYNA", h: "Görüntüyü yansıtan cilalı cam." },
        { w: "BABA", h: "Erkek ebeveyn." },
        { w: "BATI", h: "Güneşin battığı yön." },
        { w: "BİNA", h: "Yapı." },
        { w: "BORÇ", h: "Geri verilmek üzere alınan şey." },
        { w: "BOYA", h: "Renklendirme maddesi." },
        { w: "CUMA", h: "Perşembe ile Cumartesi arasındaki gün." },
        { w: "ÇATI", h: "Binaların üstünü örten kısım." },
        { w: "DANS", h: "Müzik eşliğinde yapılan ritmik hareketler." },
        { w: "DERS", h: "Öğrenilen konu." },
        { w: "DERİ", h: "Vücudun dış örtüsü, ten." },
        { w: "DOĞA", h: "Tabiat." },
        { w: "DOST", h: "Arkadaş, yakın kimse." },
        { w: "EKİM", h: "Sonbahar mevsiminin bir ayı." },
        { w: "EMEK", h: "Çaba, zahmet." },
        { w: "ERİK", h: "Farklı türleri olan bir yaz meyvesi." },
        { w: "EŞYA", h: "Türlü amaçlarla kullanılan nesneler." },
        { w: "ETKİ", h: "Tesir." },
        { w: "FİLM", h: "Sinema eseri." },
        { w: "GEMİ", h: "Su üzerinde yüzen büyük taşıt." },
        { w: "GEZİ", h: "Seyahat." },
        { w: "GIDA", h: "Besin." },
        { w: "HALK", h: "Bir ülkede yaşayan insanlar bütünü." },
        { w: "HATA", h: "Yanlışlık, kusur." },
        { w: "HAVA", h: "Dünyayı saran gaz tabakası." },
        { w: "İLAÇ", h: "Hastalıkları iyileştiren madde." },
        { w: "İLKE", h: "Prensip." },
        { w: "KAFE", h: "Kahve içilen yer." },
        { w: "KAMP", h: "Çadır kurarak konaklama." },
        { w: "KATI", h: "Sıvı olmayan." },
        { w: "KAYA", h: "Büyük taş kütlesi." },
        { w: "KEÇİ", h: "İnatçılığıyla bilinen hayvan." },
        { w: "KENT", h: "Şehir." },
        { w: "KİLO", h: "Ağırlık birimi." },
        { w: "KONU", h: "Mevzu, bahis." },
        { w: "KOŞU", h: "Hızlı yürüme eylemi, yarış." },
        { w: "KRAL", h: "Hükümdar." },
        { w: "KURT", h: "Köpekgillerden vahşi hayvan." },
        { w: "KUTU", h: "İçine eşya konulan kap." },
        { w: "LİRA", h: "Para birimi." },
        { w: "MASA", h: "Ayaklı mobilya." },
        { w: "MÜZE", h: "Tarihi eserlerin sergilendiği yer." },
        { w: "OCAK", h: "Yılın ilk ayı." },
        { w: "OLAY", h: "Hadise, vaka." },
        { w: "OTEL", h: "Konaklama tesisi." },
        { w: "OYUN", h: "Eğlence etkinliği." },
        { w: "ÖDEV", h: "Vazife." },
        { w: "ÖYKÜ", h: "Hikaye." },
        { w: "ÖZEL", h: "Hususi." },
        { w: "PARA", h: "Ödeme aracı." },
        { w: "PARK", h: "Yeşil alan." },
        { w: "RÜYA", h: "Uykuda görülen düş." },
        { w: "SAAT", h: "Zaman ölçme aracı." },
        { w: "SARI", h: "Limonun rengi." },
        { w: "SPOR", h: "Bedensel aktivite." },
        { w: "ŞANS", h: "Talih, uğur." },
        { w: "ŞART", h: "Koşul." },
        { w: "ŞİİR", h: "Duygulu, ahenkli yazı türü." },
        { w: "TAZE", h: "Bayat olmayan." },
        { w: "TEMA", h: "Ana konu." },
        { w: "TREN", h: "Raylar üzerinde giden taşıt." },
        { w: "UMUT", h: "Ümit." },
        { w: "ÜRÜN", h: "Mahsul." },
        { w: "ÜNLÜ", h: "Meşhur, tanınmış." },
        { w: "YAPI", h: "Bina, inşaat." },
        { w: "YARA", h: "Doku hasarı." },
        { w: "YENİ", h: "Eski olmayan." },
        { w: "ZEKA", h: "Akıl, anlama yeteneği." },
        { w: "KURS", h: "Eğitim programı." },
        { w: "YAZI", h: "Düşüncenin harflerle ifadesi." },
        { w: "MODA", h: "Geçici giyim akımı." },
        { w: "UYKU", h: "Dinlenme hali." }
    ],

    // ─────────────────────────────────────────────
    //  5 HARFLİ KELİMELER
    // ─────────────────────────────────────────────
    5: [
        { w: "RADYO", h: "Ses dalgalarını ileten cihaz." },
        { w: "KİTAP", h: "Okumak için yazılmış eser." },
        { w: "ÇİÇEK", h: "Bitkilerin renkli ve kokulu kısmı." },
        { w: "DÜNYA", h: "Yaşadığımız gezegen." },
        { w: "MÜZİK", h: "Ses sanatı." },
        { w: "KAHVE", h: "Kafeinli sıcak içecek." },
        { w: "BULUT", h: "Gökyüzündeki su buharı kütlesi." },
        { w: "GÜNEŞ", h: "Dünyamızı ısıtan yıldız." },
        { w: "ROBOT", h: "Otomatik iş yapan makine." },
        { w: "LAZER", h: "Yoğunlaştırılmış ışık demeti." },
        { w: "EKRAN", h: "Görüntü paneli." },
        { w: "MOTOR", h: "Güç üreten makine." },
        { w: "HELVA", h: "Tatlı bir yiyecek." },
        { w: "PANEL", h: "Levha veya açık oturum." },
        { w: "ACELE", h: "Çabukluk, telaş." },
        { w: "ADRES", h: "Bulunulan yerin tarifi." },
        { w: "AKŞAM", h: "Günün batış zamanı." },
        { w: "ALARM", h: "Uyarı sesi." },
        { w: "ALBÜM", h: "Müzik veya resim koleksiyonu." },
        { w: "ANLAM", h: "Mana." },
        { w: "ARABA", h: "Tekerlekli taşıt." },
        { w: "BAHÇE", h: "Çiçek veya ağaç dikili yer." },
        { w: "BALIK", h: "Suda yaşayan hayvan." },
        { w: "BANKA", h: "Para işleri yapan kurum." },
        { w: "BARIŞ", h: "Savaşın olmama durumu." },
        { w: "BELGE", h: "Döküman, vesika." },
        { w: "BEYAZ", h: "Ak, kara karşıtı renk." },
        { w: "BİBER", h: "Acı veya tatlı sebze." },
        { w: "BİLGİ", h: "Öğrenilen şey, malumat." },
        { w: "BİLİM", h: "İlim." },
        { w: "BÖLGE", h: "Sınırları belli alan." },
        { w: "BÖLÜM", h: "Kısım, parça." },
        { w: "BÜYÜK", h: "Küçük olmayan, iri." },
        { w: "CANLI", h: "Yaşayan." },
        { w: "CEVAP", h: "Yanıt." },
        { w: "CEVİZ", h: "Sert kabuklu bir kuruyemiş." },
        { w: "ÇEVRE", h: "Doğal ortam." },
        { w: "DEĞİL", h: "Olumsuzluk belirtir." },
        { w: "DEĞER", h: "Kıymet." },
        { w: "DENİZ", h: "Tuzlu su kütlesi." },
        { w: "DOĞRU", h: "Yanlış olmayan." },
        { w: "DOLAP", h: "Eşya konan mobilya." },
        { w: "EKLEM", h: "Kemiklerin birleştiği yer." },
        { w: "FİKİR", h: "Düşünce, ide." },
        { w: "GİTAR", h: "Telli müzik aleti." },
        { w: "GÖREV", h: "Vazife." },
        { w: "GÜVEN", h: "Emniyet." },
        { w: "HAYAT", h: "Yaşam." },
        { w: "HIZLI", h: "Çabuk." },
        { w: "İNSAN", h: "Akıllı canlı, Homo sapiens." },
        { w: "KALEM", h: "Yazı yazma aracı." },
        { w: "KARGO", h: "Yük taşıma hizmeti." },
        { w: "KAYAK", h: "Kar sporu." },
        { w: "KEMAN", h: "Yaylı çalgı aleti." },
        { w: "KİLOT", h: "İç çamaşırı." },
        { w: "KIYMA", h: "Çekilmiş et." },
        { w: "KORKU", h: "Dehşet, ürperti." },
        { w: "KÖPEK", h: "Sadık evcil hayvan." },
        { w: "KÖPRÜ", h: "İki yakayı birleştiren yapı." },
        { w: "KUMAR", h: "Şansa dayalı para oyunu." },
        { w: "KÜÇÜK", h: "Büyük olmayan." },
        { w: "LAMBA", h: "Işık kaynağı." },
        { w: "MARKA", h: "Ticari isim." },
        { w: "MELEK", h: "Tanrı'nın nurdan yarattığı varlık." },
        { w: "MEZUN", h: "Okulu bitirmiş kişi." },
        { w: "MUTLU", h: "Neşeli, bahtiyar." },
        { w: "NEHİR", h: "Akan tatlı su." },
        { w: "NİSAN", h: "Yılın dördüncü ayı." },
        { w: "ORMAN", h: "Ağaçlık alan." },
        { w: "OYNAK", h: "Hareketli." },
        { w: "ÖZGÜR", h: "Serbest, hür." },
        { w: "PASTA", h: "Tatlı unlu mamul." },
        { w: "RESİM", h: "Görsel sanat eseri." },
        { w: "SABAH", h: "Günün ilk vakti." },
        { w: "SAHNE", h: "Tiyatro podyumu." },
        { w: "SALON", h: "Büyük oda." },
        { w: "ŞEKER", h: "Tatlı madde." },
        { w: "ŞEHİR", h: "Büyük yerleşim yeri." },
        { w: "TABLO", h: "Resim çerçevesi." },
        { w: "TAHTA", h: "Ahşap levha." },
        { w: "TAKSİ", h: "Ücretli taşıt." },
        { w: "TARIM", h: "Ziraat." },
        { w: "TATLI", h: "Acı olmayan lezzet." },
        { w: "TAVAN", h: "Odanın üstü." },
        { w: "TEMİZ", h: "Kirli olmayan." },
        { w: "TENİS", h: "Raket sporu." },
        { w: "TERZİ", h: "Giysi diken kişi." },
        { w: "TOHUM", h: "Bitki çekirdeği." },
        { w: "UÇAK", h: "Hava taşıtı." },
        { w: "ÜZGÜN", h: "Kederli, mutsuz." },
        { w: "VATAN", h: "Yurt, memleket." },
        { w: "YANAK", h: "Yüzün iki yanı." },
        { w: "YANIT", h: "Cevap." },
        { w: "YAŞLI", h: "Kıdemli, ihtiyar." },
        { w: "YAVAŞ", h: "Hızlı olmayan." },
        { w: "ZAMAN", h: "Vakit." },
        { w: "DOĞAL", h: "Yapay olmayan." },
        { w: "YONCA", h: "Çayır bitkisi." },
        { w: "SEVGİ", h: "Bağlılık duygusu." },
        { w: "BEBEK", h: "Yeni doğmuş çocuk." },
        { w: "ZARİF", h: "Şık, ince." }
    ],

    // ─────────────────────────────────────────────
    //  6 HARFLİ KELİMELER
    // ─────────────────────────────────────────────
    6: [
        { w: "KAMERA", h: "Görüntü kaydeden cihaz." },
        { w: "GAZETE", h: "Günlük haber yayını." },
        { w: "MİMARİ", h: "Yapı tasarımı." },
        { w: "FUTBOL", h: "Ayakla oynanan takım sporu." },
        { w: "BAYRAK", h: "Ülke sembolü bez." },
        { w: "ZEYTİN", h: "Akdeniz meyvesi." },
        { w: "MEYDAN", h: "Geniş alan." },
        { w: "MİKTAR", h: "Nicelik, tutar." },
        { w: "MİLLET", h: "Ulus." },
        { w: "MİLYON", h: "Altı sıfırlı sayı." },
        { w: "MODERN", h: "Çağdaş." },
        { w: "MUTFAK", h: "Yemek pişirilen yer." },
        { w: "PANJUR", h: "Pencere örtüsü." },
        { w: "PARFÜM", h: "Güzel koku." },
        { w: "PARLAK", h: "Işıldayan." },
        { w: "PATRON", h: "İşveren." },
        { w: "PEYNİR", h: "Sütten yapılan katı yiyecek." },
        { w: "PETROL", h: "Siyah altın, yakıt." },
        { w: "PORTAL", h: "Ana giriş kapısı." },
        { w: "REÇETE", h: "İlaç listesi." },
        { w: "REHBER", h: "Kılavuz." },
        { w: "REKLAM", h: "Tanıtım." },
        { w: "SAĞLIK", h: "Sıhhat." },
        { w: "SANİYE", h: "Zaman birimi." },
        { w: "SANSÜR", h: "Denetleme, kısıtlama." },
        { w: "SATICI", h: "Satan kişi." },
        { w: "SEMBOL", h: "Simge." },
        { w: "SENTEZ", h: "Bireşim." },
        { w: "SEVİYE", h: "Düzey." },
        { w: "SİGARA", h: "Tütün ürünü." },
        { w: "SOHBET", h: "Söyleşi, muhabbet." },
        { w: "SOSYAL", h: "Toplumsal." },
        { w: "SÖZLÜK", h: "Kelimeler kitabı, lugat." },
        { w: "SÜRÜCÜ", h: "Şoför." },
        { w: "SÜNGER", h: "Temizlik malzemesi." },
        { w: "ŞABLON", h: "Kalıp." },
        { w: "ŞEFFAF", h: "Saydam." },
        { w: "ŞİMŞEK", h: "Çakan ışık." },
        { w: "ŞİRKET", h: "Ticari ortaklık." },
        { w: "TABLET", h: "Düz bilgisayar." },
        { w: "TAHMİN", h: "Öngörü." },
        { w: "TAKVİM", h: "Zaman cetveli." },
        { w: "TEKNİK", h: "Uygulama bilgisi." },
        { w: "TEKRAR", h: "Yineleme." },
        { w: "TERCİH", h: "Seçim." },
        { w: "TESLİM", h: "Verme." },
        { w: "TOPLAM", h: "Yekün." },
        { w: "TOPLUM", h: "Cemiyet." },
        { w: "TOPRAK", h: "Yer, arazi." },
        { w: "TURİZM", h: "Gezginlik." },
        { w: "ULUSAL", h: "Milli." },
        { w: "ÜRETİM", h: "İmalat." },
        { w: "VİCDAN", h: "İç ses." },
        { w: "VİZYON", h: "Görüş, gösterim." },
        { w: "VOLKAN", h: "Yanardağ." },
        { w: "YALNIZ", h: "Tek başına." },
        { w: "YAPRAK", h: "Ağacın yeşil kısmı." },
        { w: "YARDIM", h: "İmdat, destek." },
        { w: "YAZICI", h: "Printer." },
        { w: "YILDIZ", h: "Gökyüzünde parlayan cisim." },
        { w: "YÖNTEM", h: "Metot." },
        { w: "ZİNCİR", h: "Halkalar dizisi." },
        { w: "KUZGUN", h: "Siyah büyük kuş." },
        { w: "BASTON", h: "Yürürken alınan destek." },
        { w: "TİMSAH", h: "Vahşi bir sürüngen." },
        { w: "ENERJİ", h: "Güç kaynağı." },
        { w: "PİKNİK", h: "Açık havada yenilen yemek." },
        { w: "RÜZGAR", h: "Yel." },
        { w: "YOĞURT", h: "Mayalanmış süt." }
    ],

    // ─────────────────────────────────────────────
    //  7 HARFLİ KELİMELER
    // ─────────────────────────────────────────────
    7: [
        { w: "MERHABA", h: "Selamlaşma sözü." },
        { w: "PENCERE", h: "Duvarlardaki camlı açıklık." },
        { w: "TÜRKİYE", h: "Vatanımız." },
        { w: "TELEFON", h: "İletişim aracı." },
        { w: "JÜPİTER", h: "En büyük gezegen." },
        { w: "YAZILIM", h: "Bilgisayar programı." },
        { w: "MONİTÖR", h: "Ekran." },
        { w: "GEZEGEN", h: "Gök cismi." },
        { w: "DİJİTAL", h: "Sayısal." },
        { w: "PROGRAM", h: "İzlence." },
        { w: "AKADEMİ", h: "Yüksek okul." },
        { w: "AMBALAJ", h: "Paketleme malzemesi." },
        { w: "ANATOMİ", h: "Vücut yapısı bilimi." },
        { w: "ANLAŞMA", h: "Uzlaşma, kontrat." },
        { w: "ARKADAŞ", h: "Dost." },
        { w: "AVANTAJ", h: "Üstünlük sağlayan durum." },
        { w: "AYRINTI", h: "Detay." },
        { w: "BATARYA", h: "Pil grubu." },
        { w: "BULMACA", h: "Zeka oyunu." },
        { w: "ÇALIŞMA", h: "İş, emek." },
        { w: "ÇAMAŞIR", h: "Yıkanacak giysiler." },
        { w: "DANIŞMA", h: "Bilgi alma yeri." },
        { w: "DENKLEM", h: "Eşitlik." },
        { w: "DİNAMİK", h: "Hareketli." },
        { w: "DİPLOMA", h: "Mezuniyet belgesi." },
        { w: "DİYALOG", h: "Karşılıklı konuşma." },
        { w: "DÜŞÜNCE", h: "Fikir." },
        { w: "EĞLENCE", h: "Keyifli vakit geçirme." },
        { w: "EKOLOJİ", h: "Çevre bilimi." },
        { w: "EKONOMİ", h: "İktisat." },
        { w: "EMNİYET", h: "Güvenlik." },
        { w: "FABRİKA", h: "Üretim tesisi." },
        { w: "FASULYE", h: "Bir baklagil." },
        { w: "FELAKET", h: "Büyük yıkım." },
        { w: "FELSEFE", h: "Düşünce bilimi." },
        { w: "FIRTINA", h: "Şiddetli rüzgar." },
        { w: "GALAKSİ", h: "Gökada." },
        { w: "GARANTİ", h: "Güvence." },
        { w: "GELECEK", h: "Ati, istikbal." },
        { w: "GELENEK", h: "Adet, töre." },
        { w: "GENÇLİK", h: "Tazelik çağı." },
        { w: "GENETİK", h: "Kalıtım bilimi." },
        { w: "GERİLİM", h: "Tansiyon." },
        { w: "GÖKYÜZÜ", h: "Sema." },
        { w: "GÜVENLİ", h: "Emniyetli." },
        { w: "HABERCİ", h: "Haber getiren." },
        { w: "HAREKET", h: "Kımıldama." },
        { w: "HASTANE", h: "Şifa yurdu." },
        { w: "HEYECAN", h: "Coşku." },
        { w: "ISPANAK", h: "Demir deposu sebze." },
        { w: "İHRACAT", h: "Dış satım." },
        { w: "İHTİMAL", h: "Olasılık." },
        { w: "İHTİYAÇ", h: "Gereksinim." },
        { w: "İNCELİK", h: "Zarafet." },
        { w: "İSKELET", h: "Kemik çatısı." },
        { w: "İTFAİYE", h: "Yangın söndürme ekibi." },
        { w: "KARINCA", h: "Çalışkan böcek." },
        { w: "KELEBEK", h: "Renkli kanatlı böcek." },
        { w: "KILAVUZ", h: "Rehber." },
        { w: "KIRMIZI", h: "Al renk." },
        { w: "KOMUTAN", h: "Askeri yönetici." },
        { w: "KONTROL", h: "Denetim." },
        { w: "KORİDOR", h: "Geçit, hol." },
        { w: "KRİSTAL", h: "Parlak cam." },
        { w: "MALZEME", h: "Gereç." },
        { w: "MANZARA", h: "Görünüm." },
        { w: "MARATON", h: "Uzun koşu." },
        { w: "MEKANİK", h: "Makine ile ilgili." },
        { w: "MENEKŞE", h: "Bir çiçek." },
        { w: "MOBİLYA", h: "Ev eşyası." },
        { w: "MÜZİKAL", h: "Müzikli oyun." },
        { w: "NAKLİYE", h: "Taşıma işi." },
        { w: "NEGATİF", h: "Olumsuz." },
        { w: "NİLÜFER", h: "Su çiçeği." },
        { w: "OKYANUS", h: "Büyük deniz." },
        { w: "PALMİYE", h: "Sıcak iklim ağacı." },
        { w: "PAPAĞAN", h: "Konuşan kuş." },
        { w: "PAPATYA", h: "Beyaz yapraklı çiçek." },
        { w: "PARALEL", h: "Kesişmeyen doğrular." },
        { w: "PATATES", h: "Nişastalı sebze." },
        { w: "PİRAMİT", h: "Mısır'daki anıt mezarlar." },
        { w: "PİYANGO", h: "Şans oyunu." },
        { w: "POZİTİF", h: "Olumlu." },
        { w: "PRENSİP", h: "İlke." },
        { w: "PROBLEM", h: "Sorun." },
        { w: "RANDEVU", h: "Buluşma." },
        { w: "REKABET", h: "Yarışma." },
        { w: "SABIRLI", h: "Acele etmeyen." },
        { w: "SANATÇI", h: "Sanat yapan." },
        { w: "SANTRAL", h: "Merkez istasyonu." },
        { w: "SATRANÇ", h: "Zeka oyunu." },
        { w: "SEÇENEK", h: "Alternatif." },
        { w: "SEMİNER", h: "Bilgi şöleni." },
        { w: "SENARYO", h: "Film metni." },
        { w: "SERAMİK", h: "Pişmiş toprak sanatı." },
        { w: "SİGORTA", h: "Güvence sistemi." },
        { w: "SİMETRİ", h: "Bakışım." },
        { w: "SİYASET", h: "Politika." },
        { w: "STADYUM", h: "Spor alanı." },
        { w: "SÜRPRİZ", h: "Beklenmedik olay." },
        { w: "ŞEMSİYE", h: "Yağmur koruyucusu." },
        { w: "ŞÖVALYE", h: "Savaşçı soylu." },
        { w: "TAAHHÜT", h: "Söz verme." },
        { w: "TASARIM", h: "Dizayn." },
        { w: "TAVSİYE", h: "Öğüt." },
        { w: "TEHLİKE", h: "Risk." },
        { w: "TENCERE", h: "Yemek pişirme kabı." },
        { w: "TİYATRO", h: "Sahne sanatı." },
        { w: "TRAKTÖR", h: "Tarım aracı." },
        { w: "TÜKETİM", h: "Kullanım." },
        { w: "UÇURTMA", h: "Rüzgarla uçurulan oyuncak." },
        { w: "VİTAMİN", h: "Besin öğesi." },
        { w: "YABANCI", h: "Tanıdık olmayan." },
        { w: "YARIŞMA", h: "Müsabaka." },
        { w: "YATIRIM", h: "Kazanç için harcama." },
        { w: "YELPAZE", h: "Serinletme aracı." },
        { w: "YETENEK", h: "Kabiliyet." },
        { w: "YÖNETİM", h: "İdare." },
        { w: "YUMURTA", h: "Tavuğun ürünü." },
        { w: "ZİYARET", h: "Görüşmeye gitme." },
        { w: "ANLATIM", h: "İfade ediş." },
        { w: "KESTANE", h: "Kış meyvesi." },
        { w: "LAVANTA", h: "Güzel kokulu bitki." },
        { w: "ŞAMPUAN", h: "Saç yıkama maddesi." },
        { w: "ÇEKİRGE", h: "Sıçrayan böcek." },
        { w: "ARMAĞAN", h: "Hediye." }
    ]
};
