window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Popüler ve Tanınmış Ülkeler
    { kategori: "Başkent", seviye: 1, soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 1, soru: "Fransa'nın başkenti neresidir?", secenekler: { A: "Lyon", B: "Marsilya", C: "Paris", D: "Nice" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 1, soru: "Almanya'nın başkenti neresidir?", secenekler: { A: "Münih", B: "Berlin", C: "Frankfurt", D: "Hamburg" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 2, soru: "İngiltere'nin başkenti neresidir?", secenekler: { A: "Londra", B: "Manchester", C: "Liverpool", D: "Birmingham" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 2, soru: "İtalya'nın başkenti neresidir?", secenekler: { A: "Milano", B: "Venedik", C: "Floransa", D: "Roma" }, dogruCevap: "D" },
    { kategori: "Başkent", seviye: 2, soru: "İspanya'nın başkenti neresidir?", secenekler: { A: "Barselona", B: "Madrid", C: "Valensiya", D: "Sevilla" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 3, soru: "Rusya'nın başkenti neresidir?", secenekler: { A: "St. Petersburg", B: "Moskova", C: "Kazan", D: "Novosibirsk" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 3, soru: "Amerika Birleşik Devletleri'nin başkenti neresidir?", secenekler: { A: "New York", B: "Washington D.C.", C: "Los Angeles", D: "Chicago" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 3, soru: "Japonya'nın başkenti neresidir?", secenekler: { A: "Osaka", B: "Kyoto", C: "Tokyo", D: "Hiroşima" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 4, soru: "Çin'in başkenti neresidir?", secenekler: { A: "Şanghay", B: "Pekin", C: "Hong Kong", D: "Guangzhou" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 4, soru: "Azerbaycan'ın başkenti neresidir?", secenekler: { A: "Bakü", B: "Gence", C: "Sumgayıt", D: "Nahçıvan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 4, soru: "Yunanistan'ın başkenti neresidir?", secenekler: { A: "Selanik", B: "Atina", C: "Patras", D: "Kandiye" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 5, soru: "Mısır'ın başkenti neresidir?", secenekler: { A: "İskenderiye", B: "Kahire", C: "Luksor", D: "Gize" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 5, soru: "Hollanda'nın başkenti neresidir?", secenekler: { A: "Rotterdam", B: "Lahey", C: "Amsterdam", D: "Utrecht" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 5, soru: "Brezilya'nın başkenti neresidir?", secenekler: { A: "Rio de Janeiro", B: "Sao Paulo", C: "Brasilia", D: "Salvador" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 6, soru: "Güney Kore'nin başkenti neresidir?", secenekler: { A: "Busan", B: "Seul", C: "Incheon", D: "Daegu" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 6, soru: "Arjantin'in başkenti neresidir?", secenekler: { A: "Buenos Aires", B: "Cordoba", C: "Rosario", D: "Mendoza" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 6, soru: "Hindistan'ın başkenti neresidir?", secenekler: { A: "Mumbai", B: "Yeni Delhi", C: "Kalküta", D: "Chennai" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 7, soru: "Kanada'nın başkenti neresidir?", secenekler: { A: "Toronto", B: "Montreal", C: "Ottawa", D: "Vancouver" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 7, soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Zürih", B: "Cenevre", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 7, soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Viyana", B: "Salzburg", C: "Innsbruck", D: "Graz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 8, soru: "İran'ın başkenti neresidir?", secenekler: { A: "Tebriz", B: "Meşhed", C: "Tahran", D: "İsfahan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 8, soru: "Irak'ın başkenti neresidir?", secenekler: { A: "Basra", B: "Bağdat", C: "Musul", D: "Erbil" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 8, soru: "Suudi Arabistan'ın başkenti neresidir?", secenekler: { A: "Cidde", B: "Mekke", C: "Riyad", D: "Medine" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 9, soru: "Portekiz'in başkenti neresidir?", secenekler: { A: "Porto", B: "Lizbon", C: "Braga", D: "Coimbra" }, dogruCevap: "B" },

    // 26-50: Avrupa ve Asya Detayları
    { kategori: "Başkent", seviye: 10, soru: "Ukrayna'nın başkenti neresidir?", secenekler: { A: "Harkiv", B: "Kiev", C: "Odessa", D: "Lviv" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 10, soru: "Belçika'nın başkenti neresidir?", secenekler: { A: "Brüksel", B: "Anvers", C: "Gent", D: "Brugge" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 11, soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Krakov", B: "Varşova", C: "Gdansk", D: "Wroclaw" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 11, soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Budapeşte", B: "Debrecen", C: "Pecs", D: "Segedin" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 12, soru: "Çek Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Prag", B: "Brno", C: "Ostrava", D: "Plzen" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 12, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Kosice", C: "Nitra", D: "Zilina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 13, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Split", B: "Zagreb", C: "Dubrovnik", D: "Zadar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 13, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Belgrad", B: "Novi Sad", C: "Niş", D: "Kragujevac" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 14, soru: "Bulgaristan'ın başkenti neresidir?", secenekler: { A: "Filibe", B: "Sofya", C: "Varna", D: "Burgas" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 14, soru: "Romanya'nın başkenti neresidir?", secenekler: { A: "Bükreş", B: "Kaloşvar", C: "Köstence", D: "Yaş" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 15, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Dublin", B: "Cork", C: "Galway", D: "Belfast" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 15, soru: "İskoçya'nın başkenti neresidir?", secenekler: { A: "Glasgow", B: "Edinburgh", C: "Aberdeen", D: "Dundee" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 16, soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Bergen", B: "Oslo", C: "Trondheim", D: "Stavanger" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 16, soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Goteborg", B: "Stockholm", C: "Malmö", D: "Uppsala" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 17, soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Tampere", B: "Helsinki", C: "Turku", D: "Oulu" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 17, soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Kopenhag", B: "Aarhus", C: "Odense", D: "Aalborg" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 18, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Phuket", B: "Bangkok", C: "Chiang Mai", D: "Pattaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 18, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Cakarta", B: "Bali", C: "Surabaya", D: "Bandung" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 19, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh", B: "Hanoi", C: "Da Nang", D: "Hue" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 19, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "Lahor", C: "İslamabad", D: "Peşaver" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 20, soru: "Kazakistan'ın başkenti neresidir?", secenekler: { A: "Almati", B: "Astana", C: "Çimkent", D: "Aktau" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 20, soru: "Özbekistan'ın başkenti neresidir?", secenekler: { A: "Semerkant", B: "Taşkent", C: "Buhara", D: "Hiva" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 21, soru: "Türkmenistan'ın başkenti neresidir?", secenekler: { A: "Aşkabat", B: "Merv", C: "Türkmenbaşı", D: "Daşoğuz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 21, soru: "Kırgızistan'ın başkenti neresidir?", secenekler: { A: "Oş", B: "Bişkek", C: "Celal-Abad", D: "Narın" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 22, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Tiflis", C: "Kutaisi", D: "Gori" }, dogruCevap: "B" },

    // 51-75: Orta Doğu, Afrika ve Amerika Kıtası
    { kategori: "Başkent", seviye: 23, soru: "Suriye'nın başkenti neresidir?", secenekler: { A: "Halep", B: "Şam", C: "Humus", D: "Lazkiye" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 23, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Trablusşam", B: "Beyrut", C: "Sayda", D: "Zahle" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 24, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Akabe", B: "Amman", C: "İrbid", D: "Zarka" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 24, soru: "İsrail'in başkenti (uluslararası tanınırlığa göre en büyük şehri) neresidir?", secenekler: { A: "Kudüs", B: "Tel Aviv", C: "Hayfa", D: "Eylat" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 25, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Kazablanka", B: "Marakeş", C: "Rabat", D: "Fes" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 25, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Oran", B: "Cezayir", C: "Konstantin", D: "Annabe" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 26, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Tunus", C: "Kayrevan", D: "Bizerte" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 26, soru: "Güney Afrika Cumhuriyeti'nin üç başkentinden biri hangisidir?", secenekler: { A: "Johannesburg", B: "Cape Town", C: "Durban", D: "Soweto" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 27, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Lagos", B: "Abuja", C: "Kano", D: "Ibadan" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 27, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Mombasa", B: "Nairobi", C: "Kisumu", D: "Nakuru" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 28, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Dire Dawa", C: "Gondar", D: "Lalibela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 28, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Cancun", B: "Meksiko", C: "Guadalajara", D: "Monterrey" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 29, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Santiago", B: "Havana", C: "Varadero", D: "Holguin" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 29, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Medellin", B: "Bogota", C: "Cali", D: "Cartagena" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 30, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Cusco", B: "Lima", C: "Arequipa", D: "Iquitos" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 30, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Valparaiso", B: "Santiago", C: "Concepcion", D: "Antofagasta" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 31, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Punta del Este", C: "Salto", D: "Colonia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 31, soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Perth" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 32, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Auckland", B: "Wellington", C: "Christchurch", D: "Queenstown" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 32, soru: "Güney Kıbrıs Rum Yönetimi'nin başkenti neresidir?", secenekler: { A: "Limasol", B: "Larnaka", C: "Lefkoşa", D: "Baf" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 33, soru: "Kuzey Kıbrıs Türk Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Girne", B: "Gazimağusa", C: "Lefkoşa", D: "Güzelyurt" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 33, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kandahar", B: "Kabil", C: "Herat", D: "Mezar-ı Şerif" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 34, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Manila", B: "Cebu", C: "Davao", D: "Quezon" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 34, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "George Town", C: "Johor Bahru", D: "Melaka" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 35, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Erdenet", C: "Darhan", D: "Ölgii" }, dogruCevap: "A" },

    // 76-100: Zor ve Daha Az Bilinenler
    { kategori: "Başkent", seviye: 36, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Reykjavik", B: "Akureyri", C: "Keflavik", D: "Vík" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 36, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Valletta", B: "Sliema", C: "Mdina", D: "St. Julian's" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 37, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Lüksemburg", B: "Esch", C: "Diekirch", D: "Echternach" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 37, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Pärnu", D: "Narva" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 38, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Liepaja", C: "Daugavpils", D: "Jurmala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 38, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Vilnius", B: "Kaunas", C: "Klaipeda", D: "Siauliai" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 39, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Ljubljana", B: "Maribor", C: "Celje", D: "Koper" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 39, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Durres", C: "Vlora", D: "İşkodra" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 40, soru: "Makedonya'nın (Kuzey Makedonya) başkenti neresidir?", secenekler: { A: "Üsküp", B: "Manastır", C: "Ohrid", D: "Tetovo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 40, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Kotor", C: "Budva", D: "Çetine" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 41, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Saraybosna", B: "Mostar", C: "Banja Luka", D: "Tuzla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 41, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Erivan", B: "Gümrü", C: "Vanadzor", D: "Dilican" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 42, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Sylhet", D: "Rajshahi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 42, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Katmandu", B: "Pokhara", C: "Lalitpur", D: "Biratnagar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 43, soru: "Sri Lanka'nın başkenti neresidir?", secenekler: { A: "Kolombo", B: "Kandy", C: "Galle", D: "Jaffna" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 43, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Wakrah", C: "Al Khor", D: "Lusail" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 44, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Kuveyt", B: "Jahra", C: "Ahmadi", D: "Salmiya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 44, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Muskat", B: "Salalah", C: "Nizwa", D: "Sohar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 45, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Sana", B: "Aden", C: "Taiz", D: "Hodeida" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 45, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Trablus", B: "Bingazi", C: "Misrata", D: "Tobruk" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 46, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Saint-Louis", C: "Thies", D: "Ziguinchor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 46, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Akra", B: "Kumasi", C: "Tamale", D: "Sekondi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 47, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antananarivo", B: "Toamasina", C: "Mahajanga", D: "Antsirabe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 48, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Quito", B: "Guayaquil", C: "Cuenca", D: "Manta" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 49, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Karakas", B: "Maracaibo", C: "Valencia", D: "Merida" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 50, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum", B: "Omdurman", C: "Port Sudan", D: "Kassala" }, dogruCevap: "A" }, 
    // Başkent Soruları Devamı (51 - 150)
    { kategori: "Başkent", seviye: 51, soru: "Tayland'ın başkenti neresidir?", secenekler: { A: "Phuket", B: "Bangkok", C: "Chiang Mai", D: "Pattaya" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 52, soru: "Güney Afrika Cumhuriyeti'nin yürütme başkenti hangisidir?", secenekler: { A: "Johannesburg", B: "Pretoria", C: "Cape Town", D: "Durban" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 53, soru: "Vietnam'ın başkenti neresidir?", secenekler: { A: "Ho Chi Minh", B: "Hanoi", C: "Da Nang", D: "Hue" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 54, soru: "Küba'nın başkenti neresidir?", secenekler: { A: "Havana", B: "Santiago", C: "Varadero", D: "Holguin" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 55, soru: "Norveç'in başkenti neresidir?", secenekler: { A: "Bergen", B: "Oslo", C: "Trondheim", D: "Stavanger" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 56, soru: "İsveç'in başkenti neresidir?", secenekler: { A: "Stockholm", B: "Goteborg", C: "Malmö", D: "Uppsala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 57, soru: "Finlandiya'nın başkenti neresidir?", secenekler: { A: "Tampere", B: "Turku", C: "Helsinki", D: "Espoo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 58, soru: "Danimarka'nın başkenti neresidir?", secenekler: { A: "Kopenhag", B: "Aarhus", C: "Odense", D: "Aalborg" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 59, soru: "İrlanda'nın başkenti neresidir?", secenekler: { A: "Belfast", B: "Dublin", C: "Cork", D: "Galway" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 60, soru: "İsviçre'nin başkenti neresidir?", secenekler: { A: "Zürih", B: "Cenevre", C: "Bern", D: "Basel" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 61, soru: "Avusturya'nın başkenti neresidir?", secenekler: { A: "Viyana", B: "Salzburg", C: "Innsbruck", D: "Graz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 62, soru: "Belçika'nın başkenti neresidir?", secenekler: { A: "Brüksel", B: "Anvers", C: "Gent", D: "Brugge" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 63, soru: "Macaristan'ın başkenti neresidir?", secenekler: { A: "Debrecen", B: "Budapeşte", C: "Pécs", D: "Szeged" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 64, soru: "Çek Cumhuriyeti'nın başkenti neresidir?", secenekler: { A: "Prag", B: "Brno", C: "Ostrava", D: "Plzeň" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 65, soru: "Polonya'nın başkenti neresidir?", secenekler: { A: "Krakov", B: "Gdańsk", C: "Varşova", D: "Wrocław" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 66, soru: "Romanya'nın başkenti neresidir?", secenekler: { A: "Bükreş", B: "Kaloşvar", C: "Köstence", D: "Yaş" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 67, soru: "Bulgaristan'ın başkenti neresidir?", secenekler: { A: "Filibe", B: "Varna", C: "Sofya", D: "Burgaz" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 68, soru: "Sırbistan'ın başkenti neresidir?", secenekler: { A: "Belgrad", B: "Novi Sad", C: "Niş", D: "Kragujevac" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 69, soru: "Hırvatistan'ın başkenti neresidir?", secenekler: { A: "Split", B: "Zagreb", C: "Dubrovnik", D: "Rijeka" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 70, soru: "Slovenya'nın başkenti neresidir?", secenekler: { A: "Ljubljana", B: "Maribor", C: "Celje", D: "Koper" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 71, soru: "Lüksemburg'un başkenti neresidir?", secenekler: { A: "Lüksemburg", B: "Esch", C: "Diekirch", D: "Echternach" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 72, soru: "Monako'nun başkenti neresidir?", secenekler: { A: "Monako", B: "Monte Carlo", C: "Cannes", D: "Nice" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 73, soru: "Vatikan'ın başkenti neresidir?", secenekler: { A: "Vatikan", B: "Roma", C: "Floransa", D: "Milano" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 74, soru: "Malta'nın başkenti neresidir?", secenekler: { A: "Valletta", B: "Sliema", C: "Mdina", D: "Gozo" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 75, soru: "İzlanda'nın başkenti neresidir?", secenekler: { A: "Reykjavik", B: "Akureyri", C: "Keflavik", D: "Vik" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 76, soru: "Fas'ın başkenti neresidir?", secenekler: { A: "Kazablanka", B: "Marakeş", C: "Rabat", D: "Fes" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 77, soru: "Cezayir'in başkenti neresidir?", secenekler: { A: "Oran", B: "Cezayir", C: "Konstantin", D: "Annabe" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 78, soru: "Tunus'un başkenti neresidir?", secenekler: { A: "Susa", B: "Tunus", C: "Safakes", D: "Kayrevan" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 79, soru: "Libya'nın başkenti neresidir?", secenekler: { A: "Bingazi", B: "Misrata", C: "Trablus", D: "Tobruk" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 80, soru: "Sudan'ın başkenti neresidir?", secenekler: { A: "Hartum", B: "Cub", C: "Omdurman", D: "Port Sudan" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 81, soru: "Etiyopya'nın başkenti neresidir?", secenekler: { A: "Addis Ababa", B: "Dire Dawa", C: "Gondar", D: "Lalibela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 82, soru: "Kenya'nın başkenti neresidir?", secenekler: { A: "Mombasa", B: "Nairobi", C: "Kisumu", D: "Eldoret" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 83, soru: "Nijerya'nın başkenti neresidir?", secenekler: { A: "Lagos", B: "Kano", C: "Abuja", D: "Ibadan" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 84, soru: "Gana'nın başkenti neresidir?", secenekler: { A: "Kumasi", B: "Akra", C: "Tamale", D: "Sekondi" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 85, soru: "Senegal'in başkenti neresidir?", secenekler: { A: "Dakar", B: "Saint-Louis", C: "Thiès", D: "Ziguinchor" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 86, soru: "Somali'nin başkenti neresidir?", secenekler: { A: "Hargeisa", B: "Mogadişu", C: "Kismayo", D: "Berbera" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 87, soru: "Lübnan'ın başkenti neresidir?", secenekler: { A: "Trablusşam", B: "Beyrut", C: "Sayda", D: "Zahle" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 88, soru: "Ürdün'ün başkenti neresidir?", secenekler: { A: "Akabe", B: "Zarka", C: "Amman", D: "İrbid" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 89, soru: "Kuveyt'in başkenti neresidir?", secenekler: { A: "Kuveyt City", B: "Al Jahra", C: "Ahmadi", D: "Salmiya" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 90, soru: "Katar'ın başkenti neresidir?", secenekler: { A: "Doha", B: "Al Khor", C: "Al Wakrah", D: "Lusail" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 91, soru: "Birleşik Arap Emirlikleri'nin başkenti neresidir?", secenekler: { A: "Dubai", B: "Abu Dabi", C: "Şarika", D: "Acman" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 92, soru: "Umman'ın başkenti neresidir?", secenekler: { A: "Maskat", B: "Salalah", C: "Nizwa", D: "Sohar" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 93, soru: "Yemen'in başkenti neresidir?", secenekler: { A: "Aden", B: "Taiz", C: "Sana", D: "Hudeyde" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 94, soru: "Afganistan'ın başkenti neresidir?", secenekler: { A: "Kandahar", B: "Mezar-ı Şerif", C: "Kabil", D: "Herat" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 95, soru: "Pakistan'ın başkenti neresidir?", secenekler: { A: "Karaçi", B: "İslamabad", C: "Lahor", D: "Peşaver" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 96, soru: "Bangladeş'in başkenti neresidir?", secenekler: { A: "Dakka", B: "Chittagong", C: "Sylhet", D: "Rajshahi" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 97, soru: "Nepal'in başkenti neresidir?", secenekler: { A: "Pokhara", B: "Katmandu", C: "Lalitpur", D: "Biratnagar" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 98, soru: "Sri Lanka'nın idari başkenti neresidir?", secenekler: { A: "Kolombo", B: "Kandy", C: "Sri Jayawardenepura Kotte", D: "Galle" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 99, soru: "Moğolistan'ın başkenti neresidir?", secenekler: { A: "Ulanbatur", B: "Erdenet", C: "Darhan", D: "Ölgii" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 100, soru: "Kuzey Kore'nin başkenti neresidir?", secenekler: { A: "Pyongyang", B: "Kaesong", C: "Wonsan", D: "Hamhung" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 101, soru: "Filipinler'in başkenti neresidir?", secenekler: { A: "Cebu", B: "Davao", C: "Manila", D: "Quezon" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 102, soru: "Malezya'nın başkenti neresidir?", secenekler: { A: "Kuala Lumpur", B: "George Town", C: "Kota Kinabalu", D: "Kuching" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 103, soru: "Endonezya'nın başkenti neresidir?", secenekler: { A: "Bali", B: "Cakarta", C: "Surabaya", D: "Bandung" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 104, soru: "Yeni Zelanda'nın başkenti neresidir?", secenekler: { A: "Auckland", B: "Wellington", C: "Christchurch", D: "Hamilton" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 105, soru: "Avustralya'nın başkenti neresidir?", secenekler: { A: "Sidney", B: "Melbourne", C: "Canberra", D: "Brisbane" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 106, soru: "Kolombiya'nın başkenti neresidir?", secenekler: { A: "Medellin", B: "Bogota", C: "Cali", D: "Cartagena" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 107, soru: "Venezuela'nın başkenti neresidir?", secenekler: { A: "Karakas", B: "Maracaibo", C: "Valencia", D: "Barquisimeto" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 108, soru: "Peru'nun başkenti neresidir?", secenekler: { A: "Cusco", B: "Arequipa", C: "Lima", D: "Trujillo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 109, soru: "Şili'nin başkenti neresidir?", secenekler: { A: "Valparaiso", B: "Santiago", C: "Concepcion", D: "Antofagasta" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 110, soru: "Uruguay'ın başkenti neresidir?", secenekler: { A: "Montevideo", B: "Punta del Este", C: "Salto", D: "Paysandu" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 111, soru: "Paraguay'ın başkenti neresidir?", secenekler: { A: "Asuncion", B: "Ciudad del Este", C: "Encarnacion", D: "Luque" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 112, soru: "Bolivya'nın idari başkenti neresidir?", secenekler: { A: "Sucre", B: "La Paz", C: "Santa Cruz", D: "Cochabamba" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 113, soru: "Ekvador'un başkenti neresidir?", secenekler: { A: "Guayaquil", B: "Cuenca", C: "Quito", D: "Manta" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 114, soru: "Panama'nın başkenti neresidir?", secenekler: { A: "Panama City", B: "Colon", C: "David", D: "Chitré" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 115, soru: "Kosta Rika'nın başkenti neresidir?", secenekler: { A: "San Jose", B: "Limon", C: "Alajuela", D: "Heredia" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 116, soru: "Guatemala'nın başkenti neresidir?", secenekler: { A: "Guatemala City", B: "Antigua", C: "Quetzaltenango", D: "Escuintla" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 117, soru: "Meksika'nın başkenti neresidir?", secenekler: { A: "Cancun", B: "Meksiko", C: "Guadalajara", D: "Monterrey" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 118, soru: "Jamaika'nın başkenti neresidir?", secenekler: { A: "Kingston", B: "Montego Bay", C: "Ocho Rios", D: "Negril" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 119, soru: "Haiti'nin başkenti neresidir?", secenekler: { A: "Cap-Haitien", B: "Port-au-Prince", C: "Les Cayes", D: "Jacmel" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 120, soru: "Dominik Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Punta Cana", B: "Santo Domingo", C: "Santiago", D: "La Romana" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 121, soru: "Estonya'nın başkenti neresidir?", secenekler: { A: "Tallinn", B: "Tartu", C: "Pärnu", D: "Narva" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 122, soru: "Letonya'nın başkenti neresidir?", secenekler: { A: "Riga", B: "Liepaja", C: "Daugavpils", D: "Jurmala" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 123, soru: "Litvanya'nın başkenti neresidir?", secenekler: { A: "Kaunas", B: "Vilnius", C: "Klaipeda", D: "Siauliai" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 124, soru: "Beyaz Rusya (Belarus)'nun başkenti neresidir?", secenekler: { A: "Minsk", B: "Brest", C: "Gomel", D: "Grodno" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 125, soru: "Moldova'nın başkenti neresidir?", secenekler: { A: "Tiraspol", B: "Kişinev", C: "Balti", D: "Bender" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 126, soru: "Gürcistan'ın başkenti neresidir?", secenekler: { A: "Batum", B: "Tiflis", C: "Kutaisi", D: "Gori" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 127, soru: "Ermenistan'ın başkenti neresidir?", secenekler: { A: "Gümrü", B: "Vanadzor", C: "Erivan", D: "Dilican" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 128, soru: "Arnavutluk'un başkenti neresidir?", secenekler: { A: "Tiran", B: "Durrës", C: "Vlorë", D: "İşkodra" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 129, soru: "Bosna-Hersek'in başkenti neresidir?", secenekler: { A: "Mostar", B: "Saraybosna", C: "Banja Luka", D: "Tuzla" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 130, soru: "Karadağ'ın başkenti neresidir?", secenekler: { A: "Podgorica", B: "Kotor", C: "Budva", D: "Çetine" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 131, soru: "Kuzey Makedonya'nın başkenti neresidir?", secenekler: { A: "Manastır", B: "Ohrid", C: "Üsküp", D: "Tetovo" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 132, soru: "Kıbrıs Cumhuriyeti'nin başkenti neresidir?", secenekler: { A: "Lefkoşa", B: "Limasol", C: "Larnaka", D: "Baf" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 133, soru: "Slovakya'nın başkenti neresidir?", secenekler: { A: "Bratislava", B: "Košice", C: "Nitra", D: "Žilina" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 134, soru: "Kamboçya'nın başkenti neresidir?", secenekler: { A: "Siem Reap", B: "Phnom Penh", C: "Sihanoukville", D: "Battambang" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 135, soru: "Laos'un başkenti neresidir?", secenekler: { A: "Vientiane", B: "Luang Prabang", C: "Pakse", D: "Savannakhet" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 136, soru: "Myanmar'ın başkenti neresidir?", secenekler: { A: "Yangon", B: "Mandalay", C: "Naypyidaw", D: "Bago" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 137, soru: "Brunei'nin başkenti neresidir?", secenekler: { A: "Bandar Seri Begawan", B: "Kuala Belait", C: "Seria", D: "Tutong" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 138, soru: "Tanzanya'nın başkenti neresidir?", secenekler: { A: "Darüsselam", B: "Zanzibar", C: "Dodoma", D: "Arusha" }, dogruCevap: "C" },
    { kategori: "Başkent", seviye: 139, soru: "Uganda'nın başkenti neresidir?", secenekler: { A: "Kampala", B: "Entebbe", C: "Jinja", D: "Mbarara" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 140, soru: "Ruanda'nın başkenti neresidir?", secenekler: { A: "Kigali", B: "Butare", C: "Gisenyi", D: "Ruhengeri" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 141, soru: "Angola'nın başkenti neresidir?", secenekler: { A: "Luanda", B: "Huambo", C: "Lobito", D: "Benguela" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 142, soru: "Zambiya'nın başkenti neresidir?", secenekler: { A: "Ndola", B: "Lusaka", C: "Kitwe", D: "Livingstone" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 143, soru: "Zimbabve'nin başkenti neresidir?", secenekler: { A: "Harare", B: "Bulawayo", C: "Mutare", D: "Gweru" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 144, soru: "Botsvana'nın başkenti neresidir?", secenekler: { A: "Gaborone", B: "Francistown", C: "Maun", D: "Kasane" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 145, soru: "Namibya'nın başkenti neresidir?", secenekler: { A: "Windhoek", B: "Swakopmund", C: "Walvis Bay", D: "Lüderitz" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 146, soru: "Mali'nin başkenti neresidir?", secenekler: { A: "Bamako", B: "Timbuktu", C: "Gao", D: "Mopti" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 147, soru: "Fildişi Sahili'nin idari başkenti neresidir?", secenekler: { A: "Abidjan", B: "Yamoussoukro", C: "Bouaké", D: "San-Pédro" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 148, soru: "Kamerun'un başkenti neresidir?", secenekler: { A: "Douala", B: "Yaoundé", C: "Garoua", D: "Bamenda" }, dogruCevap: "B" },
    { kategori: "Başkent", seviye: 149, soru: "Madagaskar'ın başkenti neresidir?", secenekler: { A: "Antananarivo", B: "Toamasina", C: "Mahajanga", D: "Antsirabe" }, dogruCevap: "A" },
    { kategori: "Başkent", seviye: 150, soru: "Mauritius'un başkenti neresidir?", secenekler: { A: "Port Louis", B: "Curepipe", C: "Quatre Bornes", D: "Vacoas" }, dogruCevap: "A" }
 
);
