window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-20: Türk-İslam Bilginleri ve Türk Bilim İnsanları
    { kategori: "Bilim", seviye: 1, soru: "Modern tıbbın babası ve 'Tıbbın Kanunu' kitabının yazarı kimdir?", secenekler: { A: "Farabi", B: "İbn-i Sina", C: "Akşemseddin", D: "Razi" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 2, soru: "Cebir biliminin kurucusu olan Türk-İslam bilgini kimdir?", secenekler: { A: "Harezmi", B: "Ömer Hayyam", C: "Ali Kuşçu", D: "Biruni" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 3, soru: "Sibernetiğin kurucusu ve ilk robotları yapan Artuklu mühendisi kimdir?", secenekler: { A: "Cezeri", B: "Mimar Sinan", C: "Uluğ Bey", D: "İbn-i Heysem" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 4, soru: "Fatih Sultan Mehmet'in İstanbul'a davet ettiği ünlü astronom kimdir?", secenekler: { A: "Piri Reis", B: "Katip Çelebi", C: "Ali Kuşçu", D: "Hezarfen" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 5, soru: "2015 Nobel Kimya Ödülü'nü kazanan Türk bilim insanı kimdir?", secenekler: { A: "Oktay Sinanoğlu", B: "Cahit Arf", C: "Aziz Sancar", D: "Canan Dağdeviren" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 6, soru: "Dünya haritasını en doğru şekilde çizen Osmanlı denizcisi kimdir?", secenekler: { A: "Barbaros Hayrettin", B: "Piri Reis", C: "Seydi Ali Reis", D: "Kılıç Ali Paşa" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 7, soru: "10 TL üzerindeki portresiyle tanınan ünlü matematikçimiz kimdir?", secenekler: { A: "Feza Gürsey", B: "Cahit Arf", C: "Hulusi Behçet", D: "Mazhar Osman" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 8, soru: "Mikrobu Pastuer'den önce tanımlayan 'Maddetü'l-Hayat' yazarı kimdir?", secenekler: { A: "Akşemseddin", B: "İbn-i Nefis", C: "Ebu'l Vefa", D: "Zehravi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 9, soru: "Kendi adıyla anılan bir deri hastalığını tanımlayan Türk doktor kimdir?", secenekler: { A: "Münif Paşa", B: "Hulusi Behçet", C: "Gazi Yaşargil", D: "Sadi Konuk" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 10, soru: "Modern cerrahinin babası sayılan, 'Cerrahiyyetü'l Haniyye' yazarı kimdir?", secenekler: { A: "Sabuncuoğlu Şerefeddin", B: "İbn-i Sina", C: "Razi", D: "Farabi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 11, soru: "Ay'ın haritasını ilk kez çıkaran ve NASA tarafından Ay'da bir bölgeye adı verilen bilgin?", secenekler: { A: "Ali Kuşçu", B: "Uluğ Bey", C: "Biruni", D: "Nasreddin Tusi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 12, soru: "Sosyolojinin kurucusu kabul edilen 'Mukaddime' eseri kime aittir?", secenekler: { A: "İbn-i Haldun", B: "Farabi", C: "Gazali", D: "İbn-i Rüşd" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 13, soru: "Trigonometriye 'tanjant' kavramını kazandıran bilgin kimdir?", secenekler: { A: "Ebu'l Vefa", B: "Ömer Hayyam", C: "Harezmi", D: "Biruni" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 14, soru: "Dünya'nın güneş etrafında döndüğünü Kopernik'ten önce söyleyen 'Tahkik' yazarı?", secenekler: { A: "Biruni", B: "İbn-i Sina", C: "Uluğ Bey", D: "Ali Kuşçu" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 15, soru: "Yüzyılın beyin cerrahı seçilen Türk bilim insanı kimdir?", secenekler: { A: "Gazi Yaşargil", B: "Mehmet Öz", C: "Canan Dağdeviren", D: "Türkan Saylan" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 16, soru: "Sıfır (0) rakamını ilk kez kullanan matematikçi kimdir?", secenekler: { A: "Harezmi", B: "Pisagor", C: "Öklid", D: "Arşimet" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 17, soru: "İlk insansız uçuş denemesini yapan Osmanlı bilgini kimdir?", secenekler: { A: "Hezarfen Ahmed Çelebi", B: "Lagari Hasan Çelebi", C: "Piri Reis", D: "Evliya Çelebi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 18, soru: "İlk roketli uçuşu gerçekleştiren Osmanlı bilgini kimdir?", secenekler: { A: "Lagari Hasan Çelebi", B: "Hezarfen", C: "Ali Kuşçu", D: "Takiyüddin" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 19, soru: "Dünyanın ilk kadın savaş pilotu kimdir?", secenekler: { A: "Sabiha Gökçen", B: "Nene Hatun", C: "Halide Edip", D: "Safiye Ali" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 20, soru: "Türk tarihinin en büyük mimarı, 'Koca Sinan' olarak anılan kişi kimdir?", secenekler: { A: "Mimar Sinan", B: "Mimar Hayreddin", C: "Sedefkar Mehmed Ağa", D: "Mimar Kemalettin" }, dogruCevap: "A" },

    // 21-40: Kimya Formülleri ve Elementler
    { kategori: "Bilim", seviye: 21, soru: "Suyun kimyasal formülü nedir?", secenekler: { A: "H2O", B: "CO2", C: "NaCl", D: "O2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 22, soru: "Sofra tuzunun formülü nedir?", secenekler: { A: "NaCl", B: "HCl", C: "NaOH", D: "KOH" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 23, soru: "Karbondioksit gazının formülü nedir?", secenekler: { A: "CO", B: "CO2", C: "C2O", D: "O2" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 24, soru: "Tuz ruhu olarak bilinen asidin formülü nedir?", secenekler: { A: "H2SO4", B: "HCl", C: "HNO3", D: "HF" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 25, soru: "Zaç yağı olarak bilinen sülfürik asidin formülü nedir?", secenekler: { A: "H2SO4", B: "HCl", C: "HNO3", D: "H3PO4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 26, soru: "Kezzap olarak bilinen nitrik asidin formülü nedir?", secenekler: { A: "HNO3", B: "HCl", C: "NH3", D: "CH4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 27, soru: "Amonyak bileşiğinin formülü nedir?", secenekler: { A: "NH3", B: "NH4", C: "N2H", D: "NO2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 28, soru: "Metan gazının formülü nedir?", secenekler: { A: "CH4", B: "C2H6", C: "CO2", D: "H2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 29, soru: "Gümüş elementinin simgesi nedir?", secenekler: { A: "Au", B: "Ag", C: "Cu", D: "Fe" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 30, soru: "Bakır elementinin simgesi nedir?", secenekler: { A: "Ba", B: "Bk", C: "Cu", D: "C" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 31, soru: "Demir elementinin simgesi nedir?", secenekler: { A: "D", B: "De", C: "Fe", D: "F" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 32, soru: "Kalay elementinin simgesi nedir?", secenekler: { A: "K", B: "Ka", C: "Sn", D: "S" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 33, soru: "Cıva elementinin simgesi nedir?", secenekler: { A: "C", B: "Ci", C: "Hg", D: "Pb" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 34, soru: "Kurşun elementinin simgesi nedir?", secenekler: { A: "K", B: "Pb", C: "Kr", D: "Pu" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 35, soru: "Potasyum elementinin simgesi nedir?", secenekler: { A: "P", B: "Po", C: "K", D: "Pt" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 36, soru: "Sodyum elementinin simgesi nedir?", secenekler: { A: "S", B: "So", C: "Na", D: "N" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 37, soru: "Kalsiyum karbonat (Kireç taşı) formülü nedir?", secenekler: { A: "CaCO3", B: "CaO", C: "Ca(OH)2", D: "CaCl2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 38, soru: "Sirke asidinin formülü nedir?", secenekler: { A: "CH3COOH", B: "HCOOH", C: "C2H5OH", D: "CH4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 39, soru: "Helyum elementinin simgesi nedir?", secenekler: { A: "H", B: "He", C: "Hy", D: "Li" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 40, soru: "Azot elementinin simgesi nedir?", secenekler: { A: "Az", B: "A", C: "N", D: "At" }, dogruCevap: "C" },

    // 41-60: İcatlar ve Teknoloji
    { kategori: "Bilim", seviye: 41, soru: "Telefonun mucidi kimdir?", secenekler: { A: "Graham Bell", B: "Edison", C: "Tesla", D: "Morse" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 42, soru: "Ampulü icat eden bilim insanı kimdir?", secenekler: { A: "Newton", B: "Tesla", C: "Edison", D: "Watt" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 43, soru: "Radyoyu icat eden kişi kimdir?", secenekler: { A: "Marconi", B: "Baird", C: "Bell", D: "Edison" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 44, soru: "Televizyonun mucidi kimdir?", secenekler: { A: "John Logie Baird", B: "Steve Jobs", C: "Bill Gates", D: "Graham Bell" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 45, soru: "Kuduz aşısını bulan bilim insanı kimdir?", secenekler: { A: "Louis Pasteur", B: "Robert Koch", C: "Fleming", D: "Darwin" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 46, soru: "Penisilini keşfeden bilim insanı kimdir?", secenekler: { A: "Alexander Fleming", B: "Pasteur", C: "Mendel", D: "Tesla" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 47, soru: "Matbaayı icat eden kişi kimdir?", secenekler: { A: "Gutenberg", B: "Newton", C: "Einstein", D: "Galileo" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 48, soru: "Buharlı makineyi geliştiren mucit kimdir?", secenekler: { A: "James Watt", B: "Edison", C: "Tesla", D: "Ford" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 49, soru: "İlk bilgisayarın adı nedir?", secenekler: { A: "ENIAC", B: "Apple 1", C: "Deep Blue", D: "Altair" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 50, soru: "Dünya Çapında Ağ (WWW) sistemini kuran kimdir?", secenekler: { A: "Tim Berners-Lee", B: "Mark Zuckerberg", C: "Bill Gates", D: "Elon Musk" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 51, soru: "Dinamiti icat eden ve adına ödüller düzenlenen kişi?", secenekler: { A: "Alfred Nobel", B: "Einstein", C: "Oppenheimer", D: "Curie" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 52, soru: "Yerçekimi kanununu bulan bilim insanı kimdir?", secenekler: { A: "Newton", B: "Galileo", C: "Kepler", D: "Arşimet" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 53, soru: "Teleskopla gökyüzünü inceleyen ilk bilim insanı?", secenekler: { A: "Galileo", B: "Newton", C: "Copernicus", D: "Bruno" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 54, soru: "Alternatif akımı (AC) bulan mucit kimdir?", secenekler: { A: "Nikola Tesla", B: "Edison", C: "Ohm", D: "Volt" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 55, soru: "Dünya'nın yuvarlak olduğunu ispatlayan denizci?", secenekler: { A: "Magellan", B: "Kolomb", C: "Vasco da Gama", D: "Amerigo Vespucci" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 56, soru: "X ışınlarını keşfeden bilim insanı kimdir?", secenekler: { A: "Röntgen", B: "Curie", C: "Becquerel", D: "Bohr" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 57, soru: "Radyoaktivite üzerine çalışmalarıyla 2 Nobel alan kadın?", secenekler: { A: "Marie Curie", B: "Rosalind Franklin", C: "Lise Meitner", D: "Ada Lovelace" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 58, soru: "İlk otomobili icat eden kişi kimdir?", secenekler: { A: "Karl Benz", B: "Henry Ford", C: "Tesla", D: "Diesel" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 59, soru: "Stetoskopu icat eden doktor kimdir?", secenekler: { A: "Rene Laennec", B: "Hipokrat", C: "Galen", D: "Lister" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 60, soru: "İlk uçağı uçuran kardeşler kimlerdir?", secenekler: { A: "Wright Kardeşler", B: "Montgolfier Kardeşler", C: "Lumiere Kardeşler", D: "Grimm Kardeşler" }, dogruCevap: "A" },

    // 61-80: Uzay, Fizik ve Doğa Bilimleri
    { kategori: "Bilim", seviye: 61, soru: "Güneş sistemindeki en büyük gezegen hangisidir?", secenekler: { A: "Jüpiter", B: "Satürn", C: "Neptün", D: "Dünya" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 62, soru: "Güneş'e en yakın gezegen hangisidir?", secenekler: { A: "Merkür", B: "Venüs", C: "Mars", D: "Dünya" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 63, soru: "Halkalarıyla ünlü gezegen hangisidir?", secenekler: { A: "Satürn", B: "Uranüs", C: "Jüpiter", D: "Mars" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 64, soru: "Işık hızının yaklaşık değeri saniyede kaç km'dir?", secenekler: { A: "300.000", B: "150.000", C: "500.000", D: "1.000.000" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 65, soru: "Sıvıların kaldırma kuvvetini bulan bilgin kimdir?", secenekler: { A: "Arşimet", B: "Pisagor", C: "Öklid", D: "Tales" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 66, soru: "Su kaç derecede kaynar?", secenekler: { A: "100", B: "90", C: "110", D: "80" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 67, soru: "Maddenin kaç hali vardır (temelde)?", secenekler: { A: "3", B: "4", C: "2", D: "5" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 68, soru: "Dünyanın en dış katmanı hangisidir?", secenekler: { A: "Yer Kabuğu", B: "Manto", C: "Çekirdek", D: "Magma" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 69, soru: "Bitkilerin güneş ışığıyla besin üretmesine ne denir?", secenekler: { A: "Fotosentez", B: "Solunum", C: "Terleme", D: "Mayalanma" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 70, soru: "İnsan vücudundaki en sert madde hangisidir?", secenekler: { A: "Diş Minesi", B: "Kemik", C: "Kıkırdak", D: "Tırnak" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 71, soru: "DNA'nın yapısı hangi şekildedir?", secenekler: { A: "Çift Sarmal", B: "Düz", C: "Daire", D: "Küp" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 72, soru: "Kalıtım biliminin (Genetik) babası kimdir?", secenekler: { A: "Gregor Mendel", B: "Darwin", C: "Lamarck", D: "Linnaeus" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 73, soru: "Kırmızı kan hücrelerine ne ad verilir?", secenekler: { A: "Alyuvar", B: "Akyuvar", C: "Trombosit", D: "Plazma" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 74, soru: "Vücudun savunma sisteminde görevli kan hücreleri?", secenekler: { A: "Akyuvar", B: "Alyuvar", C: "Hemoglobin", D: "Serum" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 75, soru: "Hangi organımız kanı vücuda pompalar?", secenekler: { A: "Kalp", B: "Akciğer", C: "Böbrek", D: "Karaciğer" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 76, soru: "Vücudumuzun en büyük organı hangisidir?", secenekler: { A: "Deri", B: "Karaciğer", C: "Bağırsak", D: "Akciğer" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 77, soru: "Hangi vitamin güneş ışığıyla sentezlenir?", secenekler: { A: "D Vitamini", B: "C Vitamini", C: "A Vitamini", D: "B12" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 78, soru: "Dünyanın en büyük okyanusu hangisidir?", secenekler: { A: "Büyük Okyanus (Pasifik)", B: "Atlas Okyanusu", C: "Hint Okyanusu", D: "Arktik Okyanusu" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 79, soru: "Atmosferdeki ozon tabakası bizi neyden korur?", secenekler: { A: "Ultraviyole Işınlar", B: "Meteorlar", C: "Soğuktan", D: "Yağmurdan" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 80, soru: "Yer sarsıntılarını ölçen alete ne denir?", secenekler: { A: "Sismograf", B: "Barometre", C: "Termometre", D: "Hangiometre" }, dogruCevap: "A" },

    // 81-100: Karışık Bilim ve Genel Kültür
    { kategori: "Bilim", seviye: 81, soru: "Isıyı ölçen alet hangisidir?", secenekler: { A: "Kalorimetre", B: "Termometre", C: "Dinamometre", D: "Barometre" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 82, soru: "Hava basıncını ölçen alet hangisidir?", secenekler: { A: "Barometre", B: "Higrometre", C: "Altimetre", D: "Sismometre" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 83, soru: "Suyun donma noktası kaç derecedir (Celsius)?", secenekler: { A: "0", B: "-1", C: "1", D: "4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 84, soru: "Elmas hangi elementin kristal halidir?", secenekler: { A: "Karbon", B: "Silisyum", C: "Kükürt", D: "Azot" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 85, soru: "Periyodik tablonun babası kimdir?", secenekler: { A: "Mendeleyev", B: "Dalton", C: "Bohr", D: "Rutherford" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 86, soru: "En sert doğal madde hangisidir?", secenekler: { A: "Elmas", B: "Çelik", C: "Titanyum", D: "Kuvars" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 87, soru: "Ses hızı havada yaklaşık kaç m/s'dir?", secenekler: { A: "340", B: "1000", C: "100", D: "200.000" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 88, soru: "Işığın kırılmasını açıklayan İslam bilgini?", secenekler: { A: "İbn-i Heysem", B: "Ömer Hayyam", C: "Kindi", D: "Biruni" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 89, soru: "Gökkuşağının 7 renginden ortadaki hangisidir?", secenekler: { A: "Yeşil", B: "Sarı", C: "Mavi", D: "Kırmızı" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 90, soru: "Bir mıknatısın kaç kutbu vardır?", secenekler: { A: "2", B: "1", C: "3", D: "4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 91, soru: "Atomun çekirdeğindeki artı yüklü tanecik?", secenekler: { A: "Proton", B: "Nötron", C: "Elektron", D: "Pozitron" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 92, soru: "Atomun çekirdeğindeki yüksüz tanecik?", secenekler: { A: "Nötron", B: "Proton", C: "Elektron", D: "Kuark" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 93, soru: "Elektrik akım şiddeti birimi nedir?", secenekler: { A: "Amper", B: "Volt", C: "Watt", D: "Ohm" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 94, soru: "Direnç birimi nedir?", secenekler: { A: "Ohm", B: "Volt", C: "Joule", D: "Newton" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 95, soru: "Güç birimi nedir?", secenekler: { A: "Watt", B: "Pascal", C: "Newton", D: "Amper" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 96, soru: "Sıvı haldeki tek metal hangisidir?", secenekler: { A: "Cıva", B: "Kurşun", C: "Brom", D: "Altın" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 97, soru: "Kandaki şeker oranını düzenleyen hormon?", secenekler: { A: "İnsülin", B: "Adrenalin", C: "Tiroksin", D: "Kortizol" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 98, soru: "Hangi hayvan ses dalgalarıyla yolunu bulur?", secenekler: { A: "Yarasa", B: "Baykuş", C: "Kartal", D: "Yılan" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 99, soru: "Hangi gezegen yan yatmış bir varil gibi döner?", secenekler: { A: "Uranüs", B: "Neptün", C: "Venüs", D: "Mars" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 100, soru: "Yapay zekanın babası kabul edilen bilim insanı?", secenekler: { A: "Alan Turing", B: "Bill Gates", C: "Elon Musk", D: "Steve Jobs" }, dogruCevap: "A" },
    // Bilim Soruları Devamı (101 - 200)
    { kategori: "Bilim", seviye: 101, soru: "Güneş sistemindeki en büyük gezegen hangisidir?", secenekler: { A: "Satürn", B: "Jüpiter", C: "Neptün", D: "Dünya" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 102, soru: "İnsan vücudundaki en sert madde hangisidir?", secenekler: { A: "Kemik", B: "Diş minesi", C: "Kıkırdak", D: "Tırnak" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 103, soru: "Işığın boşluktaki hızı saniyede yaklaşık kaç kilometredir?", secenekler: { A: "150.000", B: "300.000", C: "500.000", D: "1.000.000" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 104, soru: "Periyodik tabloda 'Au' sembolü hangi elementi temsil eder?", secenekler: { A: "Gümüş", B: "Bakır", C: "Altın", D: "Alüminyum" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 105, soru: "Modern genetiğin babası olarak kabul edilen bilim insanı kimdir?", secenekler: { A: "Charles Darwin", B: "Gregor Mendel", C: "Louis Pasteur", D: "Nikola Tesla" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 106, soru: "Hangi gezegen 'Çoban Yıldızı' olarak da bilinir?", secenekler: { A: "Mars", B: "Venüs", C: "Merkür", D: "Uranüs" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 107, soru: "Suyun kimyasal formülü nedir?", secenekler: { A: "CO2", B: "H2O", B: "NaCl", D: "CH4" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 108, soru: "Bitkilerin güneş ışığını kullanarak besin üretmesine ne ad verilir?", secenekler: { A: "Fermantasyon", B: "Solunum", C: "Fotosentez", D: "Terleme" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 109, soru: "Dünya'nın atmosferinde en bol bulunan gaz hangisidir?", secenekler: { A: "Oksijen", B: "Azot", C: "Karbondioksit", D: "Hidrojen" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 110, soru: "Yerçekimi kanununu sistemleştiren bilim insanı kimdir?", secenekler: { A: "Galileo", B: "Isaac Newton", C: "Albert Einstein", D: "Stephen Hawking" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 111, soru: "Bir atomun çekirdeğinde protonlarla birlikte bulunan tanecik hangisidir?", secenekler: { A: "Elektron", B: "Nötron", C: "Pozitron", D: "Foton" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 112, soru: "Kızıl Gezegen olarak bilinen gök cismi hangisidir?", secenekler: { A: "Venüs", B: "Mars", C: "Merkür", D: "Plüton" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 113, soru: "Hücrenin enerji santrali olarak bilinen organel hangisidir?", secenekler: { A: "Ribozom", B: "Mitokondri", C: "Lizozom", D: "Golgi" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 114, soru: "Gökkuşağının merkezinde hangi renk bulunur?", secenekler: { A: "Kırmızı", B: "Sarı", C: "Yeşil", D: "Mavi" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 115, soru: "Kuduz aşısını bulan bilim insanı kimdir?", secenekler: { A: "Alexander Fleming", B: "Louis Pasteur", C: "Robert Koch", D: "Marie Curie" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 116, soru: "Güneş'e en yakın gezegen hangisidir?", secenekler: { A: "Dünya", B: "Merkür", C: "Venüs", D: "Mars" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 117, soru: "Mıknatısın hangi kutupları birbirini çeker?", secenekler: { A: "Aynı kutuplar", B: "Zıt kutuplar", C: "Kuzey-Kuzey", D: "Güney-Güney" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 118, soru: "Hangi vitamin güneş ışığı yardımıyla vücutta sentezlenir?", secenekler: { A: "A Vitamini", B: "B Vitamini", C: "C Vitamini", D: "D Vitamini" }, dogruCevap: "D" },
    { kategori: "Bilim", seviye: 119, soru: "Sesin hızı aşağıdakilerin hangisinde en yüksektir?", secenekler: { A: "Hava", B: "Su", C: "Demir", D: "Boşluk" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 120, soru: "Yetişkin bir insanda normalde kaç adet diş bulunur?", secenekler: { A: "28", B: "30", C: "32", D: "36" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 121, soru: "Radyumu keşfeden ve iki kez Nobel ödülü alan bilim kadını?", secenekler: { A: "Rosalind Franklin", B: "Marie Curie", C: "Ada Lovelace", D: "Lise Meitner" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 122, soru: "Dünya'nın en dış katmanına ne ad verilir?", secenekler: { A: "Manto", B: "Çekirdek", C: "Yer kabuğu", D: "Litosfer" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 123, soru: "Depremin büyüklüğünü ölçen aletin adı nedir?", secenekler: { A: "Barometre", B: "Sismograf", C: "Termometre", D: "Higrometre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 124, soru: "Atmosfer basıncını ölçen alet hangisidir?", secenekler: { A: "Manometre", B: "Barometre", C: "Altimetre", D: "Kronometre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 125, soru: "İnsan vücudundaki en büyük organ hangisidir?", secenekler: { A: "Karaciğer", B: "Deri", C: "Akciğer", D: "Beyin" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 126, soru: "Kalıtsal bilgileri taşıyan ve hücre çekirdeğinde bulunan molekül?", secenekler: { A: "RNA", B: "DNA", C: "ATP", D: "Protein" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 127, soru: "Penisilini keşfeden bilim insanı kimdir?", secenekler: { A: "Edward Jenner", B: "Alexander Fleming", C: "Jonas Salk", D: "Louis Pasteur" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 128, soru: "Evrendeki en hafif ve en bol bulunan element hangisidir?", secenekler: { A: "Helyum", B: "Oksijen", C: "Hidrojen", D: "Azot" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 129, soru: "Bir devredeki elektrik akımını ölçen alet?", secenekler: { A: "Voltmetre", B: "Ampermetre", C: "Ommetre", D: "Wattmetre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 130, soru: "Sıcaklık birimi olan 'Kelvin' hangi fiziksel niceliği ölçer?", secenekler: { A: "Isı", B: "Sıcaklık", C: "Basınç", D: "Enerji" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 131, soru: "Işık yılı ne birimidir?", secenekler: { A: "Zaman", B: "Hız", C: "Mesafe", D: "Işık şiddeti" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 132, soru: "Sıvıların kaldırma kuvvetini bulan antik çağ bilgini?", secenekler: { A: "Aristo", B: "Arşimet", C: "Pisagor", D: "Öklid" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 133, soru: "Depremlerin şiddetini derecelendiren ölçeğin adı nedir?", secenekler: { A: "Celsius", B: "Richter", C: "Kelvin", D: "Beaufort" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 134, soru: "Hangi element oda sıcaklığında sıvı halde bulunan tek metaldir?", secenekler: { A: "Bakır", B: "Gümüş", C: "Cıva", D: "Kurşun" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 135, soru: "Zamanın Göreliliği kuramını ortaya atan fizikçi?", secenekler: { A: "Newton", B: "Einstein", C: "Bohr", D: "Planck" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 136, soru: "Kandaki oksijeni taşıyan hücrelere ne ad verilir?", secenekler: { A: "Akyuvar", B: "Alyuvar", C: "Trombosit", D: "Plazma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 137, soru: "İnsan vücudundaki en uzun kemik hangisidir?", secenekler: { A: "Kaval kemiği", B: "Uyluk kemiği", C: "Omurga", D: "Pazı kemiği" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 138, soru: "Maddenin dördüncü hali olarak kabul edilen hal hangisidir?", secenekler: { A: "Gaz", B: "Plazma", C: "Kristal", D: "Buhar" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 139, soru: "Teleskopu astronomi amaçlı ilk kullanan bilim insanı?", secenekler: { A: "Kepler", B: "Copernicus", C: "Galileo", D: "Newton" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 140, soru: "Asitlerin pH değeri hangi aralıktadır?", secenekler: { A: "0-7", B: "7-14", C: "5-10", D: "1-14" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 141, soru: "Saf suyun pH değeri kaçtır?", secenekler: { A: "0", B: "5", C: "7", D: "14" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 142, soru: "Evrim teorisini 'Türlerin Kökeni' adlı eseriyle açıklayan kişi?", secenekler: { A: "Lamarck", B: "Darwin", C: "Wallace", D: "Huxley" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 143, soru: "Güneş'te gerçekleşen ve enerji açığa çıkaran tepkime türü?", secenekler: { A: "Fisyon", B: "Füzyon", C: "Yanma", D: "Buharlaşma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 144, soru: "Hangi gezegenin halkaları en belirgindir?", secenekler: { A: "Jüpiter", B: "Satürn", C: "Uranüs", D: "Neptün" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 145, soru: "Bakır ve çinkonun karışımından oluşan alaşım?", secenekler: { A: "Tunç", B: "Pirinç", C: "Çelik", D: "Lehim" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 146, soru: "Hücre çekirdeğini keşfeden bilim insanı?", secenekler: { A: "Robert Hooke", B: "Robert Brown", C: "Antonie van Leeuwenhoek", D: "Theodor Schwann" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 147, soru: "Dünyanın kendi ekseni etrafındaki dönüşü neyi oluşturur?", secenekler: { A: "Mevsimler", B: "Gece ve Gündüz", C: "Yıllar", D: "Gelgit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 148, soru: "Sıvı bir maddenin ısı alarak gaz haline geçmesine ne denir?", secenekler: { A: "Donma", B: "Yoğuşma", C: "Buharlaşma", D: "Süblimleşme" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 149, soru: "Yerin merkezindeki çok sıcak ve yoğun bölüme ne ad verilir?", secenekler: { A: "Litosfer", B: "Manto", C: "Çekirdek", D: "Astenosfer" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 150, soru: "İnsan vücudunda kanın süzüldüğü organ hangisidir?", secenekler: { A: "Mide", B: "Böbrek", C: "Dalak", D: "Bağırsak" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 151, soru: "Ampulü icat eden bilim insanı kimdir?", secenekler: { A: "Tesla", B: "Edison", C: "Bell", D: "Watt" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 152, soru: "İnsan vücudunda toplam kaç tane ana kan grubu vardır (AB0 sistemine göre)?", secenekler: { A: "2", B: "3", C: "4", D: "8" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 153, soru: "Proteinlerin yapı taşı nedir?", secenekler: { A: "Glikoz", B: "Amino asit", C: "Yağ asidi", D: "Nükleotit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 154, soru: "Hangisi bir element değildir?", secenekler: { A: "Helyum", B: "Su", C: "Demir", D: "Altın" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 155, soru: "Havadaki nem oranını ölçen alet?", secenekler: { A: "Barometre", B: "Higrometre", C: "Termometre", D: "Anemometre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 156, soru: "Sıcaklığın etkisiyle maddelerin boyca veya hacimce büyümesine ne denir?", secenekler: { A: "Büzülme", B: "Genleşme", C: "Erime", D: "Buharlaşma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 157, soru: "Bir canlının çevreye uyum sağlamasına ne denir?", secenekler: { A: "Mutasyon", B: "Adaptasyon", C: "Modifikasyon", D: "Varyasyon" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 158, soru: "Tuzun kimyasal adı nedir?", secenekler: { A: "Sodyum Karbonat", B: "Sodyum Klorür", C: "Potasyum Nitrat", D: "Kalsiyum Oksit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 159, soru: "Hangi gök cismi 'Dünya'nın uydusu'dur?", secenekler: { A: "Güneş", B: "Ay", C: "Mars", D: "Venüs" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 160, soru: "Gözle görülemeyecek kadar küçük canlıları görmemizi sağlayan alet?", secenekler: { A: "Teleskop", B: "Mikroskop", C: "Periskop", D: "Stetoskop" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 161, soru: "Sütü pastörize etme yöntemini kim geliştirmiştir?", secenekler: { A: "Mendel", B: "Pasteur", C: "Darwin", D: "Curie" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 162, soru: "Bitkilerde suyun taşınmasını sağlayan doku?", secenekler: { A: "Ksilem (Odun borusu)", B: "Floem (Soymuk borusu)", C: "Epidermis", D: "Kambiyum" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 163, soru: "Depremlerin odağını ve büyüklüğünü inceleyen bilim dalı?", secenekler: { A: "Jeoloji", B: "Sismoloji", C: "Meteoroloji", D: "Arkeoloji" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 164, soru: "Canlıların sınıflandırılmasını inceleyen biyoloji alt dalı?", secenekler: { A: "Ekoloji", B: "Taksonomi", C: "Genetik", D: "Anatomi" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 165, soru: "Kuvvetin birimi nedir?", secenekler: { A: "Joule", B: "Newton", C: "Pascal", D: "Watt" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 166, soru: "Hangi kan grubu 'genel alıcı' olarak bilinir?", secenekler: { A: "0 Rh-", B: "AB Rh+", C: "A Rh+", D: "B Rh-" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 167, soru: "Gözün renkli kısmına ne ad verilir?", secenekler: { A: "Pupilla", B: "İris", C: "Retina", D: "Kornea" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 168, soru: "Kimyanın babası olarak kabul edilen ve 'Kütlenin Korunumu Kanunu'nu bulan kişi?", secenekler: { A: "Dalton", B: "Lavoisier", C: "Boyle", D: "Avogadro" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 169, soru: "Sesin yüksekliğini (incelik-kalınlık) belirleyen özellik?", secenekler: { A: "Genlik", B: "Frekans", C: "Hız", D: "Tını" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 170, soru: "Yeryüzündeki en sert doğal madde?", secenekler: { A: "Çelik", B: "Elmas", C: "Kuvars", D: "Mermer" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 171, soru: "Karıncaların salgıladığı asit türü hangisidir?", secenekler: { A: "Sülfürik asit", B: "Formik asit", C: "Sitrik asit", D: "Laktik asit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 172, soru: "Güneş sistemindeki en küçük gezegen?", secenekler: { A: "Mars", B: "Merkür", C: "Plüton", D: "Neptün" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 173, soru: "DNA'nın çift sarmal yapısını keşfeden bilim insanlarından biri?", secenekler: { A: "James Watson", B: "Albert Einstein", C: "Stephen Hawking", D: "Richard Feynman" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 174, soru: "Kalbin sol karıncığından çıkan ve vücuda temiz kan taşıyan büyük damar?", secenekler: { A: "Vena Cava", B: "Aort", C: "Pulmoner Arter", D: "Şah damarı" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 175, soru: "Kömürün çok yüksek basınç altında kalarak dönüştüğü madde?", secenekler: { A: "Linyit", B: "Elmas", C: "Grafit", D: "Antrasit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 176, soru: "İnsan vücudunda insülin üreten organ hangisidir?", secenekler: { A: "Karaciğer", B: "Pankreas", C: "Böbrek", D: "Safra kesesi" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 177, soru: "Atom bombasını geliştiren 'Manhattan Projesi'nin bilimsel lideri?", secenekler: { A: "Einstein", B: "Oppenheimer", C: "Fermi", D: "Bohr" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 178, soru: "Işığın kırılmasını açıklayan kanun?", secenekler: { A: "Ohm Kanunu", B: "Snell Kanunu", C: "Boyle Kanunu", D: "Hooke Kanunu" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 179, soru: "Atmosferin en alt katmanı?", secenekler: { A: "Stratosfer", B: "Troposfer", C: "Mezosfer", D: "Ekzosfer" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 180, soru: "Hangi element 'K' sembolü ile gösterilir?", secenekler: { A: "Kalsiyum", B: "Potasyum", C: "Klor", D: "Karbon" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 181, soru: "Isının bir uçtan diğerine atomların titreşimiyle iletilmesine ne denir?", secenekler: { A: "Işıma", B: "İletim (Kondüksiyon)", C: "Konveksiyon", D: "Yansıma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 182, soru: "Dünya'nın kendi ekseni etrafındaki dönüş hızı ekvatorda yaklaşık kaç km/saattir?", secenekler: { A: "500", B: "1670", C: "3000", D: "10000" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 183, soru: "Kemiklerin gelişiminde etkili olan mineral hangisidir?", secenekler: { A: "Demir", B: "Kalsiyum", C: "Sodyum", D: "Çinko" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 184, soru: "Limon suyunda bulunan asit türü?", secenekler: { A: "Malik asit", B: "Sitrik asit", C: "Folik asit", D: "Asetik asit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 185, soru: "Modern periyodik sistemin kurucusu sayılan Rus kimyager?", secenekler: { A: "Mendeleyev", B: "Lomonosov", C: "Nobel", D: "Pascal" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 186, soru: "Teleskopla bakıldığında kırmızı renkte görülen, dev bir fırtınaya (Büyük Kırmızı Leke) sahip gezegen?", secenekler: { A: "Mars", B: "Jüpiter", C: "Satürn", D: "Neptün" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 187, soru: "Hücrede protein sentezinden sorumlu organel?", secenekler: { A: "Lizozom", B: "Ribozom", C: "Koful", D: "Çekirdek" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 188, soru: "Suyun donma noktası Fahrenheit ölçeğinde kaçtır?", secenekler: { A: "0", B: "32", C: "100", D: "212" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 189, soru: "İlk bilgisayar programcısı olarak kabul edilen kadın bilim insanı?", secenekler: { A: "Marie Curie", B: "Ada Lovelace", C: "Grace Hopper", D: "Hedy Lamarr" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 190, soru: "Kutuplarda görülen renkli ışımalara ne ad verilir?", secenekler: { A: "Serap", B: "Aurora (Kutup Işıkları)", C: "Gökkuşağı", D: "Yıldız Kayması" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 191, soru: "Bitkilerin yeşil rengini veren madde hangisidir?", secenekler: { A: "Hemoglobin", B: "Klorofil", C: "Melanin", D: "Karoten" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 192, soru: "Basınç birimi nedir?", secenekler: { A: "Joule", B: "Pascal", C: "Ohm", D: "Amper" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 193, soru: "Hücre bölünmesi sırasında kromozomların belirginleştiği evre hangisidir?", secenekler: { A: "İnterfaz", B: "Metafaz", C: "Profaz", D: "Telofaz" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 194, soru: "Dinamiti icat eden ve vasiyetiyle ödüller başlatan kişi?", secenekler: { A: "Alfred Nobel", B: "Thomas Edison", C: "Graham Bell", D: "Guglielmo Marconi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 195, soru: "İnsan vücudunda dengeyi sağlayan organ hangisidir?", secenekler: { A: "Göz", B: "Kulak (İç kulak)", C: "Beyin", D: "Omurilik" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 196, soru: "Demirin paslanması ne tür bir olaydır?", secenekler: { A: "Fiziksel", B: "Kimyasal", C: "Nükleer", D: "Biyolojik" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 197, soru: "Bir canlının genetik yapısının tamamına ne denir?", secenekler: { A: "Fenotip", B: "Genotip", C: "Genom", D: "Kromozom" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 198, soru: "Dünya'nın güneş etrafındaki bir tam turuna ne denir?", secenekler: { A: "Gün", B: "Hafta", C: "Yıl", D: "Ay" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 199, soru: "Elektrik devresinde akımı kesen veya açan eleman?", secenekler: { A: "Direnç", B: "Anahtar", C: "Üreteç", D: "Sigorta" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 200, soru: "Helyumun periyodik tablodaki numarası (atom numarası) kaçtır?", secenekler: { A: "1", B: "2", C: "4", D: "10" }, dogruCevap: "B" }, 
    // Bilim Soruları Devamı (201 - 300)
    { kategori: "Bilim", seviye: 201, soru: "Bir canlının dış görünüşüne ne ad verilir?", secenekler: { A: "Genotip", B: "Fenotip", C: "Mutasyon", D: "Adaptasyon" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 202, soru: "Elektriği iletmeyen maddelere ne ad verilir?", secenekler: { A: "İletken", B: "Yalıtkan", C: "Yarı iletken", D: "Süper iletken" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 203, soru: "Havadaki nemi ölçen alet hangisidir?", secenekler: { A: "Barometre", B: "Higrometre", C: "Termometre", D: "Altimetre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 204, soru: "Güneş'e en uzak gezegen hangisidir?", secenekler: { A: "Uranüs", B: "Neptün", C: "Plüton", D: "Satürn" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 205, soru: "Gözün ağ tabakasına ne ad verilir?", secenekler: { A: "Retina", B: "İris", C: "Pupilla", D: "Kornea" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 206, soru: "Suyun kaldırma kuvvetini kim bulmuştur?", secenekler: { A: "Arşimet", B: "Newton", C: "Einstein", D: "Pascal" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 207, soru: "Hangi kan grubu 'genel verici' olarak bilinir?", secenekler: { A: "AB", B: "A", C: "B", D: "0" }, dogruCevap: "D" },
    { kategori: "Bilim", seviye: 208, soru: "Işık hangi hızda yayılır?", secenekler: { A: "340 m/s", B: "300.000 km/s", C: "150.000 km/s", D: "1.000 km/s" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 209, soru: "Dünya'nın uydusu olan Ay, Dünya etrafındaki dönüşünü kaç günde tamamlar?", secenekler: { A: "24", B: "27.3", C: "30", D: "365" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 210, soru: "İnsan vücudundaki en küçük kemik nerededir?", secenekler: { A: "El", B: "Ayak", C: "Kulak", D: "Burun" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 211, soru: "Hücre çekirdeğindeki genetik materyale ne ad verilir?", secenekler: { A: "DNA", B: "RNA", C: "ATP", D: "ADP" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 212, soru: "Gökkuşağında kaç renk vardır?", secenekler: { A: "5", B: "6", C: "7", D: "8" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 213, soru: "Ses hangi ortamlarda yayılamaz?", secenekler: { A: "Sıvı", B: "Katı", C: "Gaz", D: "Boşluk" }, dogruCevap: "D" },
    { kategori: "Bilim", seviye: 214, soru: "Yerçekimi ivmesi yaklaşık kaçtır?", secenekler: { A: "5.8", B: "9.8", C: "12.5", D: "15.0" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 215, soru: "Demirin simgesi nedir?", secenekler: { A: "D", B: "De", C: "Fe", D: "Ir" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 216, soru: "Hidrojenin atom numarası kaçtır?", secenekler: { A: "1", B: "2", C: "3", D: "4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 217, soru: "Sıcaklığı ölçen alet hangisidir?", secenekler: { A: "Barometre", B: "Kronometre", C: "Termometre", D: "Dinamometre" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 218, soru: "Hangi gezegenin halkası en büyüktür?", secenekler: { A: "Jüpiter", B: "Satürn", C: "Uranüs", D: "Neptün" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 219, soru: "Yeryüzünde en bol bulunan element hangisidir?", secenekler: { A: "Altın", B: "Oksijen", C: "Demir", D: "Hidrojen" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 220, soru: "Asitlerin tadı nasıldır?", secenekler: { A: "Acı", B: "Ekşi", C: "Tuzlu", D: "Tatlı" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 221, soru: "Bazların tadı nasıldır?", secenekler: { A: "Acı", B: "Ekşi", C: "Tatlı", D: "Sert" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 222, soru: "Hangi organımız kan pompalar?", secenekler: { A: "Akciğer", B: "Böbrek", C: "Kalp", D: "Mide" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 223, soru: "Bitkilerde fotosentez nerede gerçekleşir?", secenekler: { A: "Kök", B: "Gövde", C: "Yaprak", D: "Çiçek" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 224, soru: "Atom bombasını kim bulmuştur?", secenekler: { A: "Einstein", B: "Oppenheimer", C: "Tesla", D: "Newton" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 225, soru: "Periyodik tabloyu kim oluşturmuştur?", secenekler: { A: "Mendeleyev", B: "Dalton", C: "Bohr", D: "Lavoisier" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 226, soru: "Dinamiti kim bulmuştur?", secenekler: { A: "Alfred Nobel", B: "Thomas Edison", C: "Graham Bell", D: "Nikola Tesla" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 227, soru: "Kuvvet ne ile ölçülür?", secenekler: { A: "Terazi", B: "Dinamometre", C: "Metre", D: "Litre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 228, soru: "Kütle ne ile ölçülür?", secenekler: { A: "Dinamometre", B: "Eşit kollu terazi", C: "Mezura", D: "Barometre" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 229, soru: "Hangisi yenilenebilir enerji kaynağıdır?", secenekler: { A: "Kömür", B: "Petrol", C: "Güneş", D: "Doğalgaz" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 230, soru: "DNA'nın yapısı nasıldır?", secenekler: { A: "Tek sarmal", B: "Çift sarmal", C: "Üçgen", D: "Düz" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 231, soru: "Fosiller hangi kayaç türünde bulunur?", secenekler: { A: "Püskürük", B: "Metamorfik", C: "Tortul", D: "Magmatik" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 232, soru: "Deprem dalgalarına ne ad verilir?", secenekler: { A: "Sismik", B: "Tsunami", C: "Magma", D: "Fay" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 233, soru: "Dünya'nın katmanlarından hangisi en kalındır?", secenekler: { A: "Kabuk", B: "Manto", C: "Dış Çekirdek", D: "İç Çekirdek" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 234, soru: "İnsan genomunda kaç çift kromozom vardır?", secenekler: { A: "20", B: "23", C: "46", D: "48" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 235, soru: "Güneş sistemindeki en sıcak gezegen hangisidir?", secenekler: { A: "Merkür", B: "Venüs", C: "Mars", D: "Jüpiter" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 236, soru: "Oksijeni keşfeden bilim insanı?", secenekler: { A: "Joseph Priestley", B: "Antoine Lavoisier", C: "John Dalton", D: "Robert Boyle" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 237, soru: "Kalıtım bilimini kim kurmuştur?", secenekler: { A: "Darwin", B: "Mendel", C: "Pasteur", D: "Lamarck" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 238, soru: "Havadaki oksijen oranı yüzde kaçtır?", secenekler: { A: "21", B: "78", C: "1", D: "10" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 239, soru: "Gözlük camları ne yardımıyla ışığı kırar?", secenekler: { A: "Ayna", B: "Mercek", C: "Prizma", D: "Cam" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 240, soru: "En hafif metal hangisidir?", secenekler: { A: "Alüminyum", B: "Lityum", C: "Magnezyum", D: "Sodyum" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 241, soru: "Tuz ruhunun kimyasal adı nedir?", secenekler: { A: "Sülfürik Asit", B: "Hidroklorik Asit", C: "Nitrik Asit", D: "Asetik Asit" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 242, soru: "Hücre çekirdeği olmayan hücrelere ne ad verilir?", secenekler: { A: "Ökaryot", B: "Prokaryot", C: "Bitki", D: "Hayvan" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 243, soru: "Işığı geçiren maddelere ne denir?", secenekler: { A: "Saydam", B: "Yarı saydam", C: "Opak", D: "Mat" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 244, soru: "Hangisi bir asal gazdır?", secenekler: { A: "Oksijen", B: "Hidrojen", C: "Helyum", D: "Azot" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 245, soru: "Atmosferin en dış katmanı hangisidir?", secenekler: { A: "Troposfer", B: "Stratosfer", C: "Termosfer", D: "Ekzosfer" }, dogruCevap: "D" },
    { kategori: "Bilim", seviye: 246, soru: "Güneş enerjisi panelleri neyi elektriğe çevirir?", secenekler: { A: "Isı", B: "Işık", C: "Rüzgar", D: "Su" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 247, soru: "Uçakların uçmasını sağlayan fizik prensibi hangisidir?", secenekler: { A: "Pascal", B: "Bernoulli", C: "Newton", D: "Arşimet" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 248, soru: "Bir mıknatısın kaç kutbu vardır?", secenekler: { A: "1", B: "2", C: "3", D: "4" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 249, soru: "Suyun en yoğun olduğu sıcaklık derecesi?", secenekler: { A: "0", B: "4", C: "10", D: "100" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 250, soru: "Pusulanın renkli ucu nereyi gösterir?", secenekler: { A: "Güney", B: "Doğu", C: "Batı", D: "Kuzey" }, dogruCevap: "D" },
    { kategori: "Bilim", seviye: 251, soru: "En büyük memeli hayvan hangisidir?", secenekler: { A: "Fil", B: "Mavi Balina", C: "Zürafa", D: "Su Aygırı" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 252, soru: "Kuşlar hangi solunumu yapar?", secenekler: { A: "Deri", B: "Solungaç", C: "Akciğer", D: "Trake" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 253, soru: "Ham petrolden benzin elde etme yöntemine ne denir?", secenekler: { A: "Süzme", B: "Damıtma", C: "Eleme", D: "Buharlaştırma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 254, soru: "Bir devrede ampulün ışık vermesini sağlayan enerji kaynağı?", secenekler: { A: "Kablo", B: "Pil", C: "Anahtar", D: "Duy" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 255, soru: "Sesin şiddetini ölçen birim nedir?", secenekler: { A: "Hertz", B: "Desibel", C: "Watt", D: "Newton" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 256, soru: "Diz kapağı hangi kemik türüne girer?", secenekler: { A: "Uzun", B: "Yassı", C: "Kısa", D: "Düzensiz" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 257, soru: "Akciğerlerin altında bulunan solunum kası?", secenekler: { A: "Mide", B: "Diyafram", C: "Pankreas", D: "Karaciğer" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 258, soru: "Gümüşün simgesi nedir?", secenekler: { A: "Au", B: "Ag", C: "Cu", D: "Si" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 259, soru: "Karbonatın kimyasal formülünde hangi element yoktur?", secenekler: { A: "Karbon", B: "Oksijen", C: "Azot", D: "Sodyum" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 260, soru: "Kutup yıldızının diğer adı nedir?", secenekler: { A: "Sirius", B: "Polaris", C: "Vega", D: "Antares" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 261, soru: "Bakırın simgesi nedir?", secenekler: { A: "Ba", B: "Cu", C: "Bk", D: "Cr" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 262, soru: "Hangisi bir omurgasız hayvandır?", secenekler: { A: "Yılan", B: "Kurbağa", C: "Kelebek", D: "Balık" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 263, soru: "İnsan vücudunda kaç litre kan bulunur?", secenekler: { A: "2-3", B: "5-6", C: "8-9", D: "10-12" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 264, soru: "Tırnaklar ve saçlar hangi proteinden oluşur?", secenekler: { A: "Kollajen", B: "Keratin", C: "Albümin", D: "Globin" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 265, soru: "Maddenin en küçük yapı taşına ne denir?", secenekler: { A: "Hücre", B: "Molekül", C: "Atom", D: "Elektron" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 266, soru: "Işığın bir yüzeye çarpıp geri dönmesine ne denir?", secenekler: { A: "Kırılma", B: "Yansıma", C: "Soğurulma", D: "Dağılma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 267, soru: "Hangi ayna türü görüntüyü her zaman düz ve küçük gösterir?", secenekler: { A: "Düz ayna", B: "Çukur ayna", C: "Tümsek ayna", D: "Dev aynası" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 268, soru: "Sıvı halden katı hale geçmeye ne denir?", secenekler: { A: "Erime", B: "Donma", C: "Buharlaşma", D: "Yoğuşma" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 269, soru: "Buharlaşmanın en hızlı olduğu sıcaklığa ne denir?", secenekler: { A: "Erime noktası", B: "Kaynama noktası", C: "Donma noktası", D: "Kritik nokta" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 270, soru: "Hangi vitamin eksikliğinde gece körlüğü görülür?", secenekler: { A: "A", B: "B", C: "C", D: "D" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 271, soru: "Bitkilerin kökleriyle su almasını sağlayan fiziksel olay?", secenekler: { A: "Difüzyon", B: "Osmos", C: "Aktif taşıma", D: "Terleme" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 272, soru: "Sodyumun simgesi nedir?", secenekler: { A: "S", B: "So", C: "Na", D: "Sn" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 273, soru: "Kurşunun simgesi nedir?", secenekler: { A: "Kr", B: "Pb", C: "Ku", D: "Pl" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 274, soru: "Hangi gezegen yan yatmış bir varil gibi döner?", secenekler: { A: "Satürn", B: "Uranüs", C: "Neptün", D: "Jüpiter" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 275, soru: "İlk teleskobu kim icat etmiştir?", secenekler: { A: "Galileo", B: "Hans Lippershey", C: "Newton", D: "Kepler" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 276, soru: "Kanın pıhtılaşmasını sağlayan hücreler?", secenekler: { A: "Alyuvar", B: "Akyuvar", C: "Trombosit", D: "Plazma" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 277, soru: "Güneş'in en dış katmanına ne ad verilir?", secenekler: { A: "Çekirdek", B: "Işık küre", C: "Taç küre (Korona)", D: "Renk küre" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 278, soru: "Fizikte 'İş' birimi nedir?", secenekler: { A: "Newton", B: "Watt", C: "Joule", D: "Pascal" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 279, soru: "Elektrik yükünün birimi nedir?", secenekler: { A: "Volt", B: "Amper", C: "Coulomb", D: "Ohm" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 280, soru: "Yer kabuğunda en çok bulunan metal?", secenekler: { A: "Demir", B: "Bakır", C: "Alüminyum", D: "Altın" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 281, soru: "Kalsiyumun simgesi nedir?", secenekler: { A: "K", B: "Ka", C: "Ca", D: "Cl" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 282, soru: "Yarasalar yönlerini ne ile bulur?", secenekler: { A: "Göz", B: "Koku", C: "Ses (Ultrasonik)", D: "Isı" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 283, soru: "Mantar hangi canlı grubuna girer?", secenekler: { A: "Bitki", B: "Hayvan", C: "Ayrı bir grup (Fungi)", D: "Bakteri" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 284, soru: "DNA'da bulunan bazlardan hangisi RNA'da yoktur?", secenekler: { A: "Adenin", B: "Guanin", C: "Sitozin", D: "Timin" }, dogruCevap: "D" },
    { kategori: "Bilim", seviye: 285, soru: "Dünya'nın en yüksek dağı olan Everest'in yüksekliği yaklaşık kaç metredir?", secenekler: { A: "5848", B: "8848", C: "10848", D: "12848" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 286, soru: "Sesin frekans birimi nedir?", secenekler: { A: "Hertz", B: "Desibel", C: "Metre", D: "Saniye" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 287, soru: "Zeytinyağı-su karışımı hangi yöntemle ayrılır?", secenekler: { A: "Süzme", B: "Ayırma hunisi", C: "Mıknatıs", D: "Eleme" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 288, soru: "Hangisi bir fiziksel değişimdir?", secenekler: { A: "Kağıdın yanması", B: "Demirin paslanması", C: "Buzun erimesi", D: "Sütün ekşimesi" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 289, soru: "Hangi gezegenin 'Kızıl Gezegen' olarak bilinmesinin nedeni yüzeyindeki demir oksittir?", secenekler: { A: "Venüs", B: "Mars", C: "Merkür", D: "Jüpiter" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 290, soru: "Karbondioksit formülü nedir?", secenekler: { A: "CO", B: "CO2", C: "C2O", D: "O2" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 291, soru: "Saf alkolün kaynama noktası yaklaşık kaçtır?", secenekler: { A: "78", B: "100", C: "120", D: "50" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 292, soru: "İnsan kalbi dakikada ortalama kaç kez atar?", secenekler: { A: "40-50", B: "70-80", C: "110-120", D: "150-160" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 293, soru: "Işığın tüm renklerinin birleşimi hangi rengi oluşturur?", secenekler: { A: "Siyah", B: "Beyaz", C: "Gri", D: "Kahverengi" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 294, soru: "Bir canlının yaşamını sürdürdüğü doğal ortama ne denir?", secenekler: { A: "Ekosistem", B: "Habitat", C: "Biyom", D: "Popülasyon" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 295, soru: "Hangisi bir kuş değildir?", secenekler: { A: "Penguen", B: "Yarasa", C: "Devekuşu", D: "Kartal" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 296, soru: "Helyumun simgesi nedir?", secenekler: { A: "H", B: "Hy", C: "He", D: "Hu" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 297, soru: "En büyük memeli hayvan hangisidir?", secenekler: { A: "Fil", B: "Mavi Balina", C: "Zürafa", D: "Orka" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 298, soru: "Hangi element güneşin ana yakıtıdır?", secenekler: { A: "Helyum", B: "Hidrojen", C: "Karbon", D: "Oksijen" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 299, soru: "Vücudumuzdaki en uzun hücreler hangileridir?", secenekler: { A: "Kan", B: "Kas", C: "Sinir", D: "Kemik" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 300, soru: "Mutlak sıfır noktası kaç santigrat derecedir?", secenekler: { A: "0", B: "-100", C: "-273.15", D: "-300" }, dogruCevap: "C" }
 

);
 