window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-20: Türk-İslam Bilginleri ve Türk Bilim İnsanları
    { kategori: "Bilim", seviye: 1, soru: "Modern tıbbın babası ve 'Tıbbın Kanunu' kitabının yazarı kimdir?", secenekler: { A: "Farabi", B: "İbn-i Sina", C: "Akşemseddin", D: "Razi" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 2, soru: "Cebir biliminin kurucusu olan Türk-İslam bilgini kimdir?", secenekler: { A: "Harezmi", B: "Ömer Hayyam", C: "Ali Kuşçu", D: "Biruni" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 3, soru: "Sibernetiğin kurucusu ve ilk robotları yapan Artuklu mühendisi kimdir?", secenekler: { A: "Cezeri", B: "Mimar Sinan", C: "Uluğ Bey", D: "İbn-i Heysem" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 4, soru: "Fatih Sultan Mehmet'in İstanbul'a davet ettiği ünlü astronom kimdir?", secenekler: { A: "Piri Reis", B: "Katip Çelebi", C: "Ali Kuşçu", D: "Hezarfen" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 5, soru: "2015 Nobel Kimya Ödülü'nü kazanan Türk bilim insanı kimdir?", secenekler: { A: "Oktay Sinanoğlu", B: "Cahit Arf", C: "Aziz Sancar", D: "Canan Dağdeviren" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 6, soru: "Dünya haritasını en doğru şekilde çizen Osmanlı denizcisi kimdir?", secenekler: { A: "Barbaros Hayrettin", B: "Piri Reis", C: "Seydi Ali Reis", D: "Kılıç Ali Paşa" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 7, soru: "10 TL üzerindeki portresiyle tanınan ünlü matematikçimiz kimdir?", secenekler: { A: "Feza Gürsey", B: "Cahit Arf", C: "Hulusi Behçet", D: "Mazhar Osman" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 8, soru: "Mikrobu Pastuer'den önce tanımlayan 'Maddetü'l-Hayat' yazarı kimdir?", secenekler: { A: "Akşemseddin", B: "İbn-i Nefis", C: "Ebu'l Vefa", D: "Zehravi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 9, soru: "Kendi adıyla anılan bir deri hastalığını tanımlayan Türk doktor kimdir?", secenekler: { A: "Münif Paşa", B: "Hulusi Behçet", C: "Gazi Yaşargil", D: "Sadi Konuk" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 10, soru: "Modern cerrahinin babası sayılan, 'Cerrahiyyetü'l Haniyye' yazarı kimdir?", secenekler: { A: "Sabuncuoğlu Şerefeddin", B: "İbn-i Sina", C: "Razi", D: "Farabi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 11, soru: "Ay'ın haritasını ilk kez çıkaran ve NASA tarafından Ay'da bir bölgeye adı verilen bilgin?", secenekler: { A: "Ali Kuşçu", B: "Uluğ Bey", C: "Biruni", D: "Nasreddin Tusi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 12, soru: "Sosyolojinin kurucusu kabul edilen 'Mukaddime' eseri kime aittir?", secenekler: { A: "İbn-i Haldun", B: "Farabi", C: "Gazali", D: "İbn-i Rüşd" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 13, soru: "Trigonometriye 'tanjant' kavramını kazandıran bilgin kimdir?", secenekler: { A: "Ebu'l Vefa", B: "Ömer Hayyam", C: "Harezmi", D: "Biruni" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 14, soru: "Dünya'nın güneş etrafında döndüğünü Kopernik'ten önce söyleyen 'Tahkik' yazarı?", secenekler: { A: "Biruni", B: "İbn-i Sina", C: "Uluğ Bey", D: "Ali Kuşçu" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 15, soru: "Yüzyılın beyin cerrahı seçilen Türk bilim insanı kimdir?", secenekler: { A: "Gazi Yaşargil", B: "Mehmet Öz", C: "Canan Dağdeviren", D: "Türkan Saylan" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 16, soru: "Sıfır (0) rakamını ilk kez kullanan matematikçi kimdir?", secenekler: { A: "Harezmi", B: "Pisagor", C: "Öklid", D: "Arşimet" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 17, soru: "İlk insansız uçuş denemesini yapan Osmanlı bilgini kimdir?", secenekler: { A: "Hezarfen Ahmed Çelebi", B: "Lagari Hasan Çelebi", C: "Piri Reis", D: "Evliya Çelebi" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 18, soru: "İlk roketli uçuşu gerçekleştiren Osmanlı bilgini kimdir?", secenekler: { A: "Lagari Hasan Çelebi", B: "Hezarfen", C: "Ali Kuşçu", D: "Takiyüddin" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 19, soru: "Dünyanın ilk kadın savaş pilotu kimdir?", secenekler: { A: "Sabiha Gökçen", B: "Nene Hatun", C: "Halide Edip", D: "Safiye Ali" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 20, soru: "Türk tarihinin en büyük mimarı, 'Koca Sinan' olarak anılan kişi kimdir?", secenekler: { A: "Mimar Sinan", B: "Mimar Hayreddin", C: "Sedefkar Mehmed Ağa", D: "Mimar Kemalettin" }, dogruCevap: "A" },

    // 21-40: Kimya Formülleri ve Elementler
    { kategori: "Bilim", seviye: 21, soru: "Suyun kimyasal formülü nedir?", secenekler: { A: "H2O", B: "CO2", C: "NaCl", D: "O2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 22, soru: "Sofra tuzunun formülü nedir?", secenekler: { A: "NaCl", B: "HCl", C: "NaOH", D: "KOH" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 23, soru: "Karbondioksit gazının formülü nedir?", secenekler: { A: "CO", B: "CO2", C: "C2O", D: "O2" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 24, soru: "Tuz ruhu olarak bilinen asidin formülü nedir?", secenekler: { A: "H2SO4", B: "HCl", C: "HNO3", D: "HF" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 25, soru: "Zaç yağı olarak bilinen sülfürik asidin formülü nedir?", secenekler: { A: "H2SO4", B: "HCl", C: "HNO3", D: "H3PO4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 26, soru: "Kezzap olarak bilinen nitrik asidin formülü nedir?", secenekler: { A: "HNO3", B: "HCl", C: "NH3", D: "CH4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 27, soru: "Amonyak bileşiğinin formülü nedir?", secenekler: { A: "NH3", B: "NH4", C: "N2H", D: "NO2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 28, soru: "Metan gazının formülü nedir?", secenekler: { A: "CH4", B: "C2H6", C: "CO2", D: "H2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 29, soru: "Gümüş elementinin simgesi nedir?", secenekler: { A: "Au", B: "Ag", C: "Cu", D: "Fe" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 30, soru: "Bakır elementinin simgesi nedir?", secenekler: { A: "Ba", B: "Bk", C: "Cu", D: "C" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 31, soru: "Demir elementinin simgesi nedir?", secenekler: { A: "D", B: "De", C: "Fe", D: "F" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 32, soru: "Kalay elementinin simgesi nedir?", secenekler: { A: "K", B: "Ka", C: "Sn", D: "S" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 33, soru: "Cıva elementinin simgesi nedir?", secenekler: { A: "C", B: "Ci", C: "Hg", D: "Pb" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 34, soru: "Kurşun elementinin simgesi nedir?", secenekler: { A: "K", B: "Pb", C: "Kr", D: "Pu" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 35, soru: "Potasyum elementinin simgesi nedir?", secenekler: { A: "P", B: "Po", C: "K", D: "Pt" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 36, soru: "Sodyum elementinin simgesi nedir?", secenekler: { A: "S", B: "So", C: "Na", D: "N" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 37, soru: "Kalsiyum karbonat (Kireç taşı) formülü nedir?", secenekler: { A: "CaCO3", B: "CaO", C: "Ca(OH)2", D: "CaCl2" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 38, soru: "Sirke asidinin formülü nedir?", secenekler: { A: "CH3COOH", B: "HCOOH", C: "C2H5OH", D: "CH4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 39, soru: "Helyum elementinin simgesi nedir?", secenekler: { A: "H", B: "He", C: "Hy", D: "Li" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 40, soru: "Azot elementinin simgesi nedir?", secenekler: { A: "Az", B: "A", C: "N", D: "At" }, dogruCevap: "C" },

    // 41-60: İcatlar ve Teknoloji
    { kategori: "Bilim", seviye: 41, soru: "Telefonun mucidi kimdir?", secenekler: { A: "Graham Bell", B: "Edison", C: "Tesla", D: "Morse" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 42, soru: "Ampulü icat eden bilim insanı kimdir?", secenekler: { A: "Newton", B: "Tesla", C: "Edison", D: "Watt" }, dogruCevap: "C" },
    { kategori: "Bilim", seviye: 43, soru: "Radyoyu icat eden kişi kimdir?", secenekler: { A: "Marconi", B: "Baird", C: "Bell", D: "Edison" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 44, soru: "Televizyonun mucidi kimdir?", secenekler: { A: "John Logie Baird", B: "Steve Jobs", C: "Bill Gates", D: "Graham Bell" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 45, soru: "Kuduz aşısını bulan bilim insanı kimdir?", secenekler: { A: "Louis Pasteur", B: "Robert Koch", C: "Fleming", D: "Darwin" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 46, soru: "Penisilini keşfeden bilim insanı kimdir?", secenekler: { A: "Alexander Fleming", B: "Pasteur", C: "Mendel", D: "Tesla" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 47, soru: "Matbaayı icat eden kişi kimdir?", secenekler: { A: "Gutenberg", B: "Newton", C: "Einstein", D: "Galileo" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 48, soru: "Buharlı makineyi geliştiren mucit kimdir?", secenekler: { A: "James Watt", B: "Edison", C: "Tesla", D: "Ford" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 49, soru: "İlk bilgisayarın adı nedir?", secenekler: { A: "ENIAC", B: "Apple 1", C: "Deep Blue", D: "Altair" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 50, soru: "Dünya Çapında Ağ (WWW) sistemini kuran kimdir?", secenekler: { A: "Tim Berners-Lee", B: "Mark Zuckerberg", C: "Bill Gates", D: "Elon Musk" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 51, soru: "Dinamiti icat eden ve adına ödüller düzenlenen kişi?", secenekler: { A: "Alfred Nobel", B: "Einstein", C: "Oppenheimer", D: "Curie" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 52, soru: "Yerçekimi kanununu bulan bilim insanı kimdir?", secenekler: { A: "Newton", B: "Galileo", C: "Kepler", D: "Arşimet" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 53, soru: "Teleskopla gökyüzünü inceleyen ilk bilim insanı?", secenekler: { A: "Galileo", B: "Newton", C: "Copernicus", D: "Bruno" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 54, soru: "Alternatif akımı (AC) bulan mucit kimdir?", secenekler: { A: "Nikola Tesla", B: "Edison", C: "Ohm", D: "Volt" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 55, soru: "Dünya'nın yuvarlak olduğunu ispatlayan denizci?", secenekler: { A: "Magellan", B: "Kolomb", C: "Vasco da Gama", D: "Amerigo Vespucci" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 56, soru: "X ışınlarını keşfeden bilim insanı kimdir?", secenekler: { A: "Röntgen", B: "Curie", C: "Becquerel", D: "Bohr" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 57, soru: "Radyoaktivite üzerine çalışmalarıyla 2 Nobel alan kadın?", secenekler: { A: "Marie Curie", B: "Rosalind Franklin", C: "Lise Meitner", D: "Ada Lovelace" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 58, soru: "İlk otomobili icat eden kişi kimdir?", secenekler: { A: "Karl Benz", B: "Henry Ford", C: "Tesla", D: "Diesel" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 59, soru: "Stetoskopu icat eden doktor kimdir?", secenekler: { A: "Rene Laennec", B: "Hipokrat", C: "Galen", D: "Lister" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 60, soru: "İlk uçağı uçuran kardeşler kimlerdir?", secenekler: { A: "Wright Kardeşler", B: "Montgolfier Kardeşler", C: "Lumiere Kardeşler", D: "Grimm Kardeşler" }, dogruCevap: "A" },

    // 61-80: Uzay, Fizik ve Doğa Bilimleri
    { kategori: "Bilim", seviye: 61, soru: "Güneş sistemindeki en büyük gezegen hangisidir?", secenekler: { A: "Jüpiter", B: "Satürn", C: "Neptün", D: "Dünya" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 62, soru: "Güneş'e en yakın gezegen hangisidir?", secenekler: { A: "Merkür", B: "Venüs", C: "Mars", D: "Dünya" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 63, soru: "Halkalarıyla ünlü gezegen hangisidir?", secenekler: { A: "Satürn", B: "Uranüs", C: "Jüpiter", D: "Mars" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 64, soru: "Işık hızının yaklaşık değeri saniyede kaç km'dir?", secenekler: { A: "300.000", B: "150.000", C: "500.000", D: "1.000.000" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 65, soru: "Sıvıların kaldırma kuvvetini bulan bilgin kimdir?", secenekler: { A: "Arşimet", B: "Pisagor", C: "Öklid", D: "Tales" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 66, soru: "Su kaç derecede kaynar?", secenekler: { A: "100", B: "90", C: "110", D: "80" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 67, soru: "Maddenin kaç hali vardır (temelde)?", secenekler: { A: "3", B: "4", C: "2", D: "5" }, dogruCevap: "B" },
    { kategori: "Bilim", seviye: 68, soru: "Dünyanın en dış katmanı hangisidir?", secenekler: { A: "Yer Kabuğu", B: "Manto", C: "Çekirdek", D: "Magma" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 69, soru: "Bitkilerin güneş ışığıyla besin üretmesine ne denir?", secenekler: { A: "Fotosentez", B: "Solunum", C: "Terleme", D: "Mayalanma" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 70, soru: "İnsan vücudundaki en sert madde hangisidir?", secenekler: { A: "Diş Minesi", B: "Kemik", C: "Kıkırdak", D: "Tırnak" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 71, soru: "DNA'nın yapısı hangi şekildedir?", secenekler: { A: "Çift Sarmal", B: "Düz", C: "Daire", D: "Küp" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 72, soru: "Kalıtım biliminin (Genetik) babası kimdir?", secenekler: { A: "Gregor Mendel", B: "Darwin", C: "Lamarck", D: "Linnaeus" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 73, soru: "Kırmızı kan hücrelerine ne ad verilir?", secenekler: { A: "Alyuvar", B: "Akyuvar", C: "Trombosit", D: "Plazma" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 74, soru: "Vücudun savunma sisteminde görevli kan hücreleri?", secenekler: { A: "Akyuvar", B: "Alyuvar", C: "Hemoglobin", D: "Serum" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 75, soru: "Hangi organımız kanı vücuda pompalar?", secenekler: { A: "Kalp", B: "Akciğer", C: "Böbrek", D: "Karaciğer" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 76, soru: "Vücudumuzun en büyük organı hangisidir?", secenekler: { A: "Deri", B: "Karaciğer", C: "Bağırsak", D: "Akciğer" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 77, soru: "Hangi vitamin güneş ışığıyla sentezlenir?", secenekler: { A: "D Vitamini", B: "C Vitamini", C: "A Vitamini", D: "B12" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 78, soru: "Dünyanın en büyük okyanusu hangisidir?", secenekler: { A: "Büyük Okyanus (Pasifik)", B: "Atlas Okyanusu", C: "Hint Okyanusu", D: "Arktik Okyanusu" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 79, soru: "Atmosferdeki ozon tabakası bizi neyden korur?", secenekler: { A: "Ultraviyole Işınlar", B: "Meteorlar", C: "Soğuktan", D: "Yağmurdan" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 80, soru: "Yer sarsıntılarını ölçen alete ne denir?", secenekler: { A: "Sismograf", B: "Barometre", C: "Termometre", D: "Hangiometre" }, dogruCevap: "A" },

    // 81-100: Karışık Bilim ve Genel Kültür
    { kategori: "Bilim", seviye: 81, soru: "Isıyı ölçen alet hangisidir?", secenekler: { A: "Kalorimetre", B: "Termometre", C: "Dinamometre", D: "Barometre" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 82, soru: "Hava basıncını ölçen alet hangisidir?", secenekler: { A: "Barometre", B: "Higrometre", C: "Altimetre", D: "Sismometre" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 83, soru: "Suyun donma noktası kaç derecedir (Celsius)?", secenekler: { A: "0", B: "-1", C: "1", D: "4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 84, soru: "Elmas hangi elementin kristal halidir?", secenekler: { A: "Karbon", B: "Silisyum", C: "Kükürt", D: "Azot" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 85, soru: "Periyodik tablonun babası kimdir?", secenekler: { A: "Mendeleyev", B: "Dalton", C: "Bohr", D: "Rutherford" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 86, soru: "En sert doğal madde hangisidir?", secenekler: { A: "Elmas", B: "Çelik", C: "Titanyum", D: "Kuvars" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 87, soru: "Ses hızı havada yaklaşık kaç m/s'dir?", secenekler: { A: "340", B: "1000", C: "100", D: "200.000" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 88, soru: "Işığın kırılmasını açıklayan İslam bilgini?", secenekler: { A: "İbn-i Heysem", B: "Ömer Hayyam", C: "Kindi", D: "Biruni" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 89, soru: "Gökkuşağının 7 renginden ortadaki hangisidir?", secenekler: { A: "Yeşil", B: "Sarı", C: "Mavi", D: "Kırmızı" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 90, soru: "Bir mıknatısın kaç kutbu vardır?", secenekler: { A: "2", B: "1", C: "3", D: "4" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 91, soru: "Atomun çekirdeğindeki artı yüklü tanecik?", secenekler: { A: "Proton", B: "Nötron", C: "Elektron", D: "Pozitron" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 92, soru: "Atomun çekirdeğindeki yüksüz tanecik?", secenekler: { A: "Nötron", B: "Proton", C: "Elektron", D: "Kuark" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 93, soru: "Elektrik akım şiddeti birimi nedir?", secenekler: { A: "Amper", B: "Volt", C: "Watt", D: "Ohm" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 94, soru: "Direnç birimi nedir?", secenekler: { A: "Ohm", B: "Volt", C: "Joule", D: "Newton" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 95, soru: "Güç birimi nedir?", secenekler: { A: "Watt", B: "Pascal", C: "Newton", D: "Amper" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 96, soru: "Sıvı haldeki tek metal hangisidir?", secenekler: { A: "Cıva", B: "Kurşun", C: "Brom", D: "Altın" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 97, soru: "Kandaki şeker oranını düzenleyen hormon?", secenekler: { A: "İnsülin", B: "Adrenalin", C: "Tiroksin", D: "Kortizol" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 98, soru: "Hangi hayvan ses dalgalarıyla yolunu bulur?", secenekler: { A: "Yarasa", B: "Baykuş", C: "Kartal", D: "Yılan" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 99, soru: "Hangi gezegen yan yatmış bir varil gibi döner?", secenekler: { A: "Uranüs", B: "Neptün", C: "Venüs", D: "Mars" }, dogruCevap: "A" },
    { kategori: "Bilim", seviye: 100, soru: "Yapay zekanın babası kabul edilen bilim insanı?", secenekler: { A: "Alan Turing", B: "Bill Gates", C: "Elon Musk", D: "Steve Jobs" }, dogruCevap: "A" }
);
 