window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Klasik ve Kolay Bilmeceler
    { seviye: 1, kategori: "Bilmece", soru: "Şehirleri var ama evleri yok. Dağları var ama ağaçları yok. Suları var ama balıkları yok. Bu nedir?", secenekler: { A: "Harita", B: "Küresel ısınma", C: "Çöl", D: "Resim" }, dogruCevap: "A" },
    { seviye: 1, kategori: "Bilmece", soru: "Ben giderim o gider, üstümde gölge eder.", secenekler: { A: "Bulut", B: "Şemsiye", C: "Güneş", D: "Şapka" }, dogruCevap: "B" },
    { seviye: 1, kategori: "Bilmece", soru: "Pazardan aldım bir tane, eve geldim bin tane.", secenekler: { A: "Pirinç", B: "Nar", C: "Mısır", D: "Üzüm" }, dogruCevap: "B" },
    { seviye: 1, kategori: "Bilmece", soru: "Sesi var canı yok, konuşur ağzı yok.", secenekler: { A: "Rüzgar", B: "Yankı", C: "Radyo", D: "Telefon" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Bilmece", soru: "Yer altında yağlı kayış.", secenekler: { A: "Solucan", B: "Yılan", C: "Kemer", D: "Hortum" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Bilmece", soru: "İki camlı pencere, bakıp durur her yere.", secenekler: { A: "Gözlük", B: "Dürbün", C: "Göz", D: "Ayna" }, dogruCevap: "A" },
    { seviye: 2, kategori: "Bilmece", soru: "İncecik beli, elimdedir dili.", secenekler: { A: "Kaşık", B: "Zil", C: "Kalem", D: "Bardak" }, dogruCevap: "C" },
    { seviye: 2, kategori: "Bilmece", soru: "Kolu var eli yok, karnı yarık karnı yok.", secenekler: { A: "Ceket", B: "Gömlek", C: "Yelek", D: "Pantolon" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Bilmece", soru: "Bir küçücük fıçıcık, içi dolu turşucuk.", secenekler: { A: "Limon", B: "Zeytin", C: "Limon", D: "Mandalina" }, dogruCevap: "D" },
    { seviye: 3, kategori: "Bilmece", soru: "Ayakları var yürüyemez, dili var konuşamaz.", secenekler: { A: "Masa", B: "Sandalye", C: "Ayakkabı", D: "Araba" }, dogruCevap: "C" },
    { seviye: 3, kategori: "Bilmece", soru: "Gökten iner bir avuç, tadı şekerden tatlı.", secenekler: { A: "Kar", B: "Yağmur", C: "Dut", D: "Dolu" }, dogruCevap: "C" },
    { seviye: 4, kategori: "Bilmece", soru: "Yatınca yatar, kalkınca kalkar.", secenekler: { A: "Yorgan", B: "Yastık", C: "Parmak", D: "Ayakkabı" }, dogruCevap: "C" },
    { seviye: 4, kategori: "Bilmece", soru: "Hiç ağzı yok ama her dile cevap verir.", secenekler: { A: "Kağıt", B: "Yankı", C: "Kitap", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Bilmece", soru: "Bir tarlam var, beyaz gül açar.", secenekler: { A: "Gökyüzü / Yıldızlar", B: "Kağıt / Yazı", C: "Bahçe / Kar", D: "Deniz / Köpük" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Bilmece", soru: "Dışı var içi yok, dayak yer suçu yok.", secenekler: { A: "Top", B: "Davul", C: "Halı", D: "Yastık" }, dogruCevap: "B" },
    { seviye: 5, kategori: "Bilmece", soru: "Geldi mi gitmez, gitti mi gelmez.", secenekler: { A: "Misafir", B: "Gençlik", C: "Zaman", D: "Sağlık" }, dogruCevap: "B" },
    { seviye: 5, kategori: "Bilmece", soru: "Ağzı var dili yok, nefesi var canı yok.", secenekler: { A: "Düdük", B: "Ney", C: "Kavala", D: "Balon" }, dogruCevap: "D" },
    { seviye: 6, kategori: "Bilmece", soru: "Kapağı var kitap değil, kulu var kapı değil.", secenekler: { A: "Tencere", B: "Göz", C: "Dolap", D: "Çanta" }, dogruCevap: "B" },
    { seviye: 6, kategori: "Bilmece", soru: "Daldan dala atlar, kuyruğuyla oynar.", secenekler: { A: "Kedi", B: "Maymun", C: "Sincap", D: "Kuş" }, dogruCevap: "B" },
    { seviye: 6, kategori: "Bilmece", soru: "Bir ağacı oymuşlar, içine dünyayı koymuşlar.", secenekler: { A: "Gemi", B: "Radyo", C: "Televizyon", D: "Sandık" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Bilmece", soru: "Kanadı var uçamaz, ağzı var konuşamaz.", secenekler: { A: "Tavuk", B: "Balık", C: "Penguen", D: "Uçak" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Bilmece", soru: "Gökyüzünde gördüm bir köprü, rengi var yedi türlü.", secenekler: { A: "Bulut", B: "Uçak", C: "Gökkuşağı", D: "Yıldız" }, dogruCevap: "C" },
    { seviye: 7, kategori: "Bilmece", soru: "Uzun uzun uzarlar, her yıl kışın azalırlar.", secenekler: { A: "Günler", B: "Geceler", C: "Saçlar", D: "Yollar" }, dogruCevap: "A" },
    { seviye: 8, kategori: "Bilmece", soru: "Canı var kanı yok, sesi var dili yok.", secenekler: { A: "Arı", B: "Sinek", C: "Kelebek", D: "Balık" }, dogruCevap: "B" },
    { seviye: 8, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Tükenmez kalem", B: "Kurşun kalem", C: "Kontrol kalemi", D: "Dolma kalem" }, dogruCevap: "C" },

    // 26-100: Karışık, Zeka ve Kelime Oyunlu Bilmeceler
    { seviye: 26, kategori: "Bilmece", soru: "Karşıdan baktım hiç yok, yanına gittim pek çok.", secenekler: { A: "Karınca", B: "Çiçek", C: "Kum", D: "Ağaç" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Bilmece", soru: "En çok hangi ilimizde güneş gözlüğü kullanılır?", secenekler: { A: "Antalya", B: "Muğla", C: "Göz-lük (Gözlük)", D: "Van" }, dogruCevap: "C" },
    { seviye: 28, kategori: "Bilmece", soru: "Pişirirsen aş olur, pişirmezsen kuş olur.", secenekler: { A: "Pirinç", B: "Yumurta", C: "Mısır", D: "Buğday" }, dogruCevap: "B" },
    { seviye: 29, kategori: "Bilmece", soru: "İçinde derya var, nehir var ama hiç su yok.", secenekler: { A: "Atlas", B: "Şişe", C: "Sürahi", D: "Bardak" }, dogruCevap: "A" },
    { seviye: 30, kategori: "Bilmece", soru: "Canlı gider, cansız gelir.", secenekler: { A: "Avcı", B: "Balıkçı", C: "Kasap", D: "Aşçı" }, dogruCevap: "B" },
    { seviye: 31, kategori: "Bilmece", soru: "Dokunmadan kırılan şey nedir?", secenekler: { A: "Cam", B: "Kalp", C: "Buz", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 32, kategori: "Bilmece", soru: "Hangi tastan su içilmez?", secenekler: { A: "Altın tas", B: "Gümüş tas", C: "Kafatası", D: "Bakır tas" }, dogruCevap: "C" },
    { seviye: 33, kategori: "Bilmece", soru: "Sadece kullanıldığında kırılan şey nedir?", secenekler: { A: "Yumurta", B: "Kömür", C: "Fındık", D: "Ceviz" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Bilmece", soru: "Hangi macunla diş fırçalanmaz?", secenekler: { A: "Beyaz macun", B: "Naneli macun", C: "Lahmacun", D: "Çilekli macun" }, dogruCevap: "C" },
    { seviye: 35, kategori: "Bilmece", soru: "Sıcak dondurma nerede bulunur?", secenekler: { A: "Antalya'da", B: "Fırında", C: "Güneşte", D: "Hayallerde" }, dogruCevap: "B" },
    { seviye: 36, kategori: "Bilmece", soru: "Yarım elma neye benzer?", secenekler: { A: "Ay'a", B: "Elmaya", C: "Diğer yarısına", D: "Topa" }, dogruCevap: "C" },
    { seviye: 37, kategori: "Bilmece", soru: "Hangi karnede not olmaz?", secenekler: { A: "Sağlık karnesi", B: "Okul karnesi", C: "Sürücü karnesi", D: "Vize karnesi" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Bilmece", soru: "Yürür yürür iz etmez, hızı her gün değişmez.", secenekler: { A: "Araba", B: "Saat", C: "Güneş", D: "Rüzgar" }, dogruCevap: "B" },
    { seviye: 39, kategori: "Bilmece", soru: "En ağır meyve hangisidir?", secenekler: { A: "Karpuz", B: "Kavun", C: "Bal kabağı", D: "İncir (B-in-cir)" }, dogruCevap: "D" },
    { seviye: 40, kategori: "Bilmece", soru: "Kökü var ama bitki değil, tırmanır ama hayvan değil.", secenekler: { A: "Diş", B: "Tırnak", C: "Saç", D: "Burun" }, dogruCevap: "A" },
    { seviye: 41, kategori: "Bilmece", soru: "Gözle görülmez, elle tutulmaz, onsuz yaşanmaz.", secenekler: { A: "Rüzgar", B: "Hava", C: "Koku", D: "Sevgi" }, dogruCevap: "B" },
    { seviye: 42, kategori: "Bilmece", soru: "Dili yok ama her şeyi anlatır.", secenekler: { A: "Resim", B: "Kitap", C: "Heykel", D: "Mektup" }, dogruCevap: "B" },
    { seviye: 43, kategori: "Bilmece", soru: "Hangi kapı açılmaz?", secenekler: { A: "Demir kapı", B: "Tahta kapı", C: "Kale kapısı", D: "Çıkış kapısı" }, dogruCevap: "D" },
    { seviye: 44, kategori: "Bilmece", soru: "Başı var kulağı yok, karnı var bacağı yok.", secenekler: { A: "Yılan", B: "Kuş", C: "Balık", D: "Böcek" }, dogruCevap: "A" },
    { seviye: 45, kategori: "Bilmece", soru: "Bir küçücük sandık, içi dolu boncuk.", secenekler: { A: "Nar", B: "Bezelye", C: "Mısır", D: "Fasulye" }, dogruCevap: "A" },
    { seviye: 46, kategori: "Bilmece", soru: "Gece çıkar, gündüz kaçar.", secenekler: { A: "Güneş", B: "Ay", C: "Yıldız", D: "Bulut" }, dogruCevap: "B" },
    { seviye: 47, kategori: "Bilmece", soru: "Şekerden tatlı, zehirden acı.", secenekler: { A: "Bal", B: "Söz", C: "Aşk", D: "Kader" }, dogruCevap: "B" },
    { seviye: 48, kategori: "Bilmece", soru: "Açarsın içini, görürsün kendini.", secenekler: { A: "Kitap", B: "Ayna", C: "Pencere", D: "Kapı" }, dogruCevap: "B" },
    { seviye: 49, kategori: "Bilmece", soru: "Ay varken çıkar, gün varken kaçar.", secenekler: { A: "Yıldız", B: "Baykuş", C: "Gölge", D: "Rüya" }, dogruCevap: "A" },
    { seviye: 50, kategori: "Bilmece", soru: "Hangi bağda üzüm yetişmez?", secenekler: { A: "Kara bağ", B: "Karabağ", C: "Siyah bağ", D: "Ayakkabı bağı" }, dogruCevap: "D" },
    { seviye: 51, kategori: "Bilmece", soru: "Canı var kanı yok, karnı var canı yok.", secenekler: { A: "Bebek", B: "Oyuncak bebek", C: "Kedi", D: "Kuş" }, dogruCevap: "B" },
    { seviye: 52, kategori: "Bilmece", soru: "Ateşe girer yanmaz, suya girer boğulmaz.", secenekler: { A: "Hava", B: "Işık", C: "Rüzgar", D: "Gölge" }, dogruCevap: "B" },
    { seviye: 53, kategori: "Bilmece", soru: "Ben giderim o gider, yanımda arkamda gider.", secenekler: { A: "Gölge", B: "Bulut", C: "Ay", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Bilmece", soru: "Başı var beyni yok.", secenekler: { A: "Soğan", B: "Patates", C: "Kabak", D: "Elma" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Bilmece", soru: "Tüyden hafif ama kimse onu çok uzun süre tutamaz.", secenekler: { A: "Bulut", B: "Balon", C: "Nefes", D: "Su damlası" }, dogruCevap: "C" },
    { seviye: 56, kategori: "Bilmece", soru: "İnsan neyi yutarsa ölmez ama yutkunursa ölür?", secenekler: { A: "Su", B: "Yemek", C: "Tükürük", D: "Hava" }, dogruCevap: "C" },
    { seviye: 57, kategori: "Bilmece", soru: "Gelen gider, giden gelmez.", secenekler: { A: "Zaman", B: "Gençlik", C: "Misafir", D: "Güneş" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Bilmece", soru: "Her şeyi görür ama kendini göremez.", secenekler: { A: "Kamera", B: "Göz", C: "Ayna", D: "Dürbün" }, dogruCevap: "B" },
    { seviye: 59, kategori: "Bilmece", soru: "Doluşuruz bir kutuya, gideriz uzaklara.", secenekler: { A: "Araba", B: "Otobüs", C: "Tren", D: "Uçak" }, dogruCevap: "B" },
    { seviye: 60, kategori: "Bilmece", soru: "Evi var kapısı yok, içi dolu sofrası yok.", secenekler: { A: "Karpuz", B: "Kabak", C: "Domates", D: "Biber" }, dogruCevap: "A" },
    { seviye: 61, kategori: "Bilmece", soru: "Hangi bankaya para yatırılmaz?", secenekler: { A: "Merkez bankası", B: "Kan bankası", C: "Ziraat bankası", D: "Halk bankası" }, dogruCevap: "B" },
    { seviye: 62, kategori: "Bilmece", soru: "Açarsın genişler, kaparsın daralır.", secenekler: { A: "Kapı", B: "Pencere", C: "Şemsiye", D: "Perde" }, dogruCevap: "C" },
    { seviye: 63, kategori: "Bilmece", soru: "Dışı var içi yok, sesi var dili yok.", secenekler: { A: "Zil", B: "Çan", C: "Düdük", D: "Kaval" }, dogruCevap: "A" },
    { seviye: 64, kategori: "Bilmece", soru: "Ayakları su içer, üstü güneşlenir.", secenekler: { A: "İnsan", B: "Hayvan", C: "Ağaç", D: "Gölge" }, dogruCevap: "C" },
    { seviye: 65, kategori: "Bilmece", soru: "Hangi filin hortumu yoktur?", secenekler: { A: "Asya fili", B: "Afrika fili", C: "Profil", D: "Yavru fil" }, dogruCevap: "C" },
    { seviye: 66, kategori: "Bilmece", soru: "Yazın giyer, kışın çıkarır.", secenekler: { A: "Mont", B: "Kazak", C: "Ağaç", D: "Çiçek" }, dogruCevap: "C" },
    { seviye: 67, kategori: "Bilmece", soru: "Hangi kalemle resim yapılmaz?", secenekler: { A: "Boya kalemi", B: "Kurşun kalem", C: "Kontrol kalemi", D: "Keçeli kalem" }, dogruCevap: "C" },
    { seviye: 68, kategori: "Bilmece", soru: "Hiç yorulmadan dünyayı gezen nedir?", secenekler: { A: "Bulut", B: "Rüzgar", C: "Güneş", D: "Ay" }, dogruCevap: "C" },
    { seviye: 69, kategori: "Bilmece", soru: "Dışı kaktüs, içi süt.", secenekler: { A: "Hindistan cevizi", B: "Ananas", C: "Kavun", D: "Karpuz" }, dogruCevap: "A" },
    { seviye: 70, kategori: "Bilmece", soru: "Geceleri fener, gündüzleri söner.", secenekler: { A: "Mum", B: "Lamba", C: "Ateş böceği", D: "Güneş" }, dogruCevap: "C" },
    { seviye: 71, kategori: "Bilmece", soru: "Hangi kuşun kanadı vardır ama uçamaz?", secenekler: { A: "Deve kuşu", B: "Serçe", C: "Kırlangıç", D: "Kartal" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Bilmece", soru: "Bir yanı beyaz, bir yanı kara.", secenekler: { A: "Gündüz - Gece", B: "Siyah - Beyaz", C: "Kağıt - Kalem", D: "Bulut - Yağmur" }, dogruCevap: "A" },
    { seviye: 73, kategori: "Bilmece", soru: "Hem ısıtır, hem yakar.", secenekler: { A: "Güneş", B: "Ateş", C: "Soba", D: "Elektrik" }, dogruCevap: "B" },
    { seviye: 74, kategori: "Bilmece", soru: "Hangi meyve her zaman yalnızdır?", secenekler: { A: "Elma", B: "Armut", C: "İncir", D: "Üzüm" }, dogruCevap: "B" },
    { seviye: 75, kategori: "Bilmece", soru: "İçinde rüzgar eser, kapısında kilit yok.", secenekler: { A: "Mağara", B: "Baca", C: "Pencere", D: "Kapı" }, dogruCevap: "B" },
    { seviye: 76, kategori: "Bilmece", soru: "Yer altında sakallı dede.", secenekler: { A: "Patates", B: "Soğan", C: "Pırasa", D: "Havuç" }, dogruCevap: "C" },
    { seviye: 77, kategori: "Bilmece", soru: "Hangi köprünün altından su geçmez?", secenekler: { A: "Asma köprü", B: "Taş köprü", C: "Diş köprüsü", D: "Beton köprü" }, dogruCevap: "C" },
    { seviye: 78, kategori: "Bilmece", soru: "En temiz meyve hangisidir?", secenekler: { A: "Elma", B: "Üzüm", C: "Yıkanmış kiraz", D: "Yalan (Yal-an)" }, dogruCevap: "D" },
    { seviye: 79, kategori: "Bilmece", soru: "Kulağını bükünce sesi çıkar.", secenekler: { A: "Radyo", B: "Televizyon", C: "Müzik kutusu", D: "Musluk" }, dogruCevap: "D" },
    { seviye: 80, kategori: "Bilmece", soru: "Hangi ağaçta dal olmaz?", secenekler: { A: "Çam ağacı", B: "Elma ağacı", C: "Soyağacı", D: "Meşe ağacı" }, dogruCevap: "C" },
    { seviye: 81, kategori: "Bilmece", soru: "Sıcak dondurma nerede olur?", secenekler: { A: "Fırında", B: "Güneşte", C: "Antalya'da", D: "Kızartmada" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Bilmece", soru: "Gittikçe kısalan şey nedir?", secenekler: { A: "Yol", B: "Ömür", C: "İp", D: "Kağıt" }, dogruCevap: "B" },
    { seviye: 83, kategori: "Bilmece", soru: "Hem ağlar hem güler.", secenekler: { A: "Bebek", B: "Bulut", C: "İnsan", D: "Yağmur" }, dogruCevap: "C" },
    { seviye: 84, kategori: "Bilmece", soru: "Hangi masada yemek yenmez?", secenekler: { A: "Altın masa", B: "Yemek masası", C: "Çalışma masası", D: "Dosya masası" }, dogruCevap: "D" },
    { seviye: 85, kategori: "Bilmece", soru: "Suya girer ıslanmaz, ateşe girer yanmaz.", secenekler: { A: "Gölge", B: "Işık", C: "Hava", D: "Koku" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Bilmece", soru: "Sesi var ama canı yok.", secenekler: { A: "Rüzgar", B: "Yankı", C: "Radyo", D: "Zil" }, dogruCevap: "B" },
    { seviye: 87, kategori: "Bilmece", soru: "Hangi kuşun kanadı var ama uçamaz?", secenekler: { A: "Penguen", B: "Serçe", C: "Kartal", D: "Atmaca" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Bilmece", soru: "Herkesin önünde olan ama kimsenin dokunamadığı nedir?", secenekler: { A: "Gelecek", B: "Güneş", C: "Hava", D: "Bulut" }, dogruCevap: "A" },
    { seviye: 89, kategori: "Bilmece", soru: "Hangi gül kokmaz?", secenekler: { A: "Yapay gül", B: "Kurumuş gül", C: "Virgül", D: "Solmuş gül" }, dogruCevap: "C" },
    { seviye: 90, kategori: "Bilmece", soru: "Canı var ama nefesi yok.", secenekler: { A: "Balık", B: "Bitki", C: "Gölge", D: "Ayna" }, dogruCevap: "B" },
    { seviye: 91, kategori: "Bilmece", soru: "Yer altında kırmızı fener.", secenekler: { A: "Turp", B: "Havuç", C: "Domates", D: "Biber" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Bilmece", soru: "Hangi denizde balık olmaz?", secenekler: { A: "Ölü Deniz", B: "Ege Denizi", C: "Akdeniz", D: "Karadeniz" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Bilmece", soru: "Ben giderim o gider, arkamdan beni izler.", secenekler: { A: "Gölge", B: "Kedi", C: "Bulut", D: "Ay" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Bilmece", soru: "Hangi top zıplamaz?", secenekler: { A: "Futbol topu", B: "Kar topu", C: "Tenis topu", D: "Basketbol topu" }, dogruCevap: "B" },
    { seviye: 95, kategori: "Bilmece", soru: "Kolu var ama eli yok.", secenekler: { A: "Ceket", B: "Sandalye", C: "Masa", D: "Dolap" }, dogruCevap: "B" },
    { seviye: 96, kategori: "Bilmece", soru: "Hangi saatte yemek yenmez?", secenekler: { A: "Duvar saatinde", B: "Sabah saatinde", C: "Öğle saatinde", D: "Akşam saatinde" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Bilmece", soru: "İncecik beli var, tatlı dili var.", secenekler: { A: "Kaşık", B: "Bardak", C: "Kalem", D: "Kitap" }, dogruCevap: "C" },
    { seviye: 98, kategori: "Bilmece", soru: "Sesi var ama canı yok.", secenekler: { A: "Rüzgar", B: "Yankı", C: "Radyo", D: "Telefon" }, dogruCevap: "B" },
    { seviye: 99, kategori: "Bilmece", soru: "Hangi ağaçta dal olmaz?", secenekler: { A: "Meşe", B: "Soyağacı", C: "Çam", D: "Elma" }, dogruCevap: "B" },
    { seviye: 100, kategori: "Bilmece", soru: "Hangi kalemle yazı yazılmaz?", secenekler: { A: "Kurşun", B: "Tükenmez", C: "Kontrol kalemi", D: "Dolma" }, dogruCevap: "C" }
);
