window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Türkiye Fiziki Coğrafyası (Dağlar, Göller, Akarsular)
    { seviye: 1, kategori: "Coğrafya", soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { seviye: 2, kategori: "Coğrafya", soru: "Türkiye'nin en yüksek dağı hangisidir?", secenekler: { A: "Erciyes", B: "Süphan", C: "Ağrı Dağı", D: "Kaçkar" }, dogruCevap: "C" },
    { seviye: 3, kategori: "Coğrafya", soru: "Türkiye'nin yüzölçümü bakımından en büyük gölü hangisidir?", secenekler: { A: "Tuz Gölü", B: "Van Gölü", C: "Beyşehir Gölü", D: "Eğirdir Gölü" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Coğrafya", soru: "Türkiye'nin en uzun nehri (tamamı ülke sınırları içinde) hangisidir?", secenekler: { A: "Fırat", B: "Dicle", C: "Kızılırmak", D: "Yeşilırmak" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Coğrafya", soru: "Türkiye'nin en büyük deltası hangisidir?", secenekler: { A: "Çarşamba", B: "Bafra", C: "Çukurova", D: "Silifke" }, dogruCevap: "C" },
    { seviye: 6, kategori: "Coğrafya", soru: "Ege Bölgesi'nde dağlar denize nasıl uzanır?", secenekler: { A: "Paralel", B: "Dik", C: "Çapraz", D: "Kesik" }, dogruCevap: "B" },
    { seviye: 7, kategori: "Coğrafya", soru: "Türkiye'nin en büyük adası hangisidir?", secenekler: { A: "Bozcaada", B: "Gökçeada", C: "Büyükada", D: "Marmara Adası" }, dogruCevap: "B" },
    { seviye: 8, kategori: "Coğrafya", soru: "Nemrut Dağı ve üzerindeki dev heykeller hangi ilimizdedir?", secenekler: { A: "Adıyaman", B: "Malatya", C: "Şanlıurfa", D: "Bitlis" }, dogruCevap: "A" },
    { seviye: 9, kategori: "Coğrafya", soru: "Manyas (Kuş) Gölü hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Bursa", B: "Balıkesir", C: "Çanakkale", D: "Manisa" }, dogruCevap: "B" },
    { seviye: 10, kategori: "Coğrafya", soru: "Türkiye'nin en kuzey noktası olan İnceburun hangi ilimizdedir?", secenekler: { A: "Sinop", B: "Kırklareli", C: "Artvin", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 11, kategori: "Coğrafya", soru: "Dünyanın en büyük peribacaları oluşumları hangi bölgemizdedir?", secenekler: { A: "Ege", B: "İç Anadolu", C: "Doğu Anadolu", D: "Güneydoğu Anadolu" }, dogruCevap: "B" },
    { seviye: 12, kategori: "Coğrafya", soru: "Hangi ilimiz hem Asya hem de Avrupa kıtasında toprağa sahiptir?", secenekler: { A: "Çanakkale", B: "İstanbul", C: "Edirne", D: "Kocaeli" }, dogruCevap: "B" },
    { seviye: 13, kategori: "Coğrafya", soru: "Türkiye'nin en az yağış alan yöresi hangisidir?", secenekler: { A: "Iğdır Ovası", B: "Tuz Gölü Çevresi", C: "Güneydoğu Anadolu", D: "Ergene Havzası" }, dogruCevap: "B" },
    { seviye: 14, kategori: "Coğrafya", soru: "Toros Dağları hangi coğrafi bölgemizin karakteristik dağıdır?", secenekler: { A: "Ege", B: "Akdeniz", C: "Marmara", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 15, kategori: "Coğrafya", soru: "Yedi Göller Milli Parkı hangi ilimizdedir?", secenekler: { A: "Bolu", B: "Düzce", C: "Karabük", D: "Zonguldak" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Coğrafya", soru: "Türkiye'nin en batı ucu olan Avlaka Burnu hangi adadadır?", secenekler: { A: "Gökçeada", B: "Bozcaada", C: "Cunda", D: "Kefken" }, dogruCevap: "A" },
    { seviye: 17, kategori: "Coğrafya", soru: "Mavi Tünel Projesi hangi ovamızın sulanması için yapılmıştır?", secenekler: { A: "Konya Ovası", B: "Harran Ovası", C: "Iğdır Ovası", D: "Gediz Ovası" }, dogruCevap: "A" },
    { seviye: 18, kategori: "Coğrafya", soru: "Türkiye'de kış ılıklığının en belirgin olduğu bölge hangisidir?", secenekler: { A: "Akdeniz", B: "Ege", C: "Marmara", D: "Güneydoğu Anadolu" }, dogruCevap: "A" },
    { seviye: 19, kategori: "Coğrafya", soru: "Tortum Şelalesi hangi ilimizdedir?", secenekler: { A: "Erzurum", B: "Artvin", C: "Rize", D: "Trabzon" }, dogruCevap: "A" },
    { seviye: 20, kategori: "Coğrafya", soru: "Türkiye'nin 'Sakin Şehir' (Cittaslow) ünvanlı ilk ilçesi hangisidir?", secenekler: { A: "Seferihisar", B: "Akyaka", C: "Halfeti", D: "Taraklı" }, dogruCevap: "A" },
    { seviye: 21, kategori: "Coğrafya", soru: "Ihlara Vadisi hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Aksaray", B: "Nevşehir", C: "Niğde", D: "Kayseri" }, dogruCevap: "A" },
    { seviye: 22, kategori: "Coğrafya", soru: "Türkiye'nin en güneyindeki il hangisidir?", secenekler: { A: "Mersin", B: "Antalya", C: "Hatay", D: "Muğla" }, dogruCevap: "C" },
    { seviye: 23, kategori: "Coğrafya", soru: "İzmir'de bulunan meşhur kuş cennetinin adı nedir?", secenekler: { A: "Gala", B: "Çamaltı", C: "Sultan Sazlığı", D: "Birecik" }, dogruCevap: "B" },
    { seviye: 24, kategori: "Coğrafya", soru: "Sakarya Nehri hangi denize dökülür?", secenekler: { A: "Marmara", B: "Ege", C: "Karadeniz", D: "Akdeniz" }, dogruCevap: "C" },
    { seviye: 25, kategori: "Coğrafya", soru: "Erciyes Dağı hangi ilimizdedir?", secenekler: { A: "Kayseri", B: "Konya", C: "Sivas", D: "Aksaray" }, dogruCevap: "A" },

    // 26-50: Türkiye Ekonomik Coğrafyası (Tarım, Sanayi, Madenler)
    { seviye: 26, kategori: "Coğrafya", soru: "Dünyada fındık üretiminde 1. sırada olan ülke hangisidir?", secenekler: { A: "İtalya", B: "Türkiye", C: "ABD", D: "Gürcistan" }, dogruCevap: "B" },
    { seviye: 27, kategori: "Coğrafya", soru: "Türkiye'de çay tarımı nerede yoğunlaşmıştır?", secenekler: { A: "Doğu Karadeniz", B: "Batı Karadeniz", C: "Ege", D: "Akdeniz" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Coğrafya", soru: "Türkiye'de petrolün en çok çıkarıldığı il hangisidir?", secenekler: { A: "Batman", B: "Adıyaman", C: "Siirt", D: "Diyarbakır" }, dogruCevap: "A" },
    { seviye: 29, kategori: "Coğrafya", soru: "Zonguldak denilince akla gelen en önemli maden hangisidir?", secenekler: { A: "Linyit", B: "Taş Kömürü", C: "Demir", D: "Bakır" }, dogruCevap: "B" },
    { seviye: 30, kategori: "Coğrafya", soru: "Dünya bor rezervlerinin yaklaşık %70'inden fazlasına sahip ülke?", secenekler: { A: "Rusya", B: "Çin", C: "Türkiye", D: "ABD" }, dogruCevap: "C" },
    { seviye: 31, kategori: "Coğrafya", soru: "Türkiye'de pamuk üretiminde ilk sırada yer alan ilimiz?", secenekler: { A: "Adana", B: "Aydın", C: "Şanlıurfa", D: "Antalya" }, dogruCevap: "C" },
    { seviye: 32, kategori: "Coğrafya", soru: "Kayısı üretimiyle dünya çapında meşhur olan ilimiz?", secenekler: { A: "Malatya", B: "Elazığ", C: "Iğdır", D: "Erzincan" }, dogruCevap: "A" },
    { seviye: 33, kategori: "Coğrafya", soru: "Türkiye'de ipek böcekçiliği ve ipekli dokumada lider şehir?", secenekler: { A: "Bursa", B: "Diyarbakır", C: "Bilecik", D: "Sakarya" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Coğrafya", soru: "Lüle taşı sadece hangi ilimizde çıkarılır?", secenekler: { A: "Eskişehir", B: "Erzurum", C: "Kütahya", D: "Afyon" }, dogruCevap: "A" },
    { seviye: 35, kategori: "Coğrafya", soru: "Oltu taşı hangi ilimizin simgesidir?", secenekler: { A: "Erzurum", B: "Erzincan", C: "Bayburt", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 36, kategori: "Coğrafya", soru: "Türkiye'de jeotermal enerjiden elektrik üretilen ilk yer?", secenekler: { A: "Sarayköy (Denizli)", B: "Germencik (Aydın)", C: "Soma (Manisa)", D: "Yatağan (Muğla)" }, dogruCevap: "A" },
    { seviye: 37, kategori: "Coğrafya", soru: "Hangi ilimiz 'Güller Diyarı' olarak bilinir?", secenekler: { A: "Isparta", B: "Burdur", C: "Afyon", D: "Antalya" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Coğrafya", soru: "Türkiye'nin en büyük demir-çelik fabrikası hangisidir?", secenekler: { A: "Erdemir", B: "Kardemir", C: "İsdemir", D: "Asil Çelik" }, dogruCevap: "A" },
    { seviye: 39, kategori: "Coğrafya", soru: "GAP (Güneydoğu Anadolu Projesi) kapsamındaki en büyük baraj?", secenekler: { A: "Atatürk Barajı", B: "Keban Barajı", C: "Karakaya Barajı", D: "Ilısu Barajı" }, dogruCevap: "A" },
    { seviye: 40, kategori: "Coğrafya", soru: "Türkiye'de muz üretiminin yapıldığı tek bölge hangisidir?", secenekler: { A: "Ege", B: "Akdeniz", C: "Marmara", D: "Güneydoğu Anadolu" }, dogruCevap: "B" },
    { seviye: 41, kategori: "Coğrafya", soru: "Ayçiçeği üretimi en çok hangi bölgemizde yapılır?", secenekler: { A: "İç Anadolu", B: "Marmara (Trakya)", C: "Ege", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 42, kategori: "Coğrafya", soru: "Türkiye'de rüzgar enerjisi santrali (RES) ilk kez nerede kuruldu?", secenekler: { A: "İzmir (Alaçatı)", B: "Balıkesir", C: "Çanakkale", D: "Muğla" }, dogruCevap: "A" },
    { seviye: 43, kategori: "Coğrafya", soru: "Turunçgil üretimi için kış ılıklığı şarttır. Hangi ilde bu üretim zordur?", secenekler: { A: "Adana", B: "Mersin", C: "Sivas", D: "Antalya" }, dogruCevap: "C" },
    { seviye: 44, kategori: "Coğrafya", soru: "Türkiye'nin en çok ithal (satın alma) ettiği enerji kaynağı?", secenekler: { A: "Petrol ve Doğalgaz", B: "Kömür", C: "Elektrik", D: "Güneş Paneli" }, dogruCevap: "A" },
    { seviye: 45, kategori: "Coğrafya", soru: "Sığla ağacı dünyada sadece nerede bulunur?", secenekler: { A: "Muğla (Köyceğiz)", B: "Antalya (Kaş)", C: "Rize", D: "Artvin" }, dogruCevap: "A" },
    { seviye: 46, kategori: "Coğrafya", soru: "Türkiye'de en çok mısır üretimi son yıllarda hangi bölgeye kaymıştır?", secenekler: { A: "Karadeniz", B: "Güneydoğu Anadolu", C: "Marmara", D: "Ege" }, dogruCevap: "B" },
    { seviye: 47, kategori: "Coğrafya", soru: "Kümes hayvancılığı neden büyük şehirlerin yakınında gelişmiştir?", secenekler: { A: "İklim uygunluğu", B: "Tüketici nüfus (pazar)", C: "Su kaynakları", D: "Yem fabrikaları" }, dogruCevap: "B" },
    { seviye: 48, kategori: "Coğrafya", soru: "Türkiye'nin en modern ve büyük konteyner limanı hangisidir?", secenekler: { A: "İstanbul Limanı", B: "İzmir Limanı", C: "Mersin Limanı", D: "Trabzon Limanı" }, dogruCevap: "C" },
    { seviye: 49, kategori: "Coğrafya", soru: "Zeytin üretimi en çok hangi bölgede yapılır?", secenekler: { A: "Ege", B: "Marmara", C: "Akdeniz", D: "Güneydoğu Anadolu" }, dogruCevap: "A" },
    { seviye: 50, kategori: "Coğrafya", soru: "Türkiye'nin ilk nükleer güç santrali nerede inşa edilmektedir?", secenekler: { A: "Sinop", B: "Mersin (Akkuyu)", C: "Kırklareli", D: "Adana" }, dogruCevap: "B" },

    // 51-75: Türkiye Beşeri Coğrafya, İller ve Sınırlar
    { seviye: 51, kategori: "Coğrafya", soru: "Türkiye'nin nüfus bakımından en büyük ili hangisidir?", secenekler: { A: "Ankara", B: "İstanbul", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { seviye: 52, kategori: "Coğrafya", soru: "Türkiye'nin en uzun sınır komşusu hangi ülkedir?", secenekler: { A: "Irak", B: "İran", C: "Suriye", D: "Yunanistan" }, dogruCevap: "C" },
    { seviye: 53, kategori: "Coğrafya", soru: "Nahçıvan üzerinden hangi ülke ile sınırımız vardır?", secenekler: { A: "Ermenistan", B: "Azerbaycan", C: "Gürcistan", D: "İran" }, dogruCevap: "B" },
    { seviye: 54, kategori: "Coğrafya", soru: "Türkiye'de nüfus yoğunluğu en az olan ilimiz genellikle hangisidir?", secenekler: { A: "Tunceli", B: "Bayburt", C: "Ardahan", D: "Gümüşhane" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Coğrafya", soru: "Güneydoğu Anadolu'nun en gelişmiş sanayi şehri hangisidir?", secenekler: { A: "Diyarbakır", B: "Gaziantep", C: "Şanlıurfa", D: "Mardin" }, dogruCevap: "B" },
    { seviye: 56, kategori: "Coğrafya", soru: "Türkiye'de doğurganlık oranının en yüksek olduğu bölge hangisidir?", secenekler: { A: "Doğu Anadolu", B: "Güneydoğu Anadolu", C: "İç Anadolu", D: "Karadeniz" }, dogruCevap: "B" },
    { seviye: 57, kategori: "Coğrafya", soru: "Hangi ilimizin adı daha önce 'Maraş' iken değiştirilmiştir?", secenekler: { A: "Şanlıurfa", B: "Kahramanmaraş", C: "Gaziantep", D: "Afyonkarahisar" }, dogruCevap: "B" },
    { seviye: 58, kategori: "Coğrafya", soru: "Aşağıdakilerden hangisi bir sınır kapımız değildir?", secenekler: { A: "Habur", B: "Kapıkule", C: "Sarp", D: "Esenboğa" }, dogruCevap: "D" },
    { seviye: 59, kategori: "Coğrafya", soru: "Türkiye'nin en kalabalık 3. şehri hangisidir?", secenekler: { A: "Bursa", B: "İzmir", C: "Antalya", D: "Adana" }, dogruCevap: "B" },
    { seviye: 60, kategori: "Coğrafya", soru: "İpek Yolu'nun Anadolu'daki önemli duraklarından biri olan şehir?", secenekler: { A: "Erzurum", B: "Kayseri", C: "Konya", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 61, kategori: "Coğrafya", soru: "Dünyanın en eski yerleşimlerinden Çatalhöyük hangi ilimizdedir?", secenekler: { A: "Konya", B: "Çorum", C: "Aksaray", D: "Karaman" }, dogruCevap: "A" },
    { seviye: 62, kategori: "Coğrafya", soru: "Türkiye'nin kış turizminde önde gelen 'Palandöken' merkezi nerededir?", secenekler: { A: "Bursa", B: "Erzurum", C: "Kayseri", D: "Bolu" }, dogruCevap: "B" },
    { seviye: 63, kategori: "Coğrafya", soru: "Marmara ve Ege Denizi'ni birbirine bağlayan boğaz?", secenekler: { A: "İstanbul Boğazı", B: "Çanakkale Boğazı", C: "Cebelitarık Boğazı", D: "Korint Kanalı" }, dogruCevap: "B" },
    { seviye: 64, kategori: "Coğrafya", soru: "Türkiye'nin yüzölçümü en büyük ili hangisidir?", secenekler: { A: "Sivas", B: "Konya", C: "Ankara", D: "Erzurum" }, dogruCevap: "B" },
    { seviye: 65, kategori: "Coğrafya", soru: "Fındık ve Çay dışında 'Kivi' üretimiyle de öne çıkan bölgemiz?", secenekler: { A: "Karadeniz", B: "Marmara", C: "Akdeniz", D: "Ege" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Coğrafya", soru: "Karadeniz ve Akdeniz'i birbirine bağlayacak olan tünel projeleri?", secenekler: { A: "Ovit", B: "Zigana", C: "Ecevit", D: "Hepsi" }, dogruCevap: "D" },
    { seviye: 67, kategori: "Coğrafya", soru: "Türkiye'nin tek fiyord tipi kıyısı nerededir?", secenekler: { A: "Sinop (Hamsilos)", B: "Antalya (Kaş)", C: "İzmir (Foça)", D: "Muğla (Fethiye)" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Coğrafya", soru: "Göbeklitepe hangi ilimizde bulunmaktadır?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Mardin", D: "Adıyaman" }, dogruCevap: "A" },
    { seviye: 69, kategori: "Coğrafya", soru: "Mardin'in mimarisiyle meşhur eski evleri hangi taştan yapılır?", secenekler: { A: "Kalker", B: "Sarı Kalker (Mardin Taşı)", C: "Granit", D: "Mermer" }, dogruCevap: "B" },
    { seviye: 70, kategori: "Coğrafya", soru: "Türkiye'nin pirinç üretim merkezi neresidir?", secenekler: { A: "Edirne (Meriç)", B: "Samsun", C: "Sinop", D: "Kastamonu" }, dogruCevap: "A" },
    { seviye: 71, kategori: "Coğrafya", soru: "Hangi ilimizde 'Kapadokya' benzeri 'Narman Peribacaları' bulunur?", secenekler: { A: "Erzurum", B: "Nevşehir", C: "Van", D: "Manisa" }, dogruCevap: "A" },
    { seviye: 72, kategori: "Coğrafya", soru: "Türkiye'de en çok göç veren bölge hangisidir?", secenekler: { A: "Karadeniz", B: "Doğu Anadolu", C: "İç Anadolu", D: "Ege" }, dogruCevap: "B" },
    { seviye: 73, kategori: "Coğrafya", soru: "Büyükşehir statüsünde olan en son ilimiz hangisidir?", secenekler: { A: "Ordu", B: "Mardin", C: "Muğla", D: "Tekirdağ" }, dogruCevap: "A" },
    { seviye: 74, kategori: "Coğrafya", soru: "Türkiye'nin en doğusu ile en batısı arasındaki zaman farkı?", secenekler: { A: "76 Dakika", B: "40 Dakika", C: "60 Dakika", D: "90 Dakika" }, dogruCevap: "A" },
    { seviye: 75, kategori: "Coğrafya", soru: "Hangi dağımızda buzul (glasiye) oluşumlarına rastlanmaz?", secenekler: { A: "Ağrı", B: "Cilo", C: "Yıldız Dağları", D: "Kaçkar" }, dogruCevap: "C" },

    // 76-100: Dünya Coğrafyası Genel Kültür
    { seviye: 76, kategori: "Coğrafya", soru: "Dünyanın en büyük okyanusu hangisidir?", secenekler: { A: "Pasifik", B: "Atlas", C: "Hint", D: "Kuzey Buz" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Coğrafya", soru: "Dünyanın en yüksek noktası olan Everest hangi sıradağlardadır?", secenekler: { A: "Himalayalar", B: "Alpler", C: "Andlar", D: "Kayalık Dağları" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Coğrafya", soru: "Dünyanın en uzun nehri hangisidir?", secenekler: { A: "Nil", B: "Amazon", C: "Mississipi", D: "Ganj" }, dogruCevap: "A" },
    { seviye: 79, kategori: "Coğrafya", soru: "Dünyanın en geniş yüzölçümüne sahip ülkesi?", secenekler: { A: "Rusya", B: "Kanada", C: "Çin", D: "ABD" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Coğrafya", soru: "Güney Amerika'nın en büyük ülkesi hangisidir?", secenekler: { A: "Brezilya", B: "Arjantin", C: "Şili", D: "Kolombiya" }, dogruCevap: "A" },
    { seviye: 81, kategori: "Coğrafya", soru: "Afrika kıtasının en yüksek dağı hangisidir?", secenekler: { A: "Kilimanjaro", B: "Kenya Dağı", C: "Atlas Dağları", D: "Kongo Dağı" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Coğrafya", soru: "Dünyanın en derin noktası Mariana Çukuru nerededir?", secenekler: { A: "Pasifik Okyanusu", B: "Hint Okyanusu", C: "Atlas Okyanusu", D: "Akdeniz" }, dogruCevap: "A" },
    { seviye: 83, kategori: "Coğrafya", soru: "Hangi ülke 'Yükselen Güneşin Ülkesi' olarak anılır?", secenekler: { A: "Japonya", B: "Çin", C: "Güney Kore", D: "Tayland" }, dogruCevap: "A" },
    { seviye: 84, kategori: "Coğrafya", soru: "Dünyanın en büyük çölü hangisidir?", secenekler: { A: "Sahra Çölü", B: "Gobi Çölü", C: "Kalahari", D: "Atacama" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Coğrafya", soru: "Fransa ve İngiltere'yi deniz altından bağlayan tünel?", secenekler: { A: "Manş Tüneli", B: "Bering Tüneli", C: "Cebelitarık", D: "Süveyş" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Coğrafya", soru: "Hangi kanal Akdeniz ile Kızıldeniz'i birbirine bağlar?", secenekler: { A: "Süveyş Kanalı", B: "Panama Kanalı", C: "Kanal İstanbul", D: "Korint Kanalı" }, dogruCevap: "A" },
    { seviye: 87, kategori: "Coğrafya", soru: "Dünyanın en kalabalık ülkesi (2024 verilerine göre)?", secenekler: { A: "Hindistan", B: "Çin", C: "ABD", D: "Endonezya" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Coğrafya", soru: "Kanguruları ile ünlü olan kıta ülke?", secenekler: { A: "Avustralya", B: "Afrika", C: "Asya", D: "Antarktika" }, dogruCevap: "A" },
    { seviye: 90, kategori: "Coğrafya", soru: "Hangi ülke hem Asya hem Avrupa kıtasında yer alır?", secenekler: { A: "Türkiye ve Rusya", B: "Çin", C: "Hindistan", D: "Almanya" }, dogruCevap: "A" },
    { seviye: 91, kategori: "Coğrafya", soru: "Dünyanın en küçük yüzölçümlü ülkesi?", secenekler: { A: "Vatikan", B: "Monako", C: "San Marino", D: "Andorra" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Coğrafya", soru: "İskandinav ülkeleri hangi kıtadadır?", secenekler: { A: "Avrupa", B: "Asya", C: "Amerika", D: "Afrika" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Coğrafya", soru: "Amazon yağmur ormanları hangi kıtadadır?", secenekler: { A: "Güney Amerika", B: "Kuzey Amerika", C: "Afrika", D: "Asya" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Coğrafya", soru: "İzlanda'da çok sayıda bulunan jeotermal oluşum?", secenekler: { A: "Gayzer", B: "Fiyord", C: "Obruk", D: "Delta" }, dogruCevap: "A" },
    { seviye: 95, kategori: "Coğrafya", soru: "Dünyanın en soğuk kıtası hangisidir?", secenekler: { A: "Antarktika", B: "Asya (Sibirya)", C: "Kuzey Amerika", D: "Avrupa" }, dogruCevap: "A" },
    { seviye: 96, kategori: "Coğrafya", soru: "Dünyanın en büyük tatlı su gölü hangisidir?", secenekler: { A: "Superior Gölü", B: "Hazar Denizi", C: "Baykal Gölü", D: "Victoria Gölü" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Coğrafya", soru: "Hangi ülke topraklarında hiç nehir bulunmaz?", secenekler: { A: "Suudi Arabistan", B: "Mısır", C: "Irak", D: "Libya" }, dogruCevap: "A" },
    { seviye: 98, kategori: "Coğrafya", soru: "Ekvator çizgisinin geçtiği ülkelerden biri?", secenekler: { A: "Ekvador", B: "Meksika", C: "Arjantin", D: "Kanada" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Coğrafya", soru: "Ganj Nehri hangi ülke için kutsal sayılır?", secenekler: { A: "Hindistan", B: "Çin", C: "Pakistan", D: "Mısır" }, dogruCevap: "A" },
    { seviye: 100, kategori: "Coğrafya", soru: "Dünya'nın kendi ekseni etrafında dönme hızı nerede en fazladır?", secenekler: { A: "Ekvator", B: "Kutuplar", C: "Yengeç Dönencesi", D: "Oğlak Dönencesi" }, dogruCevap: "A" }, 
    // 101-151: Dünya Coğrafyası, İklimler, Ülkeler ve Ekstrem Olaylar
    { seviye: 101, kategori: "Coğrafya", soru: "Dünyanın en derin noktası olan Mariana Çukuru hangi okyanustadır?", secenekler: { A: "Atlas Okyanusu", B: "Hint Okyanusu", C: "Büyük Okyanus (Pasifik)", D: "Arktik Okyanusu" }, dogruCevap: "C" },
    { seviye: 102, kategori: "Coğrafya", soru: "Yüzölçümü bakımından dünyanın en büyük ülkesi hangisidir?", secenekler: { A: "Kanada", B: "Çin", C: "ABD", D: "Rusya" }, dogruCevap: "D" },
    { seviye: 103, kategori: "Coğrafya", soru: "Yeryüzünde en çok yağış alan yer olarak bilinen Çerapunçi hangi ülkededir?", secenekler: { A: "Brezilya", B: "Hindistan", C: "Endonezya", D: "Kongo" }, dogruCevap: "B" },
    { seviye: 104, kategori: "Coğrafya", soru: "Dünyanın en uzun sıradağı hangisidir?", secenekler: { A: "Alpler", B: "Himalayalar", C: "And Dağları", D: "Kayalık Dağları" }, dogruCevap: "C" },
    { seviye: 105, kategori: "Coğrafya", soru: "İskandinav ülkelerinde buzulların aşındırmasıyla oluşan derin vadilere ne ad verilir?", secenekler: { A: "Kanyon", B: "Fiyort", C: "Obruk", D: "Delta" }, dogruCevap: "B" },
    { seviye: 106, kategori: "Coğrafya", soru: "Yüzölçümü en küçük olan kıta hangisidir?", secenekler: { A: "Avrupa", B: "Okyanusya (Avustralya)", C: "Antarktika", D: "Güney Amerika" }, dogruCevap: "B" },
    { seviye: 107, kategori: "Coğrafya", soru: "Dünyanın en büyük sıcak çölü hangisidir?", secenekler: { A: "Gobi Çölü", B: "Sahra Çölü", C: "Atacama Çölü", D: "Kalahari Çölü" }, dogruCevap: "B" },
    { seviye: 108, kategori: "Coğrafya", soru: "Süveyş Kanalı hangi iki denizi birbirine bağlar?", secenekler: { A: "Akdeniz - Kızıldeniz", B: "Akdeniz - Karadeniz", C: "Hazar Denizi - Karadeniz", D: "Umman Denizi - Kızıldeniz" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Coğrafya", soru: "Dünyanın en yüksek şelalesi olan Angel Şelalesi hangi ülkededir?", secenekler: { A: "Brezilya", B: "Venezuela", C: "ABD", D: "Zambiya" }, dogruCevap: "B" },
    { seviye: 110, kategori: "Coğrafya", soru: "Dünyanın kendi ekseni etrafındaki dönüş hızı (çizgisel hız) nerede en fazladır?", secenekler: { A: "Kuzey Kutbu", B: "Ekvator", C: "Yengeç Dönencesi", D: "Güney Kutbu" }, dogruCevap: "B" },
    { seviye: 111, kategori: "Coğrafya", soru: "Haritalarda yükseltiyi göstermek için kullanılan, aynı yükseltiye sahip noktaları birleştiren eğrilere ne denir?", secenekler: { A: "İzobar", B: "İzoterm", C: "İzohips", D: "İzobat" }, dogruCevap: "C" },
    { seviye: 112, kategori: "Coğrafya", soru: "Atmosferin en alt ve hava olaylarının yaşandığı katmanı hangisidir?", secenekler: { A: "Stratosfer", B: "Mezosfer", C: "Troposfer", D: "Termosfer" }, dogruCevap: "C" },
    { seviye: 113, kategori: "Coğrafya", soru: "Akdeniz ikliminin karakteristik bitki örtüsü hangisidir?", secenekler: { A: "Bozkır", B: "Maki", C: "Tundra", D: "Savann" }, dogruCevap: "B" },
    { seviye: 114, kategori: "Coğrafya", soru: "Depremin büyüklüğünü ölçmek için kullanılan ölçeğin adı nedir?", secenekler: { A: "Fahrenheit", B: "Richter", C: "Barometre", D: "Anemometre" }, dogruCevap: "B" },
    { seviye: 115, kategori: "Coğrafya", soru: "Sıcaklık ve nemin yıl boyunca yüksek olduğu, her mevsimin yağışlı geçtiği iklim?", secenekler: { A: "Muson İklimi", B: "Çöl İklimi", C: "Ekvatoral İklim", D: "Savan İklimi" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Coğrafya", soru: "Hangi ülke 'Yükselen Güneşin Ülkesi' olarak bilinir?", secenekler: { A: "Çin", B: "Güney Kore", C: "Japonya", D: "Tayland" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Coğrafya", soru: "Dünyanın en yoğun nüfuslu kıtası hangisidir?", secenekler: { A: "Avrupa", B: "Afrika", C: "Asya", D: "Kuzey Amerika" }, dogruCevap: "C" },
    { seviye: 118, kategori: "Coğrafya", soru: "Bering Boğazı hangi iki kıtayı birbirine en çok yaklaştırır?", secenekler: { A: "Asya - Avrupa", B: "Asya - Kuzey Amerika", C: "Afrika - Avrupa", D: "Güney Amerika - Antarktika" }, dogruCevap: "B" },
    { seviye: 119, kategori: "Coğrafya", soru: "Yeryüzündeki tatlı su rezervlerinin en büyük kısmı nerede bulunur?", secenekler: { A: "Göller", B: "Yeraltı suları", C: "Buzullar", D: "Nehirler" }, dogruCevap: "C" },
    { seviye: 120, kategori: "Coğrafya", soru: "Arap Yarımadası ile Afrika arasında yer alan deniz hangisidir?", secenekler: { A: "Umman Denizi", B: "Kızıldeniz", C: "Basra Körfezi", D: "Aden Körfezi" }, dogruCevap: "B" },
    { seviye: 121, kategori: "Coğrafya", soru: "Dünya üzerindeki bir noktanın Ekvator'a olan uzaklığının açı cinsinden değerine ne denir?", secenekler: { A: "Boylam", B: "Enlem", C: "Yerel Saat", D: "Yörünge" }, dogruCevap: "B" },
    { seviye: 122, kategori: "Coğrafya", soru: "Hangi okyanusun kıyısı 'Pasifik Ateş Çemberi' olarak adlandırılan yoğun volkanik bölgedir?", secenekler: { A: "Atlas Okyanusu", B: "Hint Okyanusu", C: "Büyük Okyanus", D: "Güney Okyanusu" }, dogruCevap: "C" },
    { seviye: 123, kategori: "Coğrafya", soru: "İsviçre, Avusturya ve Fransa boyunca uzanan Avrupa'nın en büyük sıradağ sistemi?", secenekler: { A: "Pireneler", B: "Alpler", C: "Karpatlar", D: "Ural Dağları" }, dogruCevap: "B" },
    { seviye: 124, kategori: "Coğrafya", soru: "Dünyanın en kalabalık Müslüman nüfusuna sahip ülkesi hangisidir?", secenekler: { A: "Suudi Arabistan", B: "Mısır", C: "Endonezya", D: "Pakistan" }, dogruCevap: "C" },
    { seviye: 125, kategori: "Coğrafya", soru: "Amazon Nehri hangi okyanusa dökülür?", secenekler: { A: "Pasifik Okyanusu", B: "Atlas Okyanusu (Atlantik)", C: "Hint Okyanusu", D: "Arktik Okyanusu" }, dogruCevap: "B" },
    { seviye: 126, kategori: "Coğrafya", soru: "Kuzey ve Güney yarım küreleri birbirinden ayıran hayali çizgiye ne denir?", secenekler: { A: "Başlangıç Meridyeni", B: "Ekvator", C: "Oğlak Dönencesi", D: "Kutup Dairesi" }, dogruCevap: "B" },
    { seviye: 127, kategori: "Coğrafya", soru: "Atlas Okyanusu ile Büyük Okyanus'u birbirine bağlayan yapay kanal hangisidir?", secenekler: { A: "Süveyş Kanalı", B: "Panama Kanalı", C: "Kiel Kanalı", D: "Korint Kanalı" }, dogruCevap: "B" },
    { seviye: 128, kategori: "Coğrafya", soru: "Avrupa ve Afrika kıtalarını birbirine en çok yaklaştıran boğaz hangisidir?", secenekler: { A: "Cebelitarık Boğazı", B: "Hürmüz Boğazı", C: "Malakka Boğazı", D: "Babülmendep Boğazı" }, dogruCevap: "A" },
    { seviye: 129, kategori: "Coğrafya", soru: "Dünyanın en tuzlu denizi hangisidir?", secenekler: { A: "Akdeniz", B: "Kızıldeniz", C: "Manş Denizi", D: "Umman Denizi" }, dogruCevap: "B" },
    { seviye: 130, kategori: "Coğrafya", soru: "Güneydoğu Asya'da yaz aylarında bol yağış getiren rüzgarlara ne denir?", secenekler: { A: "Alizeler", B: "Batı Rüzgarları", C: "Muson Rüzgarları", D: "Fön Rüzgarları" }, dogruCevap: "C" },
    { seviye: 131, kategori: "Coğrafya", soru: "Dünyanın en büyük adası hangisidir?", secenekler: { A: "Madagaskar", B: "Grönland", C: "Borneo", D: "Yeni Gine" }, dogruCevap: "B" },
    { seviye: 132, kategori: "Coğrafya", soru: "Nüfus sayımını ve nüfusun özelliklerini inceleyen bilim dalı hangisidir?", secenekler: { A: "Jeoloji", B: "Demografi", C: "Kartografya", D: "Litoloji" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Coğrafya", soru: "Avrupa'nın en uzun nehri hangisidir?", secenekler: { A: "Tuna", B: "Ren", C: "Volga", D: "Elbe" }, dogruCevap: "C" },
    { seviye: 134, kategori: "Coğrafya", soru: "Magmanın yeryüzüne çıktığı noktada oluşturduğu çukurluğa ne ad verilir?", secenekler: { A: "Mağara", B: "Krater", C: "Polye", D: "Lapyalar" }, dogruCevap: "B" },
    { seviye: 135, kategori: "Coğrafya", soru: "Kireç taşlarının (kalker) su ile erimesi sonucu oluşan yer şekillerine ne denir?", secenekler: { A: "Volkanik", B: "Karstik", C: "Buzul", D: "Rüzgar aşınımı" }, dogruCevap: "B" },
    { seviye: 136, kategori: "Coğrafya", soru: "Avustralya kıtasının en tanınmış yerli halkına ne ad verilir?", secenekler: { A: "İnka", B: "Aztek", C: "Aborjin", D: "Maori" }, dogruCevap: "C" },
    { seviye: 137, kategori: "Coğrafya", soru: "Hangi ülke toprakları üzerinde en çok zaman dilimi (saat farkı) barındırır?", secenekler: { A: "Çin", B: "Rusya", C: "Fransa (deniz aşırı toprakları dahil)", D: "ABD" }, dogruCevap: "C" },
    { seviye: 138, kategori: "Coğrafya", soru: "Kalıcı kar sınırının en yüksek olduğu bölge neresidir?", secenekler: { A: "Kutuplar", B: "Orta Kuşak", C: "Ekvator", D: "Dönenceler" }, dogruCevap: "C" },
    { seviye: 139, kategori: "Coğrafya", soru: "Kuzey ışıkları olarak da bilinen doğa olayının bilimsel adı nedir?", secenekler: { A: "Sirocco", B: "Aurora Borealis", C: "Tsunami", D: "Hortum" }, dogruCevap: "B" },
    { seviye: 140, kategori: "Coğrafya", soru: "Hangi kıtada aktif volkan bulunmaz?", secenekler: { A: "Antarktika", B: "Avustralya", C: "Avrupa", D: "Afrika" }, dogruCevap: "B" },
    { seviye: 141, kategori: "Coğrafya", soru: "Gel-git (med-cezir) olayının temel sebebi hangisidir?", secenekler: { A: "Rüzgarlar", B: "Ay'ın çekim gücü", C: "Okyanus akıntıları", D: "Dünyanın iç ısısı" }, dogruCevap: "B" },
    { seviye: 142, kategori: "Coğrafya", soru: "Yeryüzünde sıcaklık değerleri en düşük olan yerleşim birimleri hangi ülkededir?", secenekler: { A: "Kanada", B: "Rusya", C: "Norveç", D: "İzlanda" }, dogruCevap: "B" },
    { seviye: 143, kategori: "Coğrafya", soru: "Asya ile Avrupa'yı birbirinden ayıran doğal sınır kabul edilen dağlar?", secenekler: { A: "Ural Dağları", B: "Kafkas Dağları", C: "Toroslar", D: "Himalayalar" }, dogruCevap: "A" },
    { seviye: 144, kategori: "Coğrafya", soru: "Dünyanın en büyük mercan resifi sistemi hangi ülkenin kıyısındadır?", secenekler: { A: "Endonezya", B: "Avustralya", C: "Meksika", D: "Maldivler" }, dogruCevap: "B" },
    { seviye: 145, kategori: "Coğrafya", soru: "Deniz seviyesindeki atmosfer basıncı ortalama kaç milibardır?", secenekler: { A: "1000", B: "1013", C: "1025", D: "980" }, dogruCevap: "B" },
    { seviye: 146, kategori: "Coğrafya", soru: "Peri bacalarının oluşumunda iç kuvvetlerden hangisi etkilidir?", secenekler: { A: "Deprem", B: "Volkanizma", C: "Orojenez", D: "Epirojenez" }, dogruCevap: "B" },
    { seviye: 147, kategori: "Coğrafya", soru: "Dünyanın en küçük bağımsız devleti hangisidir?", secenekler: { A: "Monako", B: "Vatikan", C: "San Marino", D: "Liechtenstein" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Coğrafya", soru: "Hangi rüzgar türü estiği yamaçta sıcaklığı artırarak kar erimelerine neden olur?", secenekler: { A: "Meltem", B: "Fön", C: "Mistral", D: "Poyraz" }, dogruCevap: "B" },
    { seviye: 149, kategori: "Coğrafya", soru: "Nil Nehri hangi denize dökülür?", secenekler: { A: "Kızıldeniz", B: "Akdeniz", C: "Hint Okyanusu", D: "Basra Körfezi" }, dogruCevap: "B" },
    { seviye: 150, kategori: "Coğrafya", soru: "Atmosferdeki ozon tabakasının temel görevi nedir?", secenekler: { A: "Yağışı başlatmak", B: "Zararlı güneş ışınlarını tutmak", C: "Sıcaklığı iletmek", D: "Oksijen üretmek" }, dogruCevap: "B" },
    { seviye: 151, kategori: "Coğrafya", soru: "Güney Yarım Küre'de en uzun gündüzün yaşandığı tarih hangisidir?", secenekler: { A: "21 Haziran", B: "21 Aralık", C: "21 Mart", D: "23 Eylül" }, dogruCevap: "B" }
 
);
 