// Eğer dizi yoksa oluştur, varsa içine ekle
window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-20: İslamiyet Öncesi ve Geçiş Dönemi
    { kategori: "Edebiyat", seviye: 1, soru: "Türk edebiyatının ilk yazılı belgesi kabul edilen eser hangisidir?", secenekler: { A: "Orhun Abideleri", B: "Yenisey Yazıtları", C: "Kutadgu Bilig", D: "Divanü Lügati't-Türk" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 2, soru: "Türk İslam edebiyatının ilk mesnevisi ve ilk siyasetnamesi hangisidir?", secenekler: { A: "Atabetü'l Hakayık", B: "Divan-ı Hikmet", C: "Kutadgu Bilig", D: "Dede Korkut" }, dogruCevap: "C" },
    { kategori: "Edebiyat", seviye: 3, soru: "Kaşgarlı Mahmut tarafından yazılan ilk Türk dünyası sözlüğü hangisidir?", secenekler: { A: "Divanü Lügati't-Türk", B: "Muhakemetü'l-Lügateyn", C: "Kamusu Türki", D: "Lehçe-i Osmani" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 4, soru: "Edip Ahmet Yükneki tarafından yazılan 'hakikatlerin eşiği' anlamına gelen eser?", secenekler: { A: "Atabetü'l Hakayık", B: "Divan-ı Hikmet", C: "Kutadgu Bilig", D: "Mesnevi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 5, soru: "İlk tasavvuf şairi kabul edilen ve 'Hikmet'leri ile tanınan bilgin kimdir?", secenekler: { A: "Ahmet Yesevi", B: "Mevlana", C: "Yunus Emre", D: "Hacı Bektaş Veli" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 6, soru: "Destan döneminden halk hikayeciliğine geçişin ilk örneği kabul edilen eser?", secenekler: { A: "Dede Korkut Hikayeleri", B: "Kerem ile Aslı", C: "Leyla ile Mecnun", D: "Manas Destanı" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 7, soru: "Dünyanın en uzun destanı olarak bilinen Kırgız destanı hangisidir?", secenekler: { A: "Manas", B: "Alp Er Tunga", C: "Türeyiş", D: "Göç" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 8, soru: "Sav, Sagu, Koşuk türlerine hangi dönem Türk edebiyatında rastlanır?", secenekler: { A: "İslamiyet Öncesi", B: "Halk Edebiyatı", C: "Divan Edebiyatı", D: "Tanzimat" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 9, soru: "Ölen bir kişinin ardından duyulan acıyı dile getiren İslamiyet öncesi şiir türü?", secenekler: { A: "Sagu", B: "Sav", C: "Koşuk", D: "Ağıt" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 10, soru: "Günümüzdeki atasözlerinin İslamiyet öncesindeki karşılığı nedir?", secenekler: { A: "Sav", B: "Sagu", C: "Koşuk", D: "Destan" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 11, soru: "Divanü Lügati't-Türk'te yer alan ilk Türk dünyası haritası kime aittir?", secenekler: { A: "Kaşgarlı Mahmut", B: "İdrisi", C: "Piri Reis", D: "Katip Çelebi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 12, soru: "Kutadgu Bilig'de adaleti temsil eden hükümdar karakteri hangisidir?", secenekler: { A: "Kün Togdı", B: "Ay Toldı", C: "Ögdülmiş", D: "Odgurmış" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 13, soru: "Sözlü dönemde şiirleri 'kopuz' eşliğinde söyleyen kişilere ne denirdi?", secenekler: { A: "Kam/Baksı", B: "Aşık", C: "Ozan", D: "Hepsi" }, dogruCevap: "D" },
    { kategori: "Edebiyat", seviye: 14, soru: "Uygur dönemine ait olan ve Budizm'i anlatan eser hangisidir?", secenekler: { A: "Altun Yaruk", B: "Orhun Yazıtları", C: "Kutadgu Bilig", D: "Divan-ı Hikmet" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 15, soru: "İslamiyet öncesi Türk şiirinde kullanılan temel ölçü hangisidir?", secenekler: { A: "Hece Ölçüsü", B: "Aruz Ölçüsü", C: "Serbest Ölçü", D: "Müstezat" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 16, soru: "Dede Korkut Hikayeleri kaç hikaye ve bir önsözden oluşur?", secenekler: { A: "12", B: "10", C: "15", D: "20" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 17, soru: "Divan-ı Hikmet hangi dilde yazılmıştır?", secenekler: { A: "Hakaniye Türkçesi", B: "Osmanlıca", C: "Farsça", D: "Arapça" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 18, soru: "Aşk, doğa ve kahramanlık konularını işleyen sözlü dönem şiiri?", secenekler: { A: "Koşuk", B: "Sagu", C: "Sav", D: "Mani" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 19, soru: "Göktürk Kitabeleri'nde hitabet türünün ilk örneğini veren kimdir?", secenekler: { A: "Bilge Kağan", B: "Kül Tigin", C: "Tonyukuk", D: "Bumin Kağan" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 20, soru: "Yolluğ Tigin tarafından yazılan ilk Türk anı türü eseri hangisidir?", secenekler: { A: "Orhun Abideleri", B: "Babürname", C: "Şecere-i Terakime", D: "Siyasetname" }, dogruCevap: "A" },

    // 21-40: Halk Edebiyatı ve Tasavvuf
    { kategori: "Edebiyat", seviye: 21, soru: "Halk edebiyatında en kısa nazım biçimi hangisidir?", secenekler: { A: "Mani", B: "Koşma", C: "Semai", D: "Varsağı" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 22, soru: "İlahi türünün Türk edebiyatındaki en büyük temsilcisi kimdir?", secenekler: { A: "Yunus Emre", B: "Mevlana", C: "Hacı Bayram Veli", D: "Eşrefoğlu Rumi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 23, soru: "Güzellemeleriyle tanınan, Toroslar'da yaşamış ünlü halk şairi kimdir?", secenekler: { A: "Karacaoğlan", B: "Dadaloğlu", C: "Köroğlu", D: "Aşık Veysel" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 24, soru: "'Benden selam olsun Bolu Beyi'ne' dizeleriyle ünlü şair kimdir?", secenekler: { A: "Köroğlu", B: "Dadaloğlu", C: "Pir Sultan Abdal", D: "Kayıkçı Kul Mustafa" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 25, soru: "'Ferman padişahın dağlar bizimdir' diyen Türkmen şairi kimdir?", secenekler: { A: "Dadaloğlu", B: "Karacaoğlan", C: "Seyrani", D: "Dertli" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 26, soru: "20. yüzyılın en büyük halk ozanı, 'Uzun İnce Bir Yoldayım'ın sahibi kimdir?", secenekler: { A: "Aşık Veysel", B: "Neşet Ertaş", C: "Mahzuni Şerif", D: "Abdurrahim Karakoç" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 27, soru: "Taşlamalarıyla ünlü, Kayserili halk şairi kimdir?", secenekler: { A: "Seyrani", B: "Gevheri", C: "Zihni", D: "Sümmani" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 28, soru: "'Makalat' adlı eser kime aittir?", secenekler: { A: "Hacı Bektaş Veli", B: "Hacı Bayram Veli", C: "Yunus Emre", D: "Mevlana" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 29, soru: "Genç Osman Destanı hangi halk şairine aittir?", secenekler: { A: "Kayıkçı Kul Mustafa", B: "Levni", C: "Aşık Ömer", D: "Karacaoğlan" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 30, soru: "Koşma nazım biçiminin hece sayısı genellikle kaçtır?", secenekler: { A: "11", B: "8", C: "7", D: "14" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 31, soru: "Tasavvufta Allah'tan gelip tekrar Allah'a dönmeyi anlatan tür?", secenekler: { A: "Devriye", B: "Nutuk", C: "Şathiye", D: "Münacat" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 32, soru: "Dini inançlarla şakacı bir dille alay eder gibi yazılan şiir türü?", secenekler: { A: "Şathiye", B: "Nutuk", C: "Devriye", D: "İlahi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 33, soru: "Semai nazım biçimi kaçlı hece ölçüsüyle yazılır?", secenekler: { A: "8", B: "11", C: "7", D: "10" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 34, soru: "Varsağı türünün en belirgin özelliği olan ünlem hangisidir?", secenekler: { A: "Bre / Behey", B: "Aman", C: "Eyvah", D: "Medet" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 35, soru: "Halk edebiyatında şairlerin şiirlerinin toplandığı defterlere ne denir?", secenekler: { A: "Cönk", B: "Divan", C: "Mecmua", D: "Tezkire" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 36, soru: "Risaletü'n Nushiyye (Nasihatler Kitabı) kime aittir?", secenekler: { A: "Yunus Emre", B: "Mevlana", C: "Kaygusuz Abdal", D: "Pir Sultan" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 37, soru: "Budalaname ve Muganniname eserleri kime aittir?", secenekler: { A: "Kaygusuz Abdal", B: "Eşrefoğlu Rumi", C: "Kazak Abdal", D: "Niyazi Mısri" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 38, soru: "Hangi şairimiz sadece hece ölçüsünü kullanmıştır?", secenekler: { A: "Karacaoğlan", B: "Aşık Ömer", C: "Gevheri", D: "Bayburtlu Zihni" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 39, soru: "Modern halk şiirinin temsilcisi olan 'Bozkırın Tezenesi' kimdir?", secenekler: { A: "Neşet Ertaş", B: "Aşık Veysel", C: "Mahzuni Şerif", D: "Ali İzzet Özkan" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 40, soru: "Koşmanın türlerinden 'Güzelleme'nin en büyük ustası kimdir?", secenekler: { A: "Karacaoğlan", B: "Köroğlu", C: "Dadaloğlu", D: "Seyrani" }, dogruCevap: "A" },

    // 41-60: Divan Edebiyatı
    { kategori: "Edebiyat", seviye: 41, soru: "Aşk ve ıstırap şairi olarak bilinen Fuzuli hangi yüzyılda yaşamıştır?", secenekler: { A: "16. Yüzyıl", B: "15. Yüzyıl", C: "17. Yüzyıl", D: "14. Yüzyıl" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 42, soru: "Şairler Sultanı (Sultanü'ş Şuara) olarak bilinen 16. yy şairi?", secenekler: { A: "Baki", B: "Fuzuli", C: "Nedim", D: "Nabi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 43, soru: "Lale Devri şairi olarak bilinen, şarkı türünün ustası kimdir?", secenekler: { A: "Nedim", B: "Naili", C: "Neşati", D: "Şeyh Galip" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 44, soru: "Divan edebiyatında hikemi (didaktik) şiirin öncüsü kimdir?", secenekler: { A: "Nabi", B: "Nef'i", C: "Baki", D: "Fuzuli" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 45, soru: "Övgü ve yergi şairi olarak bilinen, 'Siham-ı Kaza'nın yazarı?", secenekler: { A: "Nef'i", B: "Nedim", C: "Naili", D: "Fuzuli" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 46, soru: "Divan edebiyatının son büyük şairi kabul edilen 'Hüsn ü Aşk' yazarı?", secenekler: { A: "Şeyh Galip", B: "Zati", C: "Hayali", D: "Nabi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 47, soru: "Türk edebiyatındaki ilk fabl örneği kabul edilen 'Harname' kime aittir?", secenekler: { A: "Şeyhi", B: "Ahmedi", C: "Necati", D: "Kadı Burhaneddin" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 48, soru: "Mevlid olarak bilinen 'Vesiletü'n Necat'ın yazarı kimdir?", secenekler: { A: "Süleyman Çelebi", B: "Ahmedi", C: "Sinan Paşa", D: "Mercimek Ahmed" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 49, soru: "Divan edebiyatında 'gazel' türünün beyit sayısı genellikle kaçtır?", secenekler: { A: "5-15", B: "33-99", C: "2", D: "10-20" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 50, soru: "Divan edebiyatında beyitler arası konu birliği olmasına ne denir?", secenekler: { A: "Yek-ahenk", B: "Yek-avaz", C: "Musammat", D: "Müstezat" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 51, soru: "Fuzuli'nin Hz. Muhammed'e duyduğu sevgiyi anlattığı kaside?", secenekler: { A: "Su Kasidesi", B: "Güneş Kasidesi", C: "Kerem Kasidesi", D: "Tazarru-name" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 52, soru: "İlk şairler tezkiresi (biyografi) olan 'Mecalisü'n Nefais' yazarı?", secenekler: { A: "Ali Şir Nevai", B: "Sehi Bey", C: "Latifi", D: "Ahmedi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 53, soru: "Divan edebiyatında mahlasın geçtiği son beyte ne denir?", secenekler: { A: "Taç Beyit", B: "Şah Beyit", C: "Matla", D: "Makta" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 54, soru: "Mesnevi türünde ilk beş esere sahip olana ne unvan verilir?", secenekler: { A: "Hamse Sahibi", B: "Mürettep Divan", C: "Sultanü'ş Şuara", D: "Reisü'l Hattatin" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 55, soru: "Divan şiirini Türkçeleştiren, 'Mahallileşme' akımının öncüsü?", secenekler: { A: "Nedim", B: "Baki", C: "Nabi", D: "Nef'i" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 56, soru: "Sebk-i Hindi (Hint Üslubu) akımının en önemli temsilcisi?", secenekler: { A: "Şeyh Galip", B: "Fuzuli", C: "Nedim", D: "Nabi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 57, soru: "Şikayetname adlı ilk edebi mektup kime aittir?", secenekler: { A: "Fuzuli", B: "Baki", C: "Zati", D: "Şeyhi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 58, soru: "Türkçenin Farsçadan üstün olduğunu savunan 'Muhakemetü'l-Lügateyn' yazarı?", secenekler: { A: "Ali Şir Nevai", B: "Kaşgarlı Mahmut", C: "Babür Şah", D: "Ahmedi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 59, soru: "Kanuni Sultan Süleyman için 'Kanuni Mersiyesi'ni kim yazmıştır?", secenekler: { A: "Baki", B: "Fuzuli", C: "Zati", D: "Hayali" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 60, soru: "Edebiyatımızdaki ilk gezi yazısı örneği 'Mir'atü'l Memalik' yazarı?", secenekler: { A: "Seydi Ali Reis", B: "Piri Reis", C: "Evliya Çelebi", D: "Katip Çelebi" }, dogruCevap: "A" },

    // 61-80: Tanzimat ve Servet-i Fünun
    { kategori: "Edebiyat", seviye: 61, soru: "Vatan Şairi olarak bilinen Namık Kemal hangi dönem sanatçısıdır?", secenekler: { A: "Tanzimat 1. Dönem", B: "Tanzimat 2. Dönem", C: "Milli Edebiyat", D: "Cumhuriyet" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 62, soru: "İlk yerli tiyatro eseri 'Şair Evlenmesi' kime aittir?", secenekler: { A: "Şinasi", B: "Ziya Paşa", C: "Namık Kemal", D: "Ahmet Vefik Paşa" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 63, soru: "İlk psikolojik roman olan 'Eylül'ün yazarı kimdir?", secenekler: { A: "Mehmet Rauf", B: "Halit Ziya", C: "Cenap Şahabettin", D: "Tevfik Fikret" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 64, soru: "'Mai ve Siyah' ile 'Aşk-ı Memnu' romanlarının yazarı kimdir?", secenekler: { A: "Halit Ziya Uşaklıgil", B: "Mehmet Rauf", C: "Ahmet Hikmet", D: "Hüseyin Cahit" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 65, soru: "Servet-i Fünun döneminin en büyük şairi, 'Aşiyan' sahibi kimdir?", secenekler: { A: "Tevfik Fikret", B: "Cenap Şahabettin", C: "Ahmet Haşim", D: "Yahya Kemal" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 66, soru: "'Tezatlar şairi' olarak bilinen 'Makber'in yazarı kimdir?", secenekler: { A: "Abdülhak Hamit Tarhan", B: "Recaizade Mahmut", C: "Muallim Naci", D: "Nabizade Nazım" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 67, soru: "Türk edebiyatındaki ilk köy romanı 'Karabibik' kime aittir?", secenekler: { A: "Nabizade Nazım", B: "Sami Paşazade Sezai", C: "Mizancı Murad", D: "Muallim Naci" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 68, soru: "İlk yerli roman 'Taaşşuk-ı Talat ve Fitnat'ın yazarı kimdir?", secenekler: { A: "Şemsettin Sami", B: "Ahmet Mithat", C: "Namık Kemal", D: "Şinasi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 69, soru: "Hangi şairimiz 'Sanat toplum içindir' anlayışını savunur?", secenekler: { A: "Namık Kemal", B: "Cenap Şahabettin", C: "Tevfik Fikret", D: "Ahmet Haşim" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 70, soru: "Servet-i Fünun edebiyatı hangi dergi etrafında toplanmıştır?", secenekler: { A: "Servet-i Fünun", B: "Tercüman-ı Ahval", C: "Genç Kalemler", D: "Yaprak" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 71, soru: "Edebiyatımızda 'Yazı Makinesi' olarak bilinen üretken yazar?", secenekler: { A: "Ahmet Mithat Efendi", B: "Namık Kemal", C: "Ömer Seyfettin", D: "Hüseyin Rahmi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 72, soru: "Sahnelenen ilk tiyatro eseri 'Vatan Yahut Silistre' yazarı?", secenekler: { A: "Namık Kemal", B: "Şinasi", C: "Ziya Paşa", D: "Ahmet Vefik Paşa" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 73, soru: "İlk realist roman 'Araba Sevdası' kime aittir?", secenekler: { A: "Recaizade Mahmut Ekrem", B: "Sami Paşazade", C: "Halit Ziya", D: "Mehmet Rauf" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 74, soru: "Servet-i Fünun'da sembolizm ve parnasizmin temsilcisi şair?", secenekler: { A: "Cenap Şahabettin", B: "Tevfik Fikret", C: "Süleyman Nazif", D: "Faik Ali" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 75, soru: "Şiirlerini 'Tamat' adlı kitapta toplayan sanatçı?", secenekler: { A: "Cenap Şahabettin", B: "Tevfik Fikret", C: "Ahmet Haşim", D: "Yahya Kemal" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 76, soru: "Ziya Paşa'nın Divan edebiyatını eleştirdiği makalesi hangisidir?", secenekler: { A: "Şiir ve İnşa", B: "Harabat", C: "Demdeme", D: "Zemzeme" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 77, soru: "Dili en ağır, en sanatlı olan edebi dönem hangisidir?", secenekler: { A: "Servet-i Fünun", B: "Tanzimat 1", C: "Milli Edebiyat", D: "Cumhuriyet" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 78, soru: "Tevfik Fikret'in çocuklar için yazdığı hece ölçülü kitabı?", secenekler: { A: "Şermin", B: "Haluk'un Defteri", C: "Rübab-ı Şikeste", D: "Tarih-i Kadim" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 79, soru: "İlk edebi roman 'İntibah' kime aittir?", secenekler: { A: "Namık Kemal", B: "Ahmet Mithat", C: "Şemsettin Sami", D: "Recaizade Mahmut" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 80, soru: "Fecr-i Ati topluluğunun en önemli şairi kimdir?", secenekler: { A: "Ahmet Haşim", B: "Emin Bülent", C: "Tahsin Nahit", D: "Yakup Kadri" }, dogruCevap: "A" },

    // 81-100: Milli Edebiyat ve Cumhuriyet
    { kategori: "Edebiyat", seviye: 81, soru: "'Yeni Lisan' makalesiyle dilde sadeleşmeyi başlatan isimlerden biri?", secenekler: { A: "Ömer Seyfettin", B: "Ziya Gökalp", C: "Ali Canip Yöntem", D: "Hepsi" }, dogruCevap: "D" },
    { kategori: "Edebiyat", seviye: 82, soru: "'Kuyucaklı Yusuf' ve 'Kürk Mantolu Madonna' gibi eserlerin yazarı?", secenekler: { A: "Sabahattin Ali", B: "Peyami Safa", C: "Tarık Buğra", D: "Orhan Kemal" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 83, soru: "Milli Şair unvanına sahip İstiklal Marşı yazarı kimdir?", secenekler: { A: "Mehmet Akif Ersoy", B: "Yahya Kemal", C: "Ziya Gökalp", D: "Mehmet Emin Yurdakul" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 84, soru: "'Sinekli Bakkal' ve 'Ateşten Gömlek' romanlarının yazarı?", secenekler: { A: "Halide Edip Adıvar", B: "Yakup Kadri", C: "Reşat Nuri", D: "Refik Halit" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 85, soru: "'Yaban' ve 'Kiralık Konak' romanlarının yazarı kimdir?", secenekler: { A: "Yakup Kadri Karaosmanoğlu", B: "Reşat Nuri", C: "Falih Rıfkı", D: "Memduh Şevket" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 86, soru: "'Çalıkuşu' ve 'Yaprak Dökümü' romanlarının yazarı kimdir?", secenekler: { A: "Reşat Nuri Güntekin", B: "Aka Gündüz", C: "Halide Edip", D: "Peyami Safa" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 87, soru: "'Bayrak Şairi' olarak bilinen şairimiz kimdir?", secenekler: { A: "Arif Nihat Asya", B: "Zeki Ömer Defne", C: "Orhan Şaik Gökyay", D: "Enis Behiç" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 88, soru: "Garip akımının (I. Yeni) kurucuları kimlerdir?", secenekler: { A: "Orhan Veli / Melih Cevdet / Oktay Rifat", B: "Ece Ayhan / Cemal Süreya", C: "İlhan Berk / Turgut Uyar", D: "Edip Cansever" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 89, soru: "'Kaldırımlar' şairi olarak bilinen mistik şairimiz?", secenekler: { A: "Necip Fazıl Kısakürek", B: "Sezai Karakoç", C: "Cahit Zarifoğlu", D: "Asaf Halet" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 90, soru: "'Mavi Gözlü Dev' lakaplı toplumcu gerçekçi şairimiz?", secenekler: { A: "Nazım Hikmet", B: "Rıfat Ilgaz", C: "Enver Gökçe", D: "Ahmed Arif" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 91, soru: "Saf şiirin (Öz Şiir) en önemli temsilcilerinden biri?", secenekler: { A: "Ahmet Haşim", B: "Yahya Kemal", C: "Cahit Sıtkı", D: "Hepsi" }, dogruCevap: "D" },
    { kategori: "Edebiyat", seviye: 92, soru: "'Han Duvarları' şiiriyle ünlü 'Beş Hececi' şairimiz?", secenekler: { A: "Faruk Nafiz Çamlıbel", B: "Enis Behiç", C: "Halit Fahri", D: "Orhan Seyfi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 93, soru: "Roman ve hikayede olayı her şeyi bilen birinin anlatması?", secenekler: { A: "İlahi Bakış Açısı", B: "Kahraman Bakış Açısı", C: "Gözlemci Bakış Açısı", D: "Çoğulcu Bakış Açısı" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 94, soru: "'Sessiz Gemi' şiiri kime aittir?", secenekler: { A: "Yahya Kemal Beyatlı", B: "Ahmet Haşim", C: "Tevfik Fikret", D: "Necip Fazıl" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 95, soru: "'Türkçem benim ses bayrağım' diyen şairimiz?", secenekler: { A: "Fazıl Hüsnü Dağlarca", B: "Behçet Necatigil", C: "Cahit Külebi", D: "Bedri Rahmi" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 96, soru: "Modern Türk öykücülüğünün en büyük ismi (Durum öyküsü)?", secenekler: { A: "Sait Faik Abasıyanık", B: "Ömer Seyfettin", C: "Memduh Şevket", D: "Haldun Taner" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 97, soru: "'Çile' adlı şiir kitabı kime aittir?", secenekler: { A: "Necip Fazıl Kısakürek", B: "Ahmet Hamdi", C: "Ziya Osman", D: "Asaf Halet" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 98, soru: "'Huzur' ve 'Saatleri Ayarlama Enstitüsü' yazarı?", secenekler: { A: "Ahmet Hamdi Tanpınar", B: "Abdülhak Şinasi", C: "Peyami Safa", D: "Tarık Buğra" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 99, soru: "'İnce Memed' romanıyla dünya çapında tanınan yazarımız?", secenekler: { A: "Yaşar Kemal", B: "Orhan Kemal", C: "Kemal Tahir", D: "Fakir Baykurt" }, dogruCevap: "A" },
    { kategori: "Edebiyat", seviye: 100, soru: "Türk edebiyatında ilk Nobel Edebiyat Ödülü'nü kim almıştır?", secenekler: { A: "Orhan Pamuk", B: "Yaşar Kemal", C: "Fazıl Hüsnü", D: "Nazım Hikmet" }, dogruCevap: "A" }
);
 
