// Eğer dizi yoksa oluştur, varsa içine ekle
window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-20: Türkiye Coğrafyası ve Şehirler
    { kategori: "Genel Kültür", seviye: 1, soru: "Türkiye'nin başkenti neresidir?", secenekler: { A: "İstanbul", B: "Ankara", C: "İzmir", D: "Bursa" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 2, soru: "Türkiye'nin en yüksek dağı hangisidir?", secenekler: { A: "Erciyes", B: "Ağrı Dağı", C: "Süphan", D: "Kaçkar" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 3, soru: "Ege Bölgesi'nin en kalabalık şehri hangisidir?", secenekler: { A: "Aydın", B: "Muğla", C: "Denizli", D: "İzmir" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 4, soru: "Türkiye'nin en büyük gölü hangisidir?", secenekler: { A: "Tuz Gölü", B: "Van Gölü", C: "Beyşehir Gölü", D: "Eğirdir Gölü" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 5, soru: "Yedi göller hangi ilimiz sınırları içerisindedir?", secenekler: { A: "Bolu", B: "Rize", C: "Trabzon", D: "Artvin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 6, soru: "Pamukkale Travertenleri hangi ilimizdedir?", secenekler: { A: "Denizli", B: "Afyon", C: "Uşak", D: "Manisa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 7, soru: "Türkiye'nin en uzun nehri hangisidir?", secenekler: { A: "Fırat", B: "Dicle", C: "Kızılırmak", D: "Sakarya" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 8, soru: "Güneydoğu Anadolu'nun 'Peygamberler Şehri' olarak bilinen ili hangisidir?", secenekler: { A: "Şanlıurfa", B: "Gaziantep", C: "Diyarbakır", D: "Mardin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 9, soru: "Peri Bacaları hangi turistik bölgemizde yer alır?", secenekler: { A: "Kapadokya", B: "Ihlara Vadisi", C: "Pamukkale", D: "Efes" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 10, soru: "Mevlana Müzesi hangi ilimizdedir?", secenekler: { A: "Ankara", B: "Konya", C: "Kayseri", D: "Sivas" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 11, soru: "Türkiye'nin üç tarafı denizlerle çevrili olması nedeniyle hangi coğrafi tanıma uyar?", secenekler: { A: "Ada", B: "Yarımada", C: "Körfez", D: "Vaha" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 12, soru: "Dünyanın en eski yerleşim yerlerinden biri olan Göbeklitepe hangi ilimizdedir?", secenekler: { A: "Şanlıurfa", B: "Adıyaman", C: "Hatay", D: "Batman" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 13, soru: "Aspendos Antik Tiyatrosu hangi ilimizdedir?", secenekler: { A: "Antalya", B: "Muğla", C: "İzmir", D: "Mersin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 14, soru: "Çay üretimiyle meşhur olan Karadeniz ilimiz hangisidir?", secenekler: { A: "Rize", B: "Artvin", C: "Giresun", D: "Ordu" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 15, soru: "Kayısısı ile ünlü ilimiz hangisidir?", secenekler: { A: "Malatya", B: "Elazığ", C: "Erzincan", D: "Kars" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 16, soru: "İstiklal Madalyası alan ilk ilçemiz hangisidir?", secenekler: { A: "İnebolu", B: "Kazan", C: "Polatlı", D: "Maraş" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 17, soru: "Çanakkale Boğazı ile İstanbul Boğazı arasındaki deniz hangisidir?", secenekler: { A: "Marmara Denizi", B: "Ege Denizi", C: "Karadeniz", D: "Akdeniz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 18, soru: "Cumhuriyet döneminin ilk barajı hangisidir?", secenekler: { A: "Çubuk Barajı", B: "Atatürk Barajı", C: "Keban Barajı", D: "Hirfanlı Barajı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 19, soru: "Türkiye'nin en kuzey noktası olan İnceburun hangi ilimizdedir?", secenekler: { A: "Sinop", B: "Kırklareli", C: "Artvin", D: "Zonguldak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 20, soru: "Ülkemizin en büyük adası hangisidir?", secenekler: { A: "Gökçeada", B: "Bozcaada", C: "Büyükada", D: "Cunda" }, dogruCevap: "A" },

    // 21-40: Türk Tarihi ve Milli Değerler
    { kategori: "Genel Kültür", seviye: 21, soru: "İstiklal Marşı'mızın şairi kimdir?", secenekler: { A: "Ziya Gökalp", B: "Namık Kemal", C: "Mehmet Akif Ersoy", D: "Yahya Kemal" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 22, soru: "Cumhuriyet kaç yılında ilan edilmiştir?", secenekler: { A: "1920", B: "1921", C: "1923", D: "1924" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 23, soru: "Anadolu'nun kapılarını Türklere açan savaş hangisidir?", secenekler: { A: "Miryokefalon", B: "Malazgirt", C: "Pasinler", D: "Dandanakan" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 24, soru: "İstanbul hangi yıl fethedilmiştir?", secenekler: { A: "1071", B: "1299", C: "1453", D: "1517" }, dogruCevap: "C" },
    { kategori: "Genel Kültür", seviye: 25, soru: "Osmanlı Devleti'nin kurucusu kimdir?", secenekler: { A: "Ertuğrul Gazi", B: "Osman Bey", C: "Orhan Bey", D: "Selçuk Bey" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 26, soru: "Türkiye Büyük Millet Meclisi (TBMM) hangi tarihte açılmıştır?", secenekler: { A: "29 Ekim 1923", B: "23 Nisan 1920", C: "19 Mayıs 1919", D: "30 Ağustos 1922" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 27, soru: "Mustafa Kemal Atatürk'ün nüfusa kayıtlı olduğu il hangisidir?", secenekler: { A: "Selanik", B: "İstanbul", C: "Ankara", D: "Gaziantep" }, dogruCevap: "D" },
    { kategori: "Genel Kültür", seviye: 28, soru: "Atatürk'ün ebedi istirahatgahı olan Anıtkabir hangi şehrimizdedir?", secenekler: { A: "Ankara", B: "İstanbul", C: "İzmir", D: "Samsun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 29, soru: "Tarihte Türk adıyla kurulan ilk devlet hangisidir?", secenekler: { A: "Hunlar", B: "Göktürkler", C: "Uygurlar", D: "Selçuklular" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 30, soru: "Sivas Kongresi hangi binada yapılmıştır?", secenekler: { A: "Sivas Lisesi", B: "Hükümet Konağı", C: "Ulu Cami", D: "Gök Medrese" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 31, soru: "Çanakkale Zaferi hangi gün kutlanır?", secenekler: { A: "18 Mart", B: "19 Mayıs", C: "30 Ağustos", D: "29 Ekim" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 32, soru: "Osmanlı'nın ilk başkenti neresidir?", secenekler: { A: "Söğüt", B: "Bursa", C: "Edirne", D: "İznik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 33, soru: "Hangi padişah 'Fatih' unvanını almıştır?", secenekler: { A: "II. Mehmet", B: "I. Selim", C: "I. Süleyman", D: "II. Abdülhamid" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 34, soru: "Türklere özgü, dünyanın en eski yaylı çalgılarından biri hangisidir?", secenekler: { A: "Kopuz", B: "Bağlama", C: "Ud", D: "Kanun" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 35, soru: "Orhun Abideleri günümüzde hangi ülke sınırları içerisindedir?", secenekler: { A: "Moğolistan", B: "Kazakistan", C: "Özbekistan", D: "Türkiye" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 36, soru: "Dede Korkut hikayeleri hangi Türk boyuna aittir?", secenekler: { A: "Oğuzlar", B: "Kıpçaklar", C: "Karluklar", D: "Uygurlar" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 37, soru: "Mimar Sinan'ın 'Ustalık Eserim' dediği cami hangisidir?", secenekler: { A: "Selimiye Camii", B: "Süleymaniye Camii", C: "Şehzade Camii", D: "Sultan Ahmet Camii" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 38, soru: "Lale Devri hangi padişah zamanında yaşanmıştır?", secenekler: { A: "III. Ahmed", B: "IV. Murad", C: "II. Mahmud", D: "Abdülaziz" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 39, soru: "Cumhuriyet tarihinin ilk kadın muhtarı kimdir?", secenekler: { A: "Gül Esin", B: "Sabiha Gökçen", C: "Afet İnan", D: "Türkan Saylan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 40, soru: "Türklerin kullandığı ilk takvim hangisidir?", secenekler: { A: "12 Hayvanlı Türk Takvimi", B: "Hicri Takvim", C: "Rumi Takvim", D: "Miladi Takvim" }, dogruCevap: "A" },

    // 41-60: Türk Edebiyatı ve Sanat
    { kategori: "Genel Kültür", seviye: 41, soru: "Şair-i Azam olarak bilinen şairimiz kimdir?", secenekler: { A: "Abdülhak Hamit Tarhan", B: "Tevfik Fikret", C: "Cahit Sıtkı Tarancı", D: "Nazım Hikmet" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 42, soru: "Mai ve Siyah romanı kime aittir?", secenekler: { A: "Halit Ziya Uşaklıgil", B: "Yakup Kadri", C: "Reşat Nuri", D: "Peyami Safa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 43, soru: "Hababam Sınıfı'nın yazarı kimdir?", secenekler: { A: "Rıfat Ilgaz", B: "Aziz Nesin", C: "Orhan Kemal", D: "Yaşar Kemal" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 44, soru: "Kuyucaklı Yusuf romanı kime aittir?", secenekler: { A: "Sabahattin Ali", B: "Peyami Safa", C: "Ahmet Hamdi Tanpınar", D: "Tarık Buğra" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 45, soru: "Vatan Şairi olarak bilinen yazarımız?", secenekler: { A: "Namık Kemal", B: "Ziya Paşa", C: "Mehmet Akif", D: "Necip Fazıl" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 46, soru: "Türkçenin ilk sözlüğü hangisidir?", secenekler: { A: "Divanü Lügati't-Türk", B: "Muhakemetü'l-Lügateyn", C: "Kamusu Türki", D: "Lehçe-i Osmani" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 47, soru: "Çalıkuşu romanının baş kahramanı kimdir?", secenekler: { A: "Feride", B: "Eylül", C: "Bihter", D: "Zehra" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 48, soru: "Türk edebiyatında ilk yerli roman hangisidir?", secenekler: { A: "Taaşşuk-ı Talat ve Fitnat", B: "İntibah", C: "Araba Sevdası", D: "Karabibik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 49, soru: "Sinekli Bakkal romanı kime aittir?", secenekler: { A: "Halide Edip Adıvar", B: "Reşat Nuri", C: "Yakup Kadri", D: "Ömer Seyfettin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 50, soru: "Yaprak Dökümü romanı kime aittir?", secenekler: { A: "Reşat Nuri Güntekin", B: "Peyami Safa", C: "Tarık Buğra", D: "Kemal Tahir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 51, soru: "Mesnevi eseri kime aittir?", secenekler: { A: "Mevlana", B: "Yunus Emre", C: "Hacı Bektaş Veli", D: "Ahmet Yesevi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 52, soru: "Risaletü'n-Nushiyye kime aittir?", secenekler: { A: "Yunus Emre", B: "Pir Sultan Abdal", C: "Kaygusuz Abdal", D: "Karacaoğlan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 53, soru: "Şerbetçi ve dondurmacı tiplemeleriyle ünlü Türk gölge oyunu?", secenekler: { A: "Karagöz ve Hacivat", B: "Meddah", C: "Orta Oyunu", D: "Köy Seyirlik Oyunları" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 54, soru: "Geleneksel Türk tiyatrosunda doğaçlama yapılan oyun?", secenekler: { A: "Orta Oyunu", B: "Trajedi", C: "Komedi", D: "Opera" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 55, soru: "Makber şiiri kime aittir?", secenekler: { A: "Abdülhak Hamit Tarhan", B: "Recaizade Mahmut Ekrem", C: "Muallim Naci", D: "Şinasi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 56, soru: "Modern Türk öykücülüğünün öncüsü kimdir?", secenekler: { A: "Sait Faik Abasıyanık", B: "Ömer Seyfettin", C: "Memduh Şevket Esendal", D: "Sabahattin Ali" }, dogruCevap: "B" },
    { kategori: "Genel Kültür", seviye: 57, soru: "Otuz Beş Yaş şiiriyle tanınan şairimiz?", secenekler: { A: "Cahit Sıtkı Tarancı", B: "Ahmet Muhip Dıranas", C: "Ziya Osman Saba", D: "Behçet Necatigil" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 58, soru: "İnce Memed romanı kime aittir?", secenekler: { A: "Yaşar Kemal", B: "Orhan Kemal", C: "Kemal Tahir", D: "Fakir Baykurt" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 59, soru: "Dokuzuncu Hariciye Koğuşu kime aittir?", secenekler: { A: "Peyami Safa", B: "Ahmet Hamdi Tanpınar", C: "Tarık Buğra", D: "Samiha Ayverdi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 60, soru: "Safahat eseri kime aittir?", secenekler: { A: "Mehmet Akif Ersoy", B: "Yahya Kemal", C: "Tevfik Fikret", D: "Ziya Gökalp" }, dogruCevap: "A" },

    // 61-80: Türk Kültürü, Gelenek ve Spor
    { kategori: "Genel Kültür", seviye: 61, soru: "Türklerin milli sporu olarak kabul edilen spor dalı?", secenekler: { A: "Güreş", B: "Okçuluk", C: "Cirit", D: "Binicilik" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 62, soru: "Dünyanın en eski güreş festivali hangisidir?", secenekler: { A: "Kırkpınar Yağlı Güreşleri", B: "Elmalı Güreşleri", C: "Kurtdere Güreşleri", D: "Karakucak Güreşleri" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 63, soru: "Türklere özgü, at üzerinde oynanan geleneksel spor?", secenekler: { A: "Cirit", B: "Matrak", C: "Gökbörü", D: "Tepük" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 64, soru: "Türk kahvesi pişirilirken kullanılan küçük saplı kaba ne denir?", secenekler: { A: "Cezve", B: "Güğüm", C: "İbrik", D: "Semaver" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 65, soru: "Erzurum ve çevresinde oynanan halk oyunu?", secenekler: { A: "Bar", B: "Zeybek", C: "Horon", D: "Halay" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 66, soru: "Ege Bölgesi ile özdeşleşmiş halk oyunu?", secenekler: { A: "Zeybek", B: "Horon", C: "Kaşık Oyunu", D: "Bengi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 67, soru: "Karadeniz bölgesine ait, kemençe eşliğinde oynanan oyun?", secenekler: { A: "Horon", B: "Halay", C: "Çayda Çıra", D: "Atabarı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 68, soru: "Trakya yöresine ait ünlü halk oyunu?", secenekler: { A: "Hora", B: "Bar", C: "Mengi", D: "Zeybek" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 69, soru: "Türk mutfağının vazgeçilmezi olan, fermente edilmiş süt ürünü?", secenekler: { A: "Yoğurt", B: "Peynir", C: "Krema", D: "Kefir" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 70, soru: "Türk mutfağında ince hamurdan yapılan, içi kıymalı veya patatesli yemek?", secenekler: { A: "Mantı", B: "Börek", C: "Lahmacun", D: "Pide" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 71, soru: "Keloğlan hangi Türk kültür ögesine aittir?", secenekler: { A: "Masal", B: "Destan", C: "Efsane", D: "Ağıt" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 72, soru: "Nasreddin Hoca fıkralarıyla ünlü şehrimiz?", secenekler: { A: "Akşehir", B: "Eskişehir", C: "Kütahya", D: "Afyon" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 73, soru: "Baharın müjdecisi olarak kutlanan Türk bayramı?", secenekler: { A: "Nevruz", B: "Hıdırellez", C: "Kurban Bayramı", D: "Ramazan Bayramı" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 74, soru: "Geleneksel Türk ebru sanatında kullanılan ana malzeme?", secenekler: { A: "Kitre", B: "Yağ", C: "Alçı", D: "Kil" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 75, soru: "Hat sanatı ile uğraşan sanatçılara ne denir?", secenekler: { A: "Hattat", B: "Müzehhip", C: "Ebruli", D: "Nakkaş" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 76, soru: "Eski yazma kitapları süsleyen küçük resim sanatı?", secenekler: { A: "Minyatür", B: "Çini", C: "Tezhip", D: "Fresk" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 77, soru: "Çini sanatı ile dünyaca ünlü ilimiz?", secenekler: { A: "Kütahya", B: "İzmit", C: "Bursa", D: "Konya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 78, soru: "Dünyanın en eski askeri bandosu hangisidir?", secenekler: { A: "Mehter Takımı", B: "Bando Mızıka", C: "Orkestra", D: "Filarmoni" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 79, soru: "Türk bayrağındaki hilal ve yıldız neyi temsil eder (sembolik olarak)?", secenekler: { A: "Bağımsızlık", B: "Barış", C: "Bereket", D: "Adalet" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 80, soru: "Atatürk'ün 'En büyük eserim' dediği şey hangisidir?", secenekler: { A: "Türkiye Cumhuriyeti", B: "Nutuk", C: "Anıtkabir", D: "TBMM" }, dogruCevap: "A" },

    // 81-100: Dünya Genel Kültürü ve Karışık
    { kategori: "Genel Kültür", seviye: 81, soru: "Dünyanın en kalabalık ülkesi hangisidir?", secenekler: { A: "Hindistan", B: "Çin", C: "ABD", D: "Rusya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 82, soru: "En büyük yüzölçümüne sahip ülke hangisidir?", secenekler: { A: "Rusya", B: "Kanada", C: "Çin", D: "Brezilya" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 83, soru: "Eyfel Kulesi hangi şehirdedir?", secenekler: { A: "Paris", B: "Londra", C: "Roma", D: "Berlin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 84, soru: "Pisa Kulesi hangi ülkededir?", secenekler: { A: "İtalya", B: "İspanya", C: "Fransa", D: "Yunanistan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 85, soru: "Kızıl Meydan hangi şehirdedir?", secenekler: { A: "Moskova", B: "Kiev", C: "Varşova", D: "Prag" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 86, soru: "Özgürlük Heykeli hangi ülkededir?", secenekler: { A: "ABD", B: "Fransa", C: "İngiltere", D: "Kanada" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 87, soru: "Kolezyum hangi şehirdedir?", secenekler: { A: "Roma", B: "Atina", C: "Venedik", D: "Floransa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 88, soru: "Piramitler hangi ülkededir?", secenekler: { A: "Mısır", B: "Meksika", C: "Peru", D: "Sudan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 89, soru: "Dünyanın en uzun nehri hangisidir?", secenekler: { A: "Nil", B: "Amazon", C: "Ganj", D: "Mississippi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 90, soru: "En derin okyanus hangisidir?", secenekler: { A: "Büyük Okyanus", B: "Atlas Okyanusu", C: "Hint Okyanusu", D: "Kuzey Buz Denizi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 91, soru: "Mona Lisa tablosu kime aittir?", secenekler: { A: "Leonardo da Vinci", B: "Picasso", C: "Van Gogh", D: "Salvador Dali" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 92, soru: "Telefonun mucidi kimdir?", secenekler: { A: "Graham Bell", B: "Edison", C: "Tesla", D: "Marconi" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 93, soru: "Hangi ülke 'Güneşin Doğduğu Ülke' olarak bilinir?", secenekler: { A: "Japonya", B: "Çin", C: "Güney Kore", D: "Tayland" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 94, soru: "Dünya kupasını en çok kazanan ülke hangisidir?", secenekler: { A: "Brezilya", B: "Almanya", C: "İtalya", D: "Arjantin" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 95, soru: "Kanarya Adaları hangi ülkeye bağlıdır?", secenekler: { A: "İspanya", B: "Portekiz", C: "Fas", D: "Fransa" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 96, soru: "Avrupa Birliği'nin merkezi hangi şehirdir?", secenekler: { A: "Brüksel", B: "Strazburg", C: "Lüksemburg", D: "Cenevre" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 97, soru: "Dünyanın yedi harikasından biri olan Tac Mahal nerededir?", secenekler: { A: "Hindistan", B: "İran", C: "Pakistan", D: "Afganistan" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 98, soru: "İnce Memed kimin eseridir?", secenekler: { A: "Yaşar Kemal", B: "Orhan Pamuk", C: "Zülfü Livaneli", D: "Elif Şafak" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 99, soru: "Güneş sistemindeki en küçük gezegen hangisidir?", secenekler: { A: "Merkür", B: "Mars", C: "Venüs", D: "Neptün" }, dogruCevap: "A" },
    { kategori: "Genel Kültür", seviye: 100, soru: "Türkiye'nin ilk yerli otomobilinin adı nedir?", secenekler: { A: "TOGG", B: "Devrim", C: "Anadol", D: "Şahin" }, dogruCevap: "A" }
);
