window.tumSorular.push(
    { seviye: 1, kategori: "Sinema / TV", soru: "Ünlü 'Hababam Sınıfı' film serisinde 'Kel Mahmut' karakterini kim canlandırmıştır?", secenekler: { A: "Kemal Sunal", B: "Halit Akçatepe", C: "Münir Özkul", D: "Şener Şen" }, dogruCevap: "C" },
    { seviye: 2, kategori: "Sinema / TV", soru: "'Bana bir masal anlat baba' şarkısı hangi meşhur Türk dizisinin jenerik müziğidir?", secenekler: { A: "Ekmek Teknesi", B: "İkinci Bahar", C: "Süper Baba", D: "Mahallenin Muhtarları" }, dogruCevap: "C" },
    { seviye: 3, kategori: "Sinema / TV", soru: "Harry Potter film serisinde büyücülük okulunun adı nedir?", secenekler: { A: "Narnia", B: "Hogwarts", C: "Gondor", D: "Mordor" }, dogruCevap: "B" },
    { seviye: 4, kategori: "Sinema / TV", soru: "Cem Yılmaz'ın uzaylılar tarafından kaçırılan Arif'i canlandırdığı filmin adı nedir?", secenekler: { A: "AROG", B: "Hokkabaz", C: "GORA", D: "Yahşi Batı" }, dogruCevap: "C" },
    { seviye: 5, kategori: "Sinema / TV", soru: "'I am your father' (Ben senin babanım) efsane repliği hangi film serisine aittir?", secenekler: { A: "Star Wars", B: "Yüzüklerin Efendisi", C: "Matrix", D: "Terminatör" }, dogruCevap: "A" },
    { seviye: 6, kategori: "Sinema / TV", soru: "SüngerBob KareŞort çizgi dizisinde SüngerBob nerede yaşar?", secenekler: { A: "Bir ananasta", B: "Bir hindistan cevizinde", C: "Bir mağarada", D: "Yengeç Restoran'da" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Sinema / TV", soru: "Leonardo DiCaprio uzun yıllar süren bekleyişin ardından ilk Oscar'ını hangi filmle kazanmıştır?", secenekler: { A: "Titanik", B: "Para Avcısı", C: "Diriliş (The Revenant)", D: "Zindan Adası" }, dogruCevap: "C" },
    { seviye: 8, kategori: "Sinema / TV", soru: "Tarantino'nun yönettiği, John Travolta ve Samuel L. Jackson'ın başrolde olduğu 1994 yapımı kült film hangisidir?", secenekler: { A: "Rezervuar Köpekleri", B: "Kill Bill", C: "Zincirsiz", D: "Ucuz Roman (Pulp Fiction)" }, dogruCevap: "D" },
    { seviye: 9, kategori: "Sinema / TV", soru: "Sinema tarihinde En İyi Film Oscar'ını kazanan İLK ve TEK fantastik türündeki film hangisidir?", secenekler: { A: "Yüzüklerin Efendisi: Kralın Dönüşü", B: "Harry Potter: Ölüm Yadigarları", C: "Avatar", D: "Pan'ın Labyrinth'i" }, dogruCevap: "A" },
    { seviye: 10, kategori: "Sinema / TV", soru: "'Eşkıya' filminde Şener Şen'in canlandırdığı Baran karakterinin ihanetine uğradığı en yakın arkadaşı kimdir?", secenekler: { A: "Cumali", B: "Berfo", C: "Müslüm", D: "Keje" }, dogruCevap: "B" },
    { seviye: 11, kategori: "Sinema / TV", soru: "Alfred Hitchcock'un ünlü 'Sapık' (Psycho) filmindeki efsanevi duş sahnesinde bıçaklanan kadın karakteri kim canlandırmıştır?", secenekler: { A: "Marilyn Monroe", B: "Grace Kelly", C: "Janet Leigh", D: "Audrey Hepburn" }, dogruCevap: "C" },
    { seviye: 12, kategori: "Sinema / TV", soru: "1939 yapımı 'Rüzgar Gibi Geçti' filminde Scarlett O'Hara'nın söylediği unutulmaz kapanış repliği nedir?", secenekler: { A: "Her zaman Paris'imiz olacak.", B: "Yarın başka bir gün.", C: "Evi gibisi yok.", D: "Frankly my dear, I don't give a damn." }, dogruCevap: "B" }
);