window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
    // 1-25: Türk Futbol Tarihi ve Süper Lig
    { seviye: 1, kategori: "Spor", soru: "UEFA Kupası'nı kazanan tek Türk takımı hangisidir?", secenekler: { A: "Fenerbahçe", B: "Beşiktaş", C: "Galatasaray", D: "Trabzonspor" }, dogruCevap: "C" },
    { seviye: 2, kategori: "Spor", soru: "Süper Lig tarihinde en çok şampiyonluk yaşayan teknik direktör?", secenekler: { A: "Fatih Terim", B: "Mustafa Denizli", C: "Şenol Güneş", D: "Okan Buruk" }, dogruCevap: "A" },
    { seviye: 3, kategori: "Spor", soru: "Süper Lig'in 'Taçsız Kral' lakaplı efsane ismi kimdir?", secenekler: { A: "Metin Oktay", B: "Tanju Çolak", C: "Hakan Şükür", D: "Sergen Yalçın" }, dogruCevap: "A" },
    { seviye: 4, kategori: "Spor", soru: "Fenerbahçe'nin 'Ordinaryüs' lakaplı unutulmaz futbolcusu kimdir?", secenekler: { A: "Lefter Küçükandonyadis", B: "Can Bartu", C: "Rıdvan Dilmen", D: "Alex de Souza" }, dogruCevap: "A" },
    { seviye: 5, kategori: "Spor", soru: "Beşiktaş'ın simgesi olan 'Kara Kartal' lakabı nereden gelir?", secenekler: { A: "Bir taraftarın tezahüratından", B: "Kulüp tüzüğünden", C: "Bir balıkçının sözünden", D: "Kurucu başkanın isteğinden" }, dogruCevap: "A" },
    { seviye: 6, kategori: "Spor", soru: "Süper Lig tarihinde bir sezonda en çok gol atan (39 gol) futbolcu?", secenekler: { A: "Tanju Çolak", B: "Enner Valencia", C: "Mbaye Diagne", D: "Metin Oktay" }, dogruCevap: "A" },
    { seviye: 7, kategori: "Spor", soru: "Türk Milli Takımı, 2002 Dünya Kupası'nda hangi ülkeyi yenerek 3. olmuştur?", secenekler: { A: "Brezilya", B: "Güney Kore", C: "Senegal", D: "Japonya" }, dogruCevap: "B" },
    { seviye: 8, kategori: "Spor", soru: "Avrupa şampiyonalarında (Euro 2008) Türkiye yarı finalde hangi ülkeye elenmiştir?", secenekler: { A: "Almanya", B: "Hırvatistan", C: "Portekiz", D: "Çek Cumhuriyeti" }, dogruCevap: "A" },
    { seviye: 9, kategori: "Spor", soru: "A Milli Takım formasıyla en çok gol atan futbolcu kimdir?", secenekler: { A: "Hakan Şükür", B: "Burak Yılmaz", C: "Cenk Tosun", D: "Nihat Kahveci" }, dogruCevap: "A" },
    { seviye: 10, kategori: "Spor", soru: "Trabzonspor'un Süper Lig'deki ilk şampiyonluk dönemi hangi yıllar arasındadır?", secenekler: { A: "1970'ler", B: "1980'ler", C: "1990'ler", D: "2000'ler" }, dogruCevap: "A" },
    { seviye: 11, kategori: "Spor", soru: "Hem basketbol hem futbol milli takımında forma giyen efsane sporcu?", secenekler: { A: "Can Bartu", B: "Metin Oktay", C: "Turgay Şeren", D: "Lefter" }, dogruCevap: "A" },
    { seviye: 12, kategori: "Spor", soru: "Berlin Kaplanı lakaplı efsane Türk kaleci kimdir?", secenekler: { A: "Turgay Şeren", B: "Rüştü Reçber", C: "Volkan Demirel", D: "Muslera" }, dogruCevap: "A" },
    { seviye: 13, kategori: "Spor", soru: "Arda Güler hangi dünya devine transfer olarak göğsümüzü kabartmıştır?", secenekler: { A: "Real Madrid", B: "Barcelona", C: "Manchester City", D: "Bayern Münih" }, dogruCevap: "A" },
    { seviye: 14, kategori: "Spor", soru: "Süper Lig'de 'Dört Büyükler' dışında şampiyon olan ilk takım?", secenekler: { A: "Bursaspor", B: "Başakşehir", C: "Eskişehirspor", D: "Göztepe" }, dogruCevap: "A" },
    { seviye: 15, kategori: "Spor", soru: "A Milli Futbol Takımı'nın ilk maçı hangi ülkeye karşıdır?", secenekler: { A: "Romanya", B: "Yunanistan", C: "İtalya", D: "Bulgaristan" }, dogruCevap: "A" },
    { seviye: 16, kategori: "Spor", soru: "Süper Lig tarihinde '100'ler kulübü'ne giren ilk futbolcu?", secenekler: { A: "Metin Oktay", B: "Hakan Şükür", C: "Tanju Çolak", D: "Lefter" }, dogruCevap: "A" },
    { seviye: 17, kategori: "Spor", soru: "Beşiktaş'ın efsane başkanı 'Süleyman Seba' kaç yıl başkanlık yapmıştır?", secenekler: { A: "16", B: "10", C: "20", D: "8" }, dogruCevap: "A" },
    { seviye: 18, kategori: "Spor", soru: "Galatasaray'ın efsane kalecisi 'Muslera' hangi ülkelidir?", secenekler: { A: "Uruguay", B: "Arjantin", C: "Brezilya", D: "Şili" }, dogruCevap: "A" },
    { seviye: 19, kategori: "Spor", soru: "Fenerbahçe'nin stadyumu Şükrü Saracoğlu hangi semttedir?", secenekler: { A: "Kadıköy", B: "Beşiktaş", C: "Şişli", D: "Bakırköy" }, dogruCevap: "A" },
    { seviye: 20, kategori: "Spor", soru: "Türkiye Kupası'nı en çok kazanan takım hangisidir?", secenekler: { A: "Galatasaray", B: "Beşiktaş", C: "Fenerbahçe", D: "Trabzonspor" }, dogruCevap: "A" },

    // 26-50: Türk Güreşi, Halter ve Olimpiyat Başarıları
    { seviye: 26, kategori: "Spor", soru: "Olimpiyat tarihinde Türkiye'ye ilk altın madalyayı kazanan sporcu?", secenekler: { A: "Yaşar Erkan", B: "Naim Süleymanoğlu", C: "Hamza Yerlikaya", D: "Mete Gazoz" }, dogruCevap: "A" },
    { seviye: 27, kategori: "Spor", soru: "Cep Herkülü lakaplı, 3 kez olimpiyat şampiyonu haltercimiz?", secenekler: { A: "Naim Süleymanoğlu", B: "Halil Mutlu", C: "Taner Sağır", D: "Sedat Artunç" }, dogruCevap: "A" },
    { seviye: 28, kategori: "Spor", soru: "Asrın Güreşçisi unvanına sahip sporcumuz kimdir?", secenekler: { A: "Hamza Yerlikaya", B: "Rıza Kayaalp", C: "Taha Akgül", D: "Mahmut Demir" }, dogruCevap: "A" },
    { seviye: 29, kategori: "Spor", soru: "Mete Gazoz hangi branşta Olimpiyat Şampiyonu olmuştur?", secenekler: { A: "Okçuluk", B: "Atıcılık", C: "Eskrim", D: "Jimnastik" }, dogruCevap: "A" },
    { seviye: 30, kategori: "Spor", soru: "Kırkpınar Yağlı Güreşleri'nde üst üste 3 kez başpehlivan olana ne verilir?", secenekler: { A: "Altın Kemer", B: "Gümüş Madalya", C: "Kupa", D: "Pehlivan Beratı" }, dogruCevap: "A" },
    { seviye: 31, kategori: "Spor", soru: "Dünya ve Avrupa şampiyonu kadın boksörümüz kimdir?", secenekler: { A: "Busenaz Sürmeneli", B: "Buse Naz Çakıroğlu", C: "Nurcan Taylan", D: "İrem Yaman" }, dogruCevap: "A" },
    { seviye: 32, kategori: "Spor", soru: "Hangi sporcumuz 'Demir Bilek' olarak bilinir?", secenekler: { A: "Haydar Pazarlı", B: "Koca Yusuf", C: "Yaşar Doğu", D: "Adalı Halil" }, dogruCevap: "A" },
    { seviye: 33, kategori: "Spor", soru: "Türk spor tarihinde ilk dünya şampiyonu kadın halterci?", secenekler: { A: "Nurcan Taylan", B: "Sibel Özkan", C: "Şule Şahbaz", D: "Aylin Daşdelen" }, dogruCevap: "A" },
    { seviye: 34, kategori: "Spor", soru: "Rıza Kayaalp hangi spor dalında rekor sayıda Avrupa şampiyonu olmuştur?", secenekler: { A: "Güreş", B: "Halter", C: "Boks", D: "Tekvando" }, dogruCevap: "A" },
    { seviye: 35, kategori: "Spor", soru: "Olimpiyatlarda madalya kazanan ilk Türk kadın sporcu kimdir?", secenekler: { A: "Hülya Şenyurt", B: "Nurcan Taylan", C: "Hamide Bıççın", D: "Yasemin Adar" }, dogruCevap: "A" },
    { seviye: 36, kategori: "Spor", soru: "Koca Yusuf hangi güreş türüyle dünyada ün salmıştır?", secenekler: { A: "Yağlı Güreş / Karakucak", B: "Grekoromen", C: "Serbest Stil", D: "Sambo" }, dogruCevap: "A" },
    { seviye: 37, kategori: "Spor", soru: "Türkiye'nin kış olimpiyatlarındaki ilk sporcusu hangi branştadır?", secenekler: { A: "Kayak", B: "Buz Pateni", C: "Körling", D: "Buz Hokeyi" }, dogruCevap: "A" },
    { seviye: 38, kategori: "Spor", soru: "Tekvandoda Olimpiyat ikincisi olan ünlü kadın sporcumuz?", secenekler: { A: "Nur Tatar", B: "Servet Tazegül", C: "Merve Dinçel", D: "Hatice Kübra İlgün" }, dogruCevap: "A" },
    { seviye: 39, kategori: "Spor", soru: "Paralimpik oyunlarda altın madalya alan okçumuz?", secenekler: { A: "Öznur Cüre", B: "Gizem Girişmen", C: "Bahattin Hekimoğlu", D: "Yiğit Caner" }, dogruCevap: "B" },
    { seviye: 40, kategori: "Spor", soru: "Tarihi Elmalı Yağlı Güreşleri nerede düzenlenir?", secenekler: { A: "Antalya", B: "Edirne", C: "Balıkesir", D: "Manisa" }, dogruCevap: "A" },

    // 51-75: Türk Basketbolu ve Voleybolu
    { seviye: 51, kategori: "Spor", soru: "Türkiye Kadın Milli Voleybol Takımı'nın lakabı nedir?", secenekler: { A: "Filenin Sultanları", B: "Potanın Perileri", C: "12 Dev Adam", D: "Sultanlar" }, dogruCevap: "A" },
    { seviye: 52, kategori: "Spor", soru: "EuroLeague şampiyonu olan ilk Türk erkek basketbol takımı?", secenekler: { A: "Fenerbahçe", B: "Anadolu Efes", C: "Galatasaray", D: "Beşiktaş" }, dogruCevap: "A" },
    { seviye: 53, kategori: "Spor", soru: "Basketbolda '12 Dev Adam' lakabı hangi turnuvada verilmiştir?", secenekler: { A: "2001 Avrupa Şampiyonası", B: "2010 Dünya Şampiyonası", C: "2006 Dünya Şampiyonası", D: "1999 Avrupa Şampiyonası" }, dogruCevap: "A" },
    { seviye: 54, kategori: "Spor", soru: "NBA'de şampiyonluk yüzüğü takan ilk Türk basketbolcu?", secenekler: { A: "Mehmet Okur", B: "Hidayet Türkoğlu", C: "Alperen Şengün", D: "Cedi Osman" }, dogruCevap: "A" },
    { seviye: 55, kategori: "Spor", soru: "Eczacıbaşı ve VakıfBank hangi branşta dünya çapında başarıya sahiptir?", secenekler: { A: "Voleybol", B: "Hentbol", C: "Basketbol", D: "Yüzme" }, dogruCevap: "A" },
    { seviye: 56, kategori: "Spor", soru: "Dünya voleybolunda 'En Değerli Oyuncu' (MVP) seçilen milli sporcumuz?", secenekler: { A: "Melissa Vargas", B: "Eda Erdem", C: "Zehra Güneş", D: "Gizem Örge" }, dogruCevap: "A" },
    { seviye: 57, kategori: "Spor", soru: "NBA'de bir maçta en çok sayı atan Türk oyuncu (rekor)?", secenekler: { A: "Alperen Şengün", B: "Mehmet Okur", C: "Hidayet Türkoğlu", D: "Ersan İlyasova" }, dogruCevap: "A" },
    { seviye: 58, kategori: "Spor", soru: "Fenerbahçe Kadın Basketbol Takımı'nın Avrupa şampiyonluğu var mıdır?", secenekler: { A: "Evet (EuroLeague)", B: "Hayır", C: "Sadece EuroCup", D: "Sadece Türkiye Kupası" }, dogruCevap: "A" },
    { seviye: 59, kategori: "Spor", soru: "A Milli Erkek Basketbol Takımı, 2010 Dünya Şampiyonası'nda kaçıncı olmuştur?", secenekler: { A: "İkinci", B: "Üçüncü", C: "Dördüncü", D: "Şampiyon" }, dogruCevap: "A" },
    { seviye: 60, kategori: "Spor", soru: "Milli voleybolcumuz Eda Erdem'in heykeli hangi stadın önüne dikilmiştir?", secenekler: { A: "Ülker Stadyumu", B: "Vakıfbank Spor Sarayı", C: "Burhan Felek", D: "Sinan Erdem" }, dogruCevap: "A" },
    { seviye: 61, kategori: "Spor", soru: "Avrupa şampiyonu olan ilk Türk voleybol takımı?", secenekler: { A: "Eczacıbaşı", B: "Vakıfbank", C: "Arkas", D: "Halkbank" }, dogruCevap: "A" },
    { seviye: 62, kategori: "Spor", soru: "Potanın Perileri hangi milli takıma verilen isimdir?", secenekler: { A: "Kadın Basketbol", B: "Kadın Voleybol", C: "Kadın Hentbol", D: "Kadın Futbol" }, dogruCevap: "A" },
    { seviye: 63, kategori: "Spor", soru: "Türk basketbolunun 'Profesör' lakaplı efsane koçu kimdir?", secenekler: { A: "Aydın Örs", B: "Ergin Ataman", C: "Erman Kunter", D: "Çetin Yılmaz" }, dogruCevap: "A" },
    { seviye: 64, kategori: "Spor", soru: "Ergin Ataman, Panathinaikos'tan önce hangi Türk takımıyla 2 EuroLeague kazandı?", secenekler: { A: "Anadolu Efes", B: "Fenerbahçe", C: "Galatasaray", D: "Beşiktaş" }, dogruCevap: "A" },
    { seviye: 65, kategori: "Spor", soru: "Hidayet Türkoğlu NBA'de hangi takımda efsaneleşmiştir?", secenekler: { A: "Orlando Magic", B: "Sacramento Kings", C: "Toronto Raptors", D: "L.A. Clippers" }, dogruCevap: "A" },
    { seviye: 66, kategori: "Spor", soru: "Neslihan Demir hangi branşın 'Demir Leydi'si olarak bilinir?", secenekler: { A: "Voleybol", B: "Tenis", C: "Boks", D: "Eskrim" }, dogruCevap: "A" },
    { seviye: 67, kategori: "Spor", soru: "Vakıfbank Kadın Voleybol Takımı kaç kez CEV Şampiyonlar Ligi şampiyonu olmuştur?", secenekler: { A: "6", B: "3", C: "2", D: "1" }, dogruCevap: "A" },
    { seviye: 68, kategori: "Spor", soru: "Gözde Kırdar hangi takımın sembol voleybolcusudur?", secenekler: { A: "Vakıfbank", B: "Eczacıbaşı", C: "Fenerbahçe", D: "Galatasaray" }, dogruCevap: "A" },
    { seviye: 69, kategori: "Spor", soru: "Dünya Şampiyonası'nda 'Sayı Kralı' olan Türk basketbolcu?", secenekler: { A: "Erman Kunter", B: "Harun Erdenay", C: "İbrahim Kutluay", D: "Ömer Onan" }, dogruCevap: "A" },
    { seviye: 70, kategori: "Spor", soru: "Türkiye'nin en eski spor kulübü hangisidir?", secenekler: { A: "Beşiktaş (1903)", B: "Galatasaray (1905)", C: "Fenerbahçe (1907)", D: "İstanbulspor" }, dogruCevap: "A" },

    // 76-100: Dünya Sporundan Seçmeler
    { seviye: 76, kategori: "Spor", soru: "Dünya Kupası'nı en çok kazanan ülke hangisidir?", secenekler: { A: "Brezilya", B: "Almanya", C: "İtalya", D: "Arjantin" }, dogruCevap: "A" },
    { seviye: 77, kategori: "Spor", soru: "Ballon d'Or ödülünü en çok kazanan futbolcu kimdir?", secenekler: { A: "Lionel Messi", B: "C. Ronaldo", C: "Pele", D: "Zidane" }, dogruCevap: "A" },
    { seviye: 78, kategori: "Spor", soru: "Olimpiyat halkalarında toplam kaç renk bulunur?", secenekler: { A: "5", B: "6", C: "4", D: "7" }, dogruCevap: "A" },
    { seviye: 79, kategori: "Spor", soru: "Basketbolun mucidi kimdir?", secenekler: { A: "James Naismith", B: "David Stern", C: "Michael Jordan", D: "Phil Jackson" }, dogruCevap: "A" },
    { seviye: 80, kategori: "Spor", soru: "Maraton koşusunun mesafesi ne kadardır?", secenekler: { A: "42.195 m", B: "40.000 m", C: "21.000 m", D: "50.000 m" }, dogruCevap: "A" },
    { seviye: 81, kategori: "Spor", soru: "Formula 1'de 7 dünya şampiyonluğu olan pilotlar?", secenekler: { A: "Schumacher - Hamilton", B: "Senna - Prost", C: "Vettel - Alonso", D: "Verstappen - Leclerc" }, dogruCevap: "A" },
    { seviye: 82, kategori: "Spor", soru: "Teniste 'Toprak Kort' kralı kimdir?", secenekler: { A: "Rafael Nadal", B: "Roger Federer", C: "Novak Djokovic", D: "Carlos Alcaraz" }, dogruCevap: "A" },
    { seviye: 83, kategori: "Spor", soru: "NBA tarihinin en çok sayı atan oyuncusu?", secenekler: { A: "LeBron James", B: "Kareem Abdul-Jabbar", C: "Michael Jordan", D: "Kobe Bryant" }, dogruCevap: "A" },
    { seviye: 84, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi nedir?", secenekler: { A: "9.58", B: "9.69", C: "9.72", D: "9.80" }, dogruCevap: "A" },
    { seviye: 85, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Japonya", B: "Çin", C: "Güney Kore", D: "Moğolistan" }, dogruCevap: "A" },
    { seviye: 86, kategori: "Spor", soru: "Modern Olimpiyatlar ilk kez nerede yapılmıştır?", secenekler: { A: "Atina", B: "Paris", C: "Londra", D: "Roma" }, dogruCevap: "A" },
    { seviye: 87, kategori: "Spor", soru: "Boksör Muhammed Ali'nin eski adı nedir?", secenekler: { A: "Cassius Clay", B: "Joe Frazier", C: "George Foreman", D: "Mike Tyson" }, dogruCevap: "A" },
    { seviye: 88, kategori: "Spor", soru: "Hangi ülke 2022 Dünya Kupası şampiyonu olmuştur?", secenekler: { A: "Arjantin", B: "Fransa", C: "Hırvatistan", D: "Fas" }, dogruCevap: "A" },
    { seviye: 89, kategori: "Spor", soru: "Teniste bir yıl içinde tüm Grand Slamleri kazanmaya ne denir?", secenekler: { A: "Grand Slam", B: "Golden Slam", C: "Masters", D: "Tie-Break" }, dogruCevap: "A" },
    { seviye: 90, kategori: "Spor", soru: "Olimpiyat meşalesi nerede yakılır?", secenekler: { A: "Olimpiya Dağı", B: "Atina Stadyumu", C: "Ev sahibi şehir", D: "Roma" }, dogruCevap: "A" },
    { seviye: 91, kategori: "Spor", soru: "Futbolda sarı ve kırmızı kart ilk kez hangi yıl kullanıldı?", secenekler: { A: "1970", B: "1966", C: "1974", D: "1960" }, dogruCevap: "A" },
    { seviye: 92, kategori: "Spor", soru: "Michael Phelps hangi branşta rekor madalya sahibidir?", secenekler: { A: "Yüzme", B: "Atletizm", C: "Jimnastik", D: "Kürek" }, dogruCevap: "A" },
    { seviye: 93, kategori: "Spor", soru: "Tour de France (Fransa Bisiklet Turu) lideri hangi renk mayo giyer?", secenekler: { A: "Sarı", B: "Pembe", C: "Kırmızı", D: "Yeşil" }, dogruCevap: "A" },
    { seviye: 94, kategori: "Spor", soru: "Badminton topuna ne ad verilir?", secenekler: { A: "Shuttlecock", B: "Puck", C: "Birdie", D: "A ve C" }, dogruCevap: "D" },
    { seviye: 95, kategori: "Spor", soru: "Amerikan futbolu final maçına ne ad verilir?", secenekler: { A: "Super Bowl", B: "World Series", C: "NBA Finals", D: "Stanley Cup" }, dogruCevap: "A" },
    { seviye: 96, kategori: "Spor", soru: "Eskrimde kullanılan üç silahtan biri?", secenekler: { A: "Flöre", B: "Ok", C: "Mızrak", D: "Süngü" }, dogruCevap: "A" },
    { seviye: 97, kategori: "Spor", soru: "Tiger Woods hangi sporda efsanedir?", secenekler: { A: "Golf", B: "Tenis", C: "Bilardo", D: "Yüzme" }, dogruCevap: "A" },
    { seviye: 98, kategori: "Spor", soru: "Körling (Curling) sporu nerede oynanır?", secenekler: { A: "Buz", B: "Çim", C: "Kum", D: "Su" }, dogruCevap: "A" },
    { seviye: 99, kategori: "Spor", soru: "Dünya Kupası tarihinde en çok gol atan oyuncu?", secenekler: { A: "Miroslav Klose", B: "Ronaldo", C: "Pele", D: "Messi" }, dogruCevap: "A" },
    { seviye: 100, kategori: "Spor", soru: "Satrançta bir maçta yapılabilecek en kısa mat kaç hamledir?", secenekler: { A: "2", B: "3", C: "4", D: "1" }, dogruCevap: "A" }, 
    // 101-150: Karışık Spor Dalları, Rekorlar ve Olimpiyatlar
    { seviye: 101, kategori: "Spor", soru: "Modern Olimpiyat Oyunları ilk kez hangi şehirde düzenlenmiştir?", secenekler: { A: "Atina", B: "Paris", C: "Londra", D: "Roma" }, dogruCevap: "A" },
    { seviye: 102, kategori: "Spor", soru: "Voleybolda sahada her takımdan kaç oyuncu bulunur?", secenekler: { A: "5", B: "6", C: "7", D: "11" }, dogruCevap: "B" },
    { seviye: 103, kategori: "Spor", soru: "Hangi ülke 2022 FIFA Dünya Kupası şampiyonu olmuştur?", secenekler: { A: "Fransa", B: "Brezilya", C: "Arjantin", D: "Fas" }, dogruCevap: "C" },
    { seviye: 104, kategori: "Spor", soru: "Teniste 'Grand Slam' kazanan ilk Türk tenisçi kimdir (Gençler kategorisi)?", secenekler: { A: "İpek Soylu", B: "Marsel İlhan", C: "Çağla Büyükakçay", D: "Melis Sezer" }, dogruCevap: "A" },
    { seviye: 105, kategori: "Spor", soru: "Basketbolda bir periyot NBA standartlarında kaç dakikadır?", secenekler: { A: "10", B: "12", C: "15", D: "8" }, dogruCevap: "B" },
    { seviye: 106, kategori: "Spor", soru: "Hangi spor dalında 'triple-double' terimi kullanılır?", secenekler: { A: "Voleybol", B: "Basketbol", C: "Hentbol", D: "Su Topu" }, dogruCevap: "B" },
    { seviye: 107, kategori: "Spor", soru: "Formula 1 tarihinde en çok şampiyonluk yaşayan iki pilottan biri hangisidir?", secenekler: { A: "Lewis Hamilton", B: "Max Verstappen", C: "Sebastian Vettel", D: "Fernando Alonso" }, dogruCevap: "A" },
    { seviye: 108, kategori: "Spor", soru: "Masa tenisinde bir set kaç sayıda biter?", secenekler: { A: "11", B: "15", C: "21", D: "25" }, dogruCevap: "A" },
    { seviye: 109, kategori: "Spor", soru: "Dünya Kupası'nı hem oyuncu hem teknik direktör olarak kazanan isimlerden biri hangisidir?", secenekler: { A: "Didier Deschamps", B: "Zinedine Zidane", C: "Diego Maradona", D: "Pele" }, dogruCevap: "A" },
    { seviye: 110, kategori: "Spor", soru: "Bisiklet sporunda dünyanın en prestijli yarışı hangisidir?", secenekler: { A: "Tour de France", B: "Giro d'Italia", C: "Vuelta a España", D: "Tour of Türkiye" }, dogruCevap: "A" },
    { seviye: 111, kategori: "Spor", soru: "2024 Olimpiyat Oyunları hangi şehirde düzenlenecektir?", secenekler: { A: "Tokyo", B: "Paris", C: "Los Angeles", D: "Brisbane" }, dogruCevap: "B" },
    { seviye: 112, kategori: "Spor", soru: "Hangi branş 'sporların anası' olarak kabul edilir?", secenekler: { A: "Yüzme", B: "Atletizm", C: "Jimnastik", D: "Güreş" }, dogruCevap: "B" },
    { seviye: 113, kategori: "Spor", soru: "Snooker (Bilardo) oyununda en yüksek puanlı top hangi renktir?", secenekler: { A: "Mavi", B: "Pembe", C: "Siyah", D: "Kırmızı" }, dogruCevap: "C" },
    { seviye: 114, kategori: "Spor", soru: "Türkiye'nin olimpiyatlarda kazandığı ilk altın madalya hangi branştadır?", secenekler: { A: "Güreş", B: "Halter", C: "Okçuluk", D: "Boks" }, dogruCevap: "A" },
    { seviye: 115, kategori: "Spor", soru: "NBA'de tüm zamanların en çok sayı atan oyuncusu kimdir?", secenekler: { A: "Kareem Abdul-Jabbar", B: "Michael Jordan", C: "LeBron James", D: "Kobe Bryant" }, dogruCevap: "C" },
    { seviye: 116, kategori: "Spor", soru: "Hentbolda bir maç kaç dakikadır?", secenekler: { A: "40", B: "50", C: "60", D: "90" }, dogruCevap: "C" },
    { seviye: 117, kategori: "Spor", soru: "Yüzmede 'kelebek' stili kaç metrelik yarışlarda başlar?", secenekler: { A: "50", B: "100", C: "200", D: "400" }, dogruCevap: "A" },
    { seviye: 118, kategori: "Spor", soru: "Dünya ağır sıklet boks şampiyonu 'Iron' lakaplı sporcu kimdir?", secenekler: { A: "Muhammad Ali", B: "Mike Tyson", C: "Anthony Joshua", D: "Tyson Fury" }, dogruCevap: "B" },
    { seviye: 119, kategori: "Spor", soru: "Voleybolda savunma oyuncusuna (farklı renk forma giyen) ne ad verilir?", secenekler: { A: "Libero", B: "Pasör", C: "Smaçör", D: "Orta Oyuncu" }, dogruCevap: "A" },
    { seviye: 120, kategori: "Spor", soru: "Buz hokeyinde oyunun oynandığı diske ne ad verilir?", secenekler: { A: "Top", B: "Puck", C: "Mermer", D: "Küre" }, dogruCevap: "B" },
    { seviye: 121, kategori: "Spor", soru: "Wimbledon Tenis Turnuvası hangi zemin üzerinde oynanır?", secenekler: { A: "Toprak", B: "Çim", C: "Sert", D: "Halı" }, dogruCevap: "B" },
    { seviye: 122, kategori: "Spor", soru: "Bir maraton koşusu tam olarak kaç kilometredir?", secenekler: { A: "42.195", B: "40", C: "45", D: "38.5" }, dogruCevap: "A" },
    { seviye: 123, kategori: "Spor", soru: "Okçulukta hedefin tam ortasına (10 puan) ne ad verilir?", secenekler: { A: "Göz", B: "Onluk", C: "Merkez", D: "Bulls-eye" }, dogruCevap: "D" },
    { seviye: 124, kategori: "Spor", soru: "Satrançta en güçlü taş hangisidir?", secenekler: { A: "Şah", B: "Vezir", C: "Kale", D: "At" }, dogruCevap: "B" },
    { seviye: 125, kategori: "Spor", soru: "Kış Olimpiyatları kaç yılda bir düzenlenir?", secenekler: { A: "2", B: "3", C: "4", D: "5" }, dogruCevap: "C" },
    { seviye: 126, kategori: "Spor", soru: "Brezilyalı efsane futbolcu Pele kaç kez Dünya Kupası kazanmıştır?", secenekler: { A: "1", B: "2", C: "3", D: "4" }, dogruCevap: "C" },
    { seviye: 127, kategori: "Spor", soru: "NBA takımlarından Chicago Bulls'un efsanevi 23 numaralı oyuncusu kimdir?", secenekler: { A: "Michael Jordan", B: "Scottie Pippen", C: "Dennis Rodman", D: "Derrick Rose" }, dogruCevap: "A" },
    { seviye: 128, kategori: "Spor", soru: "Sumo güreşi hangi ülkenin milli sporudur?", secenekler: { A: "Çin", B: "Japonya", C: "Güney Kore", D: "Tayland" }, dogruCevap: "B" },
    { seviye: 129, kategori: "Spor", soru: "Golfte topun deliğe girmesi için yapılan son vuruşa ne denir?", secenekler: { A: "Drive", B: "Swing", C: "Putt", D: "Chip" }, dogruCevap: "C" },
    { seviye: 130, kategori: "Spor", soru: "2008 Pekin Olimpiyatları'nda 8 altın madalya kazanan efsane yüzücü kimdir?", secenekler: { A: "Michael Phelps", B: "Ian Thorpe", C: "Ryan Lochte", D: "Caeleb Dressel" }, dogruCevap: "A" },
    { seviye: 131, kategori: "Spor", soru: "Hangi futbolcu daha fazla Ballon d'Or ödülüne sahiptir?", secenekler: { A: "Lionel Messi", B: "Cristiano Ronaldo", C: "Johan Cruyff", D: "Michel Platini" }, dogruCevap: "A" },
    { seviye: 132, kategori: "Spor", soru: "Eskrimde hangi silah türü tüm vücudu hedef olarak kabul eder?", secenekler: { A: "Flöre", B: "Epe", C: "Sable", D: "Kılıç" }, dogruCevap: "B" },
    { seviye: 133, kategori: "Spor", soru: "Türkiye'nin ilk yerli yarış otomobilinin adı nedir?", secenekler: { A: "Anadol", B: "Devrim", C: "Etox", D: "Volkicar" }, dogruCevap: "D" },
    { seviye: 134, kategori: "Spor", soru: "Hangi branşta 'smaç' terimi kullanılmaz?", secenekler: { A: "Voleybol", B: "Basketbol", C: "Tenis", D: "Futbol" }, dogruCevap: "D" },
    { seviye: 135, kategori: "Spor", soru: "Beyzbolda bir takımın tüm kaleleri dolaşarak kazandığı puana ne denir?", secenekler: { A: "Home Run", B: "Touchdown", C: "Goal", D: "Strike" }, dogruCevap: "A" },
    { seviye: 136, kategori: "Spor", soru: "Amerikan Futbolu'nda bir 'Touchdown' kaç puandır?", secenekler: { A: "3", B: "6", C: "7", D: "2" }, dogruCevap: "B" },
    { seviye: 137, kategori: "Spor", soru: "Hangi tenis turnuvası 'Toprak Kortun Kralı' olarak bilinen Rafael Nadal ile özdeşleşmiştir?", secenekler: { A: "Roland Garros", B: "Australian Open", C: "US Open", D: "Wimbledon" }, dogruCevap: "A" },
    { seviye: 138, kategori: "Spor", soru: "Bowlingde tüm lobutları tek seferde devirmeye ne denir?", secenekler: { A: "Spare", B: "Strike", C: "Split", D: "Perfect" }, dogruCevap: "B" },
    { seviye: 139, kategori: "Spor", soru: "Hangi ülke futbol milli takımı 'Gök Mavililer' (Azzurri) lakabıyla anılır?", secenekler: { A: "İtalya", B: "Fransa", C: "Arjantin", D: "Uruguay" }, dogruCevap: "A" },
    { seviye: 140, kategori: "Spor", soru: "Su topunda bir takım kaleci dahil kaç oyuncudan oluşur?", secenekler: { A: "6", B: "7", C: "8", D: "11" }, dogruCevap: "B" },
    { seviye: 141, kategori: "Spor", soru: "Körling (Curling) sporu nerede oynanır?", secenekler: { A: "Çim", B: "Kum", C: "Buz", D: "Su" }, dogruCevap: "C" },
    { seviye: 142, kategori: "Spor", soru: "Usain Bolt'un 100 metre dünya rekoru derecesi kaçtır?", secenekler: { A: "9.58", B: "9.69", C: "9.72", D: "9.81" }, dogruCevap: "A" },
    { seviye: 143, kategori: "Spor", soru: "Hangi branşta 'servis' ile oyuna başlanmaz?", secenekler: { A: "Voleybol", B: "Tenis", C: "Badminton", D: "Basketbol" }, dogruCevap: "D" },
    { seviye: 144, kategori: "Spor", soru: "Jimnastikte denge aleti üzerinde hangi sporcular yarışır?", secenekler: { A: "Sadece Erkekler", B: "Sadece Kadınlar", C: "Hem Erkek hem Kadın", D: "Karma Takımlar" }, dogruCevap: "B" },
    { seviye: 145, kategori: "Spor", soru: "Türkiye'nin Avrupa Şampiyonu olan Kadın Voleybol Milli Takımı'nın lakabı?", secenekler: { A: "Filenin Sultanları", B: "Potanın Perileri", C: "Demir Pençeler", D: "Altın Kızlar" }, dogruCevap: "A" },
    { seviye: 146, kategori: "Spor", soru: "Bir boks maçında nakavt için hakem kaça kadar sayar?", secenekler: { A: "5", B: "8", C: "10", D: "12" }, dogruCevap: "C" },
    { seviye: 147, kategori: "Spor", soru: "Hangi ülke Ragbi sporunun ana vatanı kabul edilir?", secenekler: { A: "ABD", B: "İngiltere", C: "Yeni Zelanda", D: "Avustralya" }, dogruCevap: "B" },
    { seviye: 148, kategori: "Spor", soru: "Bilardoda beyaz topa vurulan sopaya ne denir?", secenekler: { A: "Istaka", B: "Raket", C: "Sopa", D: "Kulüp" }, dogruCevap: "A" },
    { seviye: 149, kategori: "Spor", soru: "Mete Gazoz hangi branşta Olimpiyat Şampiyonu olmuştur?", secenekler: { A: "Jimnastik", B: "Okçuluk", C: "Atıcılık", D: "Eskrim" }, dogruCevap: "B" },
    { seviye: 150, kategori: "Spor", soru: "Hangi spor dalında 'ofsait' kuralı yoktur?", secenekler: { A: "Futbol", B: "Buz Hokeyi", C: "Basketbol", D: "Çim Hokeyi" }, dogruCevap: "C" }

);
 