window.tumSorular = window.tumSorular || [];

window.tumSorular.push(
   // --- TÜRK TARİHİ ÖZEL SETİ (100 SORU) ---

// İslamiyet Öncesi Türk Devletleri (1-20)
{ kategori: "Tarih", seviye: 2, soru: "Tarihte bilinen ilk Türk devleti hangisidir?", secenekler: { A: "Göktürkler", B: "Asya Hun Devleti", C: "Uygurlar", D: "İskitler" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 3, soru: "Asya Hun Devleti'nin en parlak dönemini yaşatan hükümdar kimdir?", secenekler: { A: "Teoman", B: "Mete Han", C: "Attila", D: "Bumin Kağan" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 5, soru: "Onlu sistem adı verilen askeri teşkilatı ilk kuran Türk hükümdarı kimdir?", secenekler: { A: "Mete Han", B: "Kültigin", C: "Bilge Kağan", D: "Alp Er Tunga" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Avrupa'da devlet kuran ve 'Tanrı'nın Kırbacı' lakabıyla anılan Türk hükümdarı kimdir?", secenekler: { A: "Balamir", B: "Uldız", C: "Attila", D: "Rua" }, dogruCevap: "C" },
{ kategori: "Tarih", seviye: 5, soru: "Türk adıyla kurulan ilk Türk devleti hangisidir?", secenekler: { A: "Uygurlar", B: "Kök Türkler", C: "Hazarlar", D: "Karahanlılar" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 6, soru: "Türk tarihinin ilk yazılı belgeleri olan Orhun Abideleri hangi devlet döneminde dikilmiştir?", secenekler: { A: "I. Kök Türk", B: "II. Kök Türk", C: "Uygur", D: "Kırgız" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 6, soru: "Maniheizm dinini kabul ederek yerleşik hayata geçen ilk Türk devleti hangisidir?", secenekler: { A: "Uygurlar", B: "Akhunlar", C: "Karluklar", D: "Peçenekler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Museviliği kabul eden tek Türk devleti hangisidir?", secenekler: { A: "Hazarlar", B: "Bulgarlar", C: "Macarlar", D: "Kumanlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Tarihte 'Bozkırın Kuyumcuları' olarak bilinen topluluk hangisidir?", secenekler: { A: "İskitler (Sakalar)", B: "Sarmatlar", C: "Oğuzlar", D: "Başkurtlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Kendi adına para bastıran ilk Türk hükümdarı kimdir (Türgişler)?", secenekler: { A: "Baga Tarkan", B: "Sulun Kağan", C: "Mukan Kağan", D: "Tapu Kağan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İstanbul'u kuşatan ilk Türk devleti hangisidir?", secenekler: { A: "Avarlar", B: "Peçenekler", C: "Hunlar", D: "Sabirler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Manas Destanı hangi Türk topluluğuna aittir?", secenekler: { A: "Kırgızlar", B: "Kazaklar", C: "Tatarlar", D: "Özbekler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "İslamiyet öncesi Türk devletlerinde devlet meselelerinin görüşüldüğü meclise ne ad verilirdi?", secenekler: { A: "Kurultay", B: "Divan", C: "Pankuş", D: "Şura" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Eski Türklerde hükümdara yönetme yetkisinin Tanrı tarafından verilmesi inancına ne denir?", secenekler: { A: "Kut", B: "Cihan Hakimiyeti", C: "Töre", D: "Veraset" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "İslamiyet öncesi Türklerde ölen kişiler için yapılan cenaze törenine ne ad verilir?", secenekler: { A: "Yuğ", B: "Kurgan", C: "Balbal", D: "Kam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "İlk Türk kadın hükümdar olarak kabul edilen Tomris Hatun hangi topluluğun lideridir?", secenekler: { A: "İskitler", B: "Amazonlar", C: "Hunlar", D: "Uygurlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Orhun Abideleri'nde söylevleri yer alan ünlü Türk veziri kimdir?", secenekler: { A: "Tonyukuk", B: "Nizamülmülk", C: "Pargalı İbrahim", D: "Sokullu Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türklerde ölen kişilerin mezarlarının başına dikilen heykelciklere ne ad verilir?", secenekler: { A: "Balbal", B: "Stupa", C: "Kurgan", D: "Kümbet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Eski Türklerde göçebe yaşam tarzına bağlı olarak gelişen en önemli sanat dalı hangisidir?", secenekler: { A: "Dokumacılık", B: "Mimari", C: "Heykel", D: "Fresk" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Hangi Türk devleti Karadeniz'in kuzeyinin Türkleşmesinde etkili olmuştur?", secenekler: { A: "İtil Bulgarları", B: "Akhunlar", C: "Tabgaçlar", D: "Kimekler" }, dogruCevap: "A" },

// İlk Müslüman Türk Devletleri ve Selçuklular (21-40)
{ kategori: "Tarih", seviye: 5, soru: "Orta Asya'da kurulan ilk Müslüman Türk devleti hangisidir?", secenekler: { A: "Karahanlılar", B: "Gazneliler", C: "Samanoğulları", D: "Büyük Selçuklular" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Gazneli Mahmut'un 'Sarayımın en değerli hazinesi' dediği ünlü bilim insanı kimdir?", secenekler: { A: "Biruni", B: "İbn-i Sina", C: "Farabi", D: "Harezmi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Büyük Selçuklu Devleti'nin resmen kurulduğu kabul edilen 1040 tarihli savaş hangisidir?", secenekler: { A: "Dandanakan", B: "Pasinler", C: "Malazgirt", D: "Katvan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Sultan Alp Arslan döneminde Bizans'a karşı kazanılan 'Yurt Açan' savaş hangisidir?", secenekler: { A: "Malazgirt", B: "Miryokefalon", C: "Kösedağ", D: "Yassıçemen" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Selçukluların en parlak dönemini yaşatan ve 'Sultanü'l-Azam' lakabıyla bilinen hükümdar kimdir?", secenekler: { A: "Melikşah", B: "Tuğrul Bey", C: "Berkyaruk", D: "Sultan Sencer" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Anadolu Selçuklu Devleti'nin kurucusu kimdir?", secenekler: { A: "Süleyman Şah", B: "I. Mesut", C: "II. Kılıç Arslan", D: "Alaeddin Keykubad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Anadolu'nun kesin olarak Türk yurdu olduğunu kanıtlayan 1176 tarihli savaş hangisidir?", secenekler: { A: "Miryokefalon", B: "Malazgirt", C: "Pasinler", D: "Koyunhisar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Anadolu Selçuklu Devleti'nin en parlak dönemi hangi hükümdar zamanıdır?", secenekler: { A: "I. Alaeddin Keykubad", B: "I. Gıyaseddin Keyhüsrev", C: "II. Kılıç Arslan", D: "I. İzzettin Keykavus" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Anadolu Selçuklu Devleti'nin Moğollara yenilerek yıkılış sürecine girdiği savaş hangisidir?", secenekler: { A: "Kösedağ", B: "Ayn Calut", C: "Otlukbeli", D: "Yassıçemen" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk tarihinin ilk dini ve sosyal nitelikli isyanı hangisidir (Anadolu Selçuklu)?", secenekler: { A: "Babailer İsyanı", B: "Şahkulu İsyanı", C: "Şeyh Bedrettin", D: "Baba Zünnun" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Mısır'da kurulan ilk Türk-İslam devleti hangisidir?", secenekler: { A: "Tolunoğulları", B: "İhşidiler", C: "Eyyubiler", D: "Memlükler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Hangi devlet Moğolları tarihte ilk kez durdurmayı başarmıştır (Ayn Calut Savaşı)?", secenekler: { A: "Memlükler", B: "Eyyubiler", C: "Harzemşahlar", D: "Büyük Selçuklular" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Kudüz'u Haçlılardan geri alan (Hıttin Savaşı) ünlü Türk-İslam komutanı kimdir?", secenekler: { A: "Selahaddin Eyyubi", B: "Baybars", C: "Nureddin Zengi", D: "Kılıç Arslan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Büyük Selçuklularda vezirlik yapan ve 'Siyasetname' eserini yazan kişi kimdir?", secenekler: { A: "Nizamülmülk", B: "Hoca Dehhani", C: "İdris-i Bitlisi", D: "Gazali" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk-İslam devletlerinde çarşı ve pazar esnafını denetleyen görevliye ne denir?", secenekler: { A: "Muhtesip", B: "Müşrif", C: "Kadı", D: "Şıhne" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Anadolu'da Türkçe'yi resmi dil ilan eden ilk beylik hangisidir?", secenekler: { A: "Karamanoğulları", B: "Germiyanoğulları", C: "Karesioğulları", D: "Menteşeoğulları" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Karahanlılar döneminde yazılan, mutluluk veren bilgi anlamına gelen eser hangisidir?", secenekler: { A: "Kutadgu Bilig", B: "Atabetü'l Hakayık", C: "Divân-ı Hikmet", D: "Siyasetname" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Sultan Alparslan'ın mezarı hangi şehirdedir?", secenekler: { A: "Merv", B: "Nişabur", C: "Rey", D: "İsfahan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Selçuklularda 'Melik'lerin eğitiminden sorumlu kişiye ne ad verilir?", secenekler: { A: "Atabey", B: "Lala", C: "Naib", D: "Hacip" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Anadolu'da kurulan ilk Türk beyliği hangisidir?", secenekler: { A: "Saltuklular", B: "Danişmentliler", C: "Mengücekliler", D: "Artuklular" }, dogruCevap: "A" },

// Osmanlı Devleti - Kuruluş ve Yükselme (41-65)
{ kategori: "Tarih", seviye: 3, soru: "Osmanlı Devleti'nin kurucusu olan Osman Bey'in babası kimdir?", secenekler: { A: "Ertuğrul Gazi", B: "Gündüz Alp", C: "Hayme Ana", D: "Süleyman Şah" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nin Bizans ile yaptığı ilk savaş hangisidir?", secenekler: { A: "Koyunhisar (Bafeus)", B: "Maltepe (Palekanon)", C: "Sazlıdere", D: "Niğbolu" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "İlk Osmanlı parası ve ilk vergi uygulaması hangi padişah dönemindedir?", secenekler: { A: "Osman Bey", B: "Orhan Bey", C: "I. Murat", D: "Yıldırım Bayezid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Bursa'yı fethederek başkent yapan ve Yaya-Müsellem ordusunu kuran padişah kimdir?", secenekler: { A: "Orhan Bey", B: "Osman Bey", C: "Çelebi Mehmet", D: "II. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'nın Rumeli'deki ilk toprak parçası olan kale hangisidir?", secenekler: { A: "Çimpe Kalesi", B: "Gelibolu", C: "Edirne", D: "Belgrad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Savaş meydanında şehit edilen tek Osmanlı padişahı hangisidir?", secenekler: { A: "I. Murat", B: "II. Murat", C: "Genç Osman", D: "IV. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "1402 Ankara Savaşı'nda Timur'a esir düşen Osmanlı padişahı kimdir?", secenekler: { A: "Yıldırım Bayezid", B: "I. Mehmet", C: "II. Murat", D: "II. Bayezid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nin 'İkinci Kurucusu' sayılan padişah kimdir?", secenekler: { A: "Çelebi Mehmet", B: "II. Murat", C: "Fatih Sultan Mehmet", D: "Yavuz Sultan Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İstanbul kuşatması için Anadolu Hisarı'nı (Güzelcehisar) yaptıran padişah kimdir?", secenekler: { A: "Yıldırım Bayezid", B: "Fatih Sultan Mehmet", C: "II. Murat", D: "Orhan Bey" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "İstanbul fethedildikten sonra Fatih Sultan Mehmet'e verilen unvan hangisidir?", secenekler: { A: "Kayzer-i Rum", B: "Hadimü’l-Harameyn", C: "Halife", D: "Sultan-ı İklim-i Rum" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Fatih Sultan Mehmet'in kuşatıp da alamadığı, Kanuni'nin fethettiği yer neresidir?", secenekler: { A: "Belgrad", B: "Rodos", C: "Viyana", D: "Malta" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Sekiz yıla seksen yıllık iş sığdıran, halifeliği Osmanlı'ya getiren padişah kimdir?", secenekler: { A: "Yavuz Sultan Selim", B: "Kanuni Sultan Süleyman", C: "II. Selim", D: "III. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Dünya tarihinin en kısa süren (2 saat) meydan savaşı hangisidir?", secenekler: { A: "Mohaç Meydan Muharebesi", B: "Çaldıran Savaşı", C: "Ridaniye Savaşı", D: "Preveze" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "28 Eylül Türk Denizcilik Günü olarak kutlanan zafer hangisidir?", secenekler: { A: "Preveze Deniz Zaferi", B: "İnebahtı", C: "Cerbe Deniz Savaşı", D: "Navarin" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı Devleti'nde sadrazamlık makamı ilk kez hangi padişah döneminde kurulmuştur?", secenekler: { A: "I. Murat", B: "Orhan Bey", C: "Osman Bey", D: "II. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı'nın devlet işlerinin görüşüldüğü 'Divan-ı Hümayun'u kuran padişah kimdir?", secenekler: { A: "Orhan Bey", B: "Osman Bey", C: "I. Murat", D: "Fatih Sultan Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Yeniçeri Ocağı'nın temelini oluşturan sistem hangisidir?", secenekler: { A: "Pençik ve Devşirme", B: "Tımar Sistemi", C: "İltizam", D: "Malikane" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Padişahın çocuklarına (Şehzadelere) ders veren hocalara ne ad verilir?", secenekler: { A: "Lala", B: "Müderris", C: "Kadı", D: "Nişancı" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'da sınır boylarında yaşayan ve keşif yapan hafif süvari birliğine ne denir?", secenekler: { A: "Akıncılar", B: "Sipahiler", C: "Yeniçeriler", D: "Lağımcılar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı Devleti'nde dış yazışmalardan ve tapu kayıtlarından sorumlu görevli kimdir?", secenekler: { A: "Nişancı", B: "Reisü'l-Küttab", C: "Defterdar", D: "Kazasker" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Osmanlı'nın Avusturya üzerinde siyasi üstünlük kurduğu (Arşidükün sadrazama denk sayıldığı) antlaşma?", secenekler: { A: "İstanbul Antlaşması (1533)", B: "Zitvatorok", C: "Karlofça", D: "Pasarofça" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Fatih döneminde inşa edilen ve devletin yönetim merkezi olan saray hangisidir?", secenekler: { A: "Topkapı Sarayı", B: "Dolmabahçe Sarayı", C: "Çırağan", D: "Yıldız" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Hangi Osmanlı padişahı 'Avni' mahlasıyla şiirler yazmıştır?", secenekler: { A: "Fatih Sultan Mehmet", B: "Kanuni", C: "II. Mahmud", D: "Yavuz Sultan Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Preveze Deniz Zaferi'ni kazanan ünlü Osmanlı kaptan-ı deryası kimdir?", secenekler: { A: "Barbaros Hayrettin Paşa", B: "Piri Reis", C: "Turgut Reis", D: "Kılıç Ali Paşa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Dünya haritasını çizen ve Kitab-ı Bahriye eserini yazan ünlü denizci kimdir?", secenekler: { A: "Piri Reis", B: "Seydi Ali Reis", C: "Kemal Reis", D: "Murat Reis" }, dogruCevap: "A" },

// Osmanlı - Duraklama, Gerileme ve Dağılma (66-85)
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı Devleti'nin Batı'da en geniş sınırlara ulaştığı antlaşma hangisidir?", secenekler: { A: "Bucaş Antlaşması", B: "Ferhat Paşa", C: "Nasuh Paşa", D: "Serav" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı'nın Avusturya karşısındaki siyasi üstünlüğünü kaybettiği (Padişahın Arşidüke denk sayıldığı) antlaşma?", secenekler: { A: "Zitvatorok Antlaşması", B: "Karlofça", C: "Vasvar", D: "İstanbul (1700)" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı'da 'Vaka-i Vakvakiye' (Çınar Vakası) hangi padişah döneminde yaşanmıştır?", secenekler: { A: "IV. Mehmet", B: "II. Osman", C: "IV. Murad", D: "I. İbrahim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Osmanlı'da ilk kez bütçe planlaması yapan (modern bütçe) devlet adamı kimdir?", secenekler: { A: "Tarhuncu Ahmed Paşa", B: "Köprülü Mehmet Paşa", C: "Merzifonlu Kara Mustafa", D: "Baltacı Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı'nın büyük çapta toprak kaybettiği ilk antlaşma hangisidir?", secenekler: { A: "Karlofça Antlaşması", B: "Pasarofça", C: "Küçük Kaynarca", D: "Yaş" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nde Lale Devri'ni bitiren isyan hangisidir?", secenekler: { A: "Patrona Halil İsyanı", B: "Kabakçı Mustafa", C: "Celali İsyanları", D: "Canberdi Gazali" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Lale Devri'nin en ünlü minyatür sanatçısı kimdir?", secenekler: { A: "Levni", B: "Nigari", C: "Matrakçı Nasuh", D: "Şeker Ahmet Paşa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Osmanlı'nın Avrupa tarzında kurduğu ilk ordu hangisidir?", secenekler: { A: "Nizam-ı Cedid", B: "Sekban-ı Cedid", C: "Eşkinci Ocağı", D: "Asakir-i Mansure-i Muhammediye" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Yeniçeri Ocağı'nı kaldıran (Vaka-i Hayriye) padişah kimdir?", secenekler: { A: "II. Mahmud", B: "III. Selim", C: "Abdülmecid", D: "II. Abdülhamid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Osmanlı'da anayasal düzene geçişin ilk adımı sayılan 1839 tarihli belge hangisidir?", secenekler: { A: "Tanzimat Fermanı", B: "Islahat Fermanı", C: "Sened-i İttifak", D: "Kanun-i Esasi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı Devleti'nin ilk anayasası hangisidir?", secenekler: { A: "Kanun-i Esasi", B: "Teşkilat-ı Esasiye", C: "Gülhane Hatt-ı Hümayunu", D: "Bab-ı Ali Baskını" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı'nın 'Hasta Adam' olarak nitelendirildiği ilk yer neresidir?", secenekler: { A: "Rusya", B: "İngiltere", C: "Fransa", D: "Avusturya" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Kırım Savaşı sırasında 'Hemşireliğin Kurucusu' sayılan ve İstanbul'da çalışan kişi kimdir?", secenekler: { A: "Florence Nightingale", B: "Madame Curie", C: "Sabiha Gökçen", D: "Halide Edip" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı'da ilk kez telgraf hattı hangi savaş sırasında kurulmuştur?", secenekler: { A: "Kırım Savaşı", B: "93 Harbi", C: "Dömeke", D: "Trablusgarp" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı Devleti'nde ilk kağıt para (Kaime) hangi padişah döneminde basılmıştır?", secenekler: { A: "Sultan Abdülmecid", B: "II. Mahmud", C: "III. Selim", D: "Sultan Abdülaziz" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "31 Mart Vakası sonucunda tahttan indirilen padişah kimdir?", secenekler: { A: "II. Abdülhamid", B: "V. Mehmed Reşad", C: "Sultan Abdülaziz", D: "V. Murad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı'nın Kuzey Afrika'daki son toprak parçasını (Libya) kaybettiği antlaşma?", secenekler: { A: "Uşi Antlaşması", B: "Londra", C: "Bükreş", D: "Atina" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Çanakkale Savaşları'nda 215 kg'lık mermiyi sırtlayan kahraman kimdir?", secenekler: { A: "Seyit Onbaşı", B: "Yahya Çavuş", C: "Nene Hatun", D: "Sütçü İmam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "I. Dünya Savaşı'nda Osmanlı'nın kazandığı tek taarruz cephesi hangisidir?", secenekler: { A: "Kafkas Cephesi (Muş ve Bitlis geri alındı)", B: "Kanal Cephesi", C: "Irak", D: "Hicaz-Yemen" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Mondros Mütarekesi'ni Osmanlı adına imzalayan devlet adamı kimdir?", secenekler: { A: "Rauf Orbay", B: "Damat Ferit", C: "Ali Rıza Paşa", D: "Talat Paşa" }, dogruCevap: "A" },

// Milli Mücadele ve Cumhuriyet Tarihi (86-100)
{ kategori: "Tarih", seviye: 3, soru: "Atatürk'ün 'Geldikleri gibi giderler' sözünü söylediği yer neresidir?", secenekler: { A: "İstanbul", B: "Samsun", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Kurtuluş Savaşı'nın gerekçesi, amacı ve yöntemi ilk kez nerede belirtilmiştir?", secenekler: { A: "Amasya Tamimi", B: "Havza Genelgesi", C: "Erzurum Kongresi", D: "Sivas Kongresi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Milli sınırların (Misak-ı Milli) ilk kez bahsedildiği kongre hangisidir?", secenekler: { A: "Erzurum Kongresi", B: "Sivas", C: "Amasya", D: "Balıkesir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Milli Mücadele'nin haklılığını kanıtlayan ilk uluslararası rapor hangisidir?", secenekler: { A: "Amiral Bristol Raporu", B: "General Harbourd", C: "Milne Hattı", D: "Sandler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "TBMM'nin imzaladığı ilk siyasi antlaşma (Ermenistan ile) hangisidir?", secenekler: { A: "Gümrü Antlaşması", B: "Kars", C: "Moskova", D: "Ankara" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "İstiklal Marşı hangi savaşın kazanılmasından sonra kabul edilmiştir?", secenekler: { A: "I. İnönü Savaşı", B: "II. İnönü", C: "Sakarya", D: "Büyük Taarruz" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Atatürk'e 'Gazi' unvanı ve 'Mareşal' rütbesi hangi savaştan sonra verilmiştir?", secenekler: { A: "Sakarya Meydan Muharebesi", B: "Büyük Taarruz", C: "Çanakkale", D: "Trablusgarp" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Saltanat hangi tarihte kaldırılmıştır?", secenekler: { A: "1 Kasım 1922", B: "29 Ekim 1923", C: "3 Mart 1924", D: "23 Nisan 1920" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Yeni Türk devletinin tapusu sayılan antlaşma hangisidir?", secenekler: { A: "Lozan Antlaşması", B: "Sevr", C: "Montrö", D: "Mudanya" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Cumhuriyetin ilanından sonra ilk Başbakan kimdir?", secenekler: { A: "İsmet İnönü", B: "Ali Fethi Okyar", C: "Celal Bayar", D: "Adnan Menderes" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk kadınına seçme ve seçilme hakkı tam olarak hangi yıl verilmiştir?", secenekler: { A: "1934", B: "1930", C: "1923", D: "1945" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Boğazlar üzerinde tam hakimiyet sağladığımız antlaşma hangisidir?", secenekler: { A: "Montrö Boğazlar Sözleşmesi", B: "Lozan", C: "Londra", D: "Paris" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Atatürk'ün naaşı Etnoğrafya Müzesi'nden Anıtkabir'e hangi yıl nakledilmiştir?", secenekler: { A: "1953", B: "1938", C: "1945", D: "1960" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Cumhuriyet döneminin ilk muhalefet partisi hangisidir?", secenekler: { A: "Terakkiperver Cumhuriyet Fırkası", B: "Serbest Cumhuriyet Fırkası", C: "Demokrat Parti", D: "Millet Partisi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Atatürk Dönemi'nde Türkiye'nin üye olduğu ilk uluslararası kuruluş hangisidir?", secenekler: { A: "Milletler Cemiyeti", B: "Birleşmiş Milletler", C: "Sadabat Paktı", D: "Balkan Antantı" }, dogruCevap: "A" }, 

   // --- TÜRK TARİHİ ÖZEL SETİ (300 SORU) ---

// İslamiyet Öncesi Türk Devletleri (1-20)
{ kategori: "Tarih", seviye: 2, soru: "Tarihte bilinen ilk Türk devleti hangisidir?", secenekler: { A: "Göktürkler", B: "Asya Hun Devleti", C: "Uygurlar", D: "İskitler" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 3, soru: "Asya Hun Devleti'nin en parlak dönemini yaşatan hükümdar kimdir?", secenekler: { A: "Teoman", B: "Mete Han", C: "Attila", D: "Bumin Kağan" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 5, soru: "Onlu sistem adı verilen askeri teşkilatı ilk kuran Türk hükümdarı kimdir?", secenekler: { A: "Mete Han", B: "Kültigin", C: "Bilge Kağan", D: "Alp Er Tunga" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Avrupa'da devlet kuran ve 'Tanrı'nın Kırbacı' lakabıyla anılan Türk hükümdarı kimdir?", secenekler: { A: "Balamir", B: "Uldız", C: "Attila", D: "Rua" }, dogruCevap: "C" },
{ kategori: "Tarih", seviye: 5, soru: "Türk adıyla kurulan ilk Türk devleti hangisidir?", secenekler: { A: "Uygurlar", B: "Kök Türkler", C: "Hazarlar", D: "Karahanlılar" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 6, soru: "Türk tarihinin ilk yazılı belgeleri olan Orhun Abideleri hangi devlet döneminde dikilmiştir?", secenekler: { A: "I. Kök Türk", B: "II. Kök Türk", C: "Uygur", D: "Kırgız" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 6, soru: "Maniheizm dinini kabul ederek yerleşik hayata geçen ilk Türk devleti hangisidir?", secenekler: { A: "Uygurlar", B: "Akhunlar", C: "Karluklar", D: "Peçenekler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Museviliği kabul eden tek Türk devleti hangisidir?", secenekler: { A: "Hazarlar", B: "Bulgarlar", C: "Macarlar", D: "Kumanlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Tarihte 'Bozkırın Kuyumcuları' olarak bilinen topluluk hangisidir?", secenekler: { A: "İskitler (Sakalar)", B: "Sarmatlar", C: "Oğuzlar", D: "Başkurtlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Kendi adına para bastıran ilk Türk hükümdarı kimdir (Türgişler)?", secenekler: { A: "Baga Tarkan", B: "Sulun Kağan", C: "Mukan Kağan", D: "Tapu Kağan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İstanbul'u kuşatan ilk Türk devleti hangisidir?", secenekler: { A: "Avarlar", B: "Peçenekler", C: "Hunlar", D: "Sabirler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Manas Destanı hangi Türk topluluğuna aittir?", secenekler: { A: "Kırgızlar", B: "Kazaklar", C: "Tatarlar", D: "Özbekler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "İslamiyet öncesi Türk devletlerinde devlet meselelerinin görüşüldüğü meclise ne ad verilirdi?", secenekler: { A: "Kurultay", B: "Divan", C: "Pankuş", D: "Şura" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Eski Türklerde hükümdara yönetme yetkisinin Tanrı tarafından verilmesi inancına ne denir?", secenekler: { A: "Kut", B: "Cihan Hakimiyeti", C: "Töre", D: "Veraset" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "İslamiyet öncesi Türklerde ölen kişiler için yapılan cenaze törenine ne ad verilir?", secenekler: { A: "Yuğ", B: "Kurgan", C: "Balbal", D: "Kam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "İlk Türk kadın hükümdar olarak kabul edilen Tomris Hatun hangi topluluğun lideridir?", secenekler: { A: "İskitler", B: "Amazonlar", C: "Hunlar", D: "Uygurlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Orhun Abideleri'nde söylevleri yer alan ünlü Türk veziri kimdir?", secenekler: { A: "Tonyukuk", B: "Nizamülmülk", C: "Pargalı İbrahim", D: "Sokullu Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türklerde ölen kişilerin mezarlarının başına dikilen heykelciklere ne ad verilir?", secenekler: { A: "Balbal", B: "Stupa", C: "Kurgan", D: "Kümbet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Eski Türklerde göçebe yaşam tarzına bağlı olarak gelişen en önemli sanat dalı hangisidir?", secenekler: { A: "Dokumacılık", B: "Mimari", C: "Heykel", D: "Fresk" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Hangi Türk devleti Karadeniz'in kuzeyinin Türkleşmesinde etkili olmuştur?", secenekler: { A: "İtil Bulgarları", B: "Akhunlar", C: "Tabgaçlar", D: "Kimekler" }, dogruCevap: "A" },

// İlk Müslüman Türk Devletleri ve Selçuklular (21-40)
{ kategori: "Tarih", seviye: 5, soru: "Orta Asya'da kurulan ilk Müslüman Türk devleti hangisidir?", secenekler: { A: "Karahanlılar", B: "Gazneliler", C: "Samanoğulları", D: "Büyük Selçuklular" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Gazneli Mahmut'un 'Sarayımın en değerli hazinesi' dediği ünlü bilim insanı kimdir?", secenekler: { A: "Biruni", B: "İbn-i Sina", C: "Farabi", D: "Harezmi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Büyük Selçuklu Devleti'nin resmen kurulduğu kabul edilen 1040 tarihli savaş hangisidir?", secenekler: { A: "Dandanakan", B: "Pasinler", C: "Malazgirt", D: "Katvan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Sultan Alp Arslan döneminde Bizans'a karşı kazanılan 'Yurt Açan' savaş hangisidir?", secenekler: { A: "Malazgirt", B: "Miryokefalon", C: "Kösedağ", D: "Yassıçemen" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Selçukluların en parlak dönemini yaşatan ve 'Sultanü'l-Azam' lakabıyla bilinen hükümdar kimdir?", secenekler: { A: "Melikşah", B: "Tuğrul Bey", C: "Berkyaruk", D: "Sultan Sencer" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Anadolu Selçuklu Devleti'nin kurucusu kimdir?", secenekler: { A: "Süleyman Şah", B: "I. Mesut", C: "II. Kılıç Arslan", D: "Alaeddin Keykubad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Anadolu'nun kesin olarak Türk yurdu olduğunu kanıtlayan 1176 tarihli savaş hangisidir?", secenekler: { A: "Miryokefalon", B: "Malazgirt", C: "Pasinler", D: "Koyunhisar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Anadolu Selçuklu Devleti'nin en parlak dönemi hangi hükümdar zamanıdır?", secenekler: { A: "I. Alaeddin Keykubad", B: "I. Gıyaseddin Keyhüsrev", C: "II. Kılıç Arslan", D: "I. İzzettin Keykavus" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Anadolu Selçuklu Devleti'nin Moğollara yenilerek yıkılış sürecine girdiği savaş hangisidir?", secenekler: { A: "Kösedağ", B: "Ayn Calut", C: "Otlukbeli", D: "Yassıçemen" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk tarihinin ilk dini ve sosyal nitelikli isyanı hangisidir (Anadolu Selçuklu)?", secenekler: { A: "Babailer İsyanı", B: "Şahkulu İsyanı", C: "Şeyh Bedrettin", D: "Baba Zünnun" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Mısır'da kurulan ilk Türk-İslam devleti hangisidir?", secenekler: { A: "Tolunoğulları", B: "İhşidiler", C: "Eyyubiler", D: "Memlükler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Hangi devlet Moğolları tarihte ilk kez durdurmayı başarmıştır (Ayn Calut Savaşı)?", secenekler: { A: "Memlükler", B: "Eyyubiler", C: "Harzemşahlar", D: "Büyük Selçuklular" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Kudüz'u Haçlılardan geri alan (Hıttin Savaşı) ünlü Türk-İslam komutanı kimdir?", secenekler: { A: "Selahaddin Eyyubi", B: "Baybars", C: "Nureddin Zengi", D: "Kılıç Arslan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Büyük Selçuklularda vezirlik yapan ve 'Siyasetname' eserini yazan kişi kimdir?", secenekler: { A: "Nizamülmülk", B: "Hoca Dehhani", C: "İdris-i Bitlisi", D: "Gazali" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk-İslam devletlerinde çarşı ve pazar esnafını denetleyen görevliye ne denir?", secenekler: { A: "Muhtesip", B: "Müşrif", C: "Kadı", D: "Şıhne" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Anadolu'da Türkçe'yi resmi dil ilan eden ilk beylik hangisidir?", secenekler: { A: "Karamanoğulları", B: "Germiyanoğulları", C: "Karesioğulları", D: "Menteşeoğulları" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Karahanlılar döneminde yazılan, mutluluk veren bilgi anlamına gelen eser hangisidir?", secenekler: { A: "Kutadgu Bilig", B: "Atabetü'l Hakayık", C: "Divân-ı Hikmet", D: "Siyasetname" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Sultan Alparslan'ın mezarı hangi şehirdedir?", secenekler: { A: "Merv", B: "Nişabur", C: "Rey", D: "İsfahan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Selçuklularda 'Melik'lerin eğitiminden sorumlu kişiye ne ad verilir?", secenekler: { A: "Atabey", B: "Lala", C: "Naib", D: "Hacip" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Anadolu'da kurulan ilk Türk beyliği hangisidir?", secenekler: { A: "Saltuklular", B: "Danişmentliler", C: "Mengücekliler", D: "Artuklular" }, dogruCevap: "A" },

// Osmanlı Devleti - Kuruluş ve Yükselme (41-65)
{ kategori: "Tarih", seviye: 3, soru: "Osmanlı Devleti'nin kurucusu olan Osman Bey'in babası kimdir?", secenekler: { A: "Ertuğrul Gazi", B: "Gündüz Alp", C: "Hayme Ana", D: "Süleyman Şah" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nin Bizans ile yaptığı ilk savaş hangisidir?", secenekler: { A: "Koyunhisar (Bafeus)", B: "Maltepe (Palekanon)", C: "Sazlıdere", D: "Niğbolu" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "İlk Osmanlı parası ve ilk vergi uygulaması hangi padişah dönemindedir?", secenekler: { A: "Osman Bey", B: "Orhan Bey", C: "I. Murat", D: "Yıldırım Bayezid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Bursa'yı fethederek başkent yapan ve Yaya-Müsellem ordusunu kuran padişah kimdir?", secenekler: { A: "Orhan Bey", B: "Osman Bey", C: "Çelebi Mehmet", D: "II. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'nın Rumeli'deki ilk toprak parçası olan kale hangisidir?", secenekler: { A: "Çimpe Kalesi", B: "Gelibolu", C: "Edirne", D: "Belgrad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Savaş meydanında şehit edilen tek Osmanlı padişahı hangisidir?", secenekler: { A: "I. Murat", B: "II. Murat", C: "Genç Osman", D: "IV. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "1402 Ankara Savaşı'nda Timur'a esir düşen Osmanlı padişahı kimdir?", secenekler: { A: "Yıldırım Bayezid", B: "I. Mehmet", C: "II. Murat", D: "II. Bayezid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nin 'İkinci Kurucusu' sayılan padişah kimdir?", secenekler: { A: "Çelebi Mehmet", B: "II. Murat", C: "Fatih Sultan Mehmet", D: "Yavuz Sultan Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İstanbul kuşatması için Anadolu Hisarı'nı (Güzelcehisar) yaptıran padişah kimdir?", secenekler: { A: "Yıldırım Bayezid", B: "Fatih Sultan Mehmet", C: "II. Murat", D: "Orhan Bey" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "İstanbul fethedildikten sonra Fatih Sultan Mehmet'e verilen unvan hangisidir?", secenekler: { A: "Kayzer-i Rum", B: "Hadimü’l-Harameyn", C: "Halife", D: "Sultan-ı İklim-i Rum" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Fatih Sultan Mehmet'in kuşatıp da alamadığı, Kanuni'nin fethettiği yer neresidir?", secenekler: { A: "Belgrad", B: "Rodos", C: "Viyana", D: "Malta" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Sekiz yıla seksen yıllık iş sığdıran, halifeliği Osmanlı'ya getiren padişah kimdir?", secenekler: { A: "Yavuz Sultan Selim", B: "Kanuni Sultan Süleyman", C: "II. Selim", D: "III. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Dünya tarihinin en kısa süren (2 saat) meydan savaşı hangisidir?", secenekler: { A: "Mohaç Meydan Muharebesi", B: "Çaldıran Savaşı", C: "Ridaniye Savaşı", D: "Preveze" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "28 Eylül Türk Denizcilik Günü olarak kutlanan zafer hangisidir?", secenekler: { A: "Preveze Deniz Zaferi", B: "İnebahtı", C: "Cerbe Deniz Savaşı", D: "Navarin" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı Devleti'nde sadrazamlık makamı ilk kez hangi padişah döneminde kurulmuştur?", secenekler: { A: "I. Murat", B: "Orhan Bey", C: "Osman Bey", D: "II. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı'nın devlet işlerinin görüşüldüğü 'Divan-ı Hümayun'u kuran padişah kimdir?", secenekler: { A: "Orhan Bey", B: "Osman Bey", C: "I. Murat", D: "Fatih Sultan Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Yeniçeri Ocağı'nın temelini oluşturan sistem hangisidir?", secenekler: { A: "Pençik ve Devşirme", B: "Tımar Sistemi", C: "İltizam", D: "Malikane" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Padişahın çocuklarına (Şehzadelere) ders veren hocalara ne ad verilir?", secenekler: { A: "Lala", B: "Müderris", C: "Kadı", D: "Nişancı" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'da sınır boylarında yaşayan ve keşif yapan hafif süvari birliğine ne denir?", secenekler: { A: "Akıncılar", B: "Sipahiler", C: "Yeniçeriler", D: "Lağımcılar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı Devleti'nde dış yazışmalardan ve tapu kayıtlarından sorumlu görevli kimdir?", secenekler: { A: "Nişancı", B: "Reisü'l-Küttab", C: "Defterdar", D: "Kazasker" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Osmanlı'nın Avusturya üzerinde siyasi üstünlük kurduğu (Arşidükün sadrazama denk sayıldığı) antlaşma?", secenekler: { A: "İstanbul Antlaşması (1533)", B: "Zitvatorok", C: "Karlofça", D: "Pasarofça" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Fatih döneminde inşa edilen ve devletin yönetim merkezi olan saray hangisidir?", secenekler: { A: "Topkapı Sarayı", B: "Dolmabahçe Sarayı", C: "Çırağan", D: "Yıldız" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Hangi Osmanlı padişahı 'Avni' mahlasıyla şiirler yazmıştır?", secenekler: { A: "Fatih Sultan Mehmet", B: "Kanuni", C: "II. Mahmud", D: "Yavuz Sultan Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Preveze Deniz Zaferi'ni kazanan ünlü Osmanlı kaptan-ı deryası kimdir?", secenekler: { A: "Barbaros Hayrettin Paşa", B: "Piri Reis", C: "Turgut Reis", D: "Kılıç Ali Paşa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Dünya haritasını çizen ve Kitab-ı Bahriye eserini yazan ünlü denizci kimdir?", secenekler: { A: "Piri Reis", B: "Seydi Ali Reis", C: "Kemal Reis", D: "Murat Reis" }, dogruCevap: "A" },

// Osmanlı - Duraklama, Gerileme ve Dağılma (66-85)
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı Devleti'nin Batı'da en geniş sınırlara ulaştığı antlaşma hangisidir?", secenekler: { A: "Bucaş Antlaşması", B: "Ferhat Paşa", C: "Nasuh Paşa", D: "Serav" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı'nın Avusturya karşısındaki siyasi üstünlüğünü kaybettiği (Padişahın Arşidüke denk sayıldığı) antlaşma?", secenekler: { A: "Zitvatorok Antlaşması", B: "Karlofça", C: "Vasvar", D: "İstanbul (1700)" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı'da 'Vaka-i Vakvakiye' (Çınar Vakası) hangi padişah döneminde yaşanmıştır?", secenekler: { A: "IV. Mehmet", B: "II. Osman", C: "IV. Murad", D: "I. İbrahim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Osmanlı'da ilk kez bütçe planlaması yapan (modern bütçe) devlet adamı kimdir?", secenekler: { A: "Tarhuncu Ahmed Paşa", B: "Köprülü Mehmet Paşa", C: "Merzifonlu Kara Mustafa", D: "Baltacı Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı'nın büyük çapta toprak kaybettiği ilk antlaşma hangisidir?", secenekler: { A: "Karlofça Antlaşması", B: "Pasarofça", C: "Küçük Kaynarca", D: "Yaş" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nde Lale Devri'ni bitiren isyan hangisidir?", secenekler: { A: "Patrona Halil İsyanı", B: "Kabakçı Mustafa", C: "Celali İsyanları", D: "Canberdi Gazali" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Lale Devri'nin en ünlü minyatür sanatçısı kimdir?", secenekler: { A: "Levni", B: "Nigari", C: "Matrakçı Nasuh", D: "Şeker Ahmet Paşa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Osmanlı'nın Avrupa tarzında kurduğu ilk ordu hangisidir?", secenekler: { A: "Nizam-ı Cedid", B: "Sekban-ı Cedid", C: "Eşkinci Ocağı", D: "Asakir-i Mansure-i Muhammediye" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Yeniçeri Ocağı'nı kaldıran (Vaka-i Hayriye) padişah kimdir?", secenekler: { A: "II. Mahmud", B: "III. Selim", C: "Abdülmecid", D: "II. Abdülhamid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Osmanlı'da anayasal düzene geçişin ilk adımı sayılan 1839 tarihli belge hangisidir?", secenekler: { A: "Tanzimat Fermanı", B: "Islahat Fermanı", C: "Sened-i İttifak", D: "Kanun-i Esasi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı Devleti'nin ilk anayasası hangisidir?", secenekler: { A: "Kanun-i Esasi", B: "Teşkilat-ı Esasiye", C: "Gülhane Hatt-ı Hümayunu", D: "Bab-ı Ali Baskını" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı'nın 'Hasta Adam' olarak nitelendirildiği ilk yer neresidir?", secenekler: { A: "Rusya", B: "İngiltere", C: "Fransa", D: "Avusturya" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Kırım Savaşı sırasında 'Hemşireliğin Kurucusu' sayılan ve İstanbul'da çalışan kişi kimdir?", secenekler: { A: "Florence Nightingale", B: "Madame Curie", C: "Sabiha Gökçen", D: "Halide Edip" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı'da ilk kez telgraf hattı hangi savaş sırasında kurulmuştur?", secenekler: { A: "Kırım Savaşı", B: "93 Harbi", C: "Dömeke", D: "Trablusgarp" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı Devleti'nde ilk kağıt para (Kaime) hangi padişah döneminde basılmıştır?", secenekler: { A: "Sultan Abdülmecid", B: "II. Mahmud", C: "III. Selim", D: "Sultan Abdülaziz" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "31 Mart Vakası sonucunda tahttan indirilen padişah kimdir?", secenekler: { A: "II. Abdülhamid", B: "V. Mehmed Reşad", C: "Sultan Abdülaziz", D: "V. Murad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı'nın Kuzey Afrika'daki son toprak parçasını (Libya) kaybettiği antlaşma?", secenekler: { A: "Uşi Antlaşması", B: "Londra", C: "Bükreş", D: "Atina" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Çanakkale Savaşları'nda 215 kg'lık mermiyi sırtlayan kahraman kimdir?", secenekler: { A: "Seyit Onbaşı", B: "Yahya Çavuş", C: "Nene Hatun", D: "Sütçü İmam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "I. Dünya Savaşı'nda Osmanlı'nın kazandığı tek taarruz cephesi hangisidir?", secenekler: { A: "Kafkas Cephesi (Muş ve Bitlis geri alındı)", B: "Kanal Cephesi", C: "Irak", D: "Hicaz-Yemen" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Mondros Mütarekesi'ni Osmanlı adına imzalayan devlet adamı kimdir?", secenekler: { A: "Rauf Orbay", B: "Damat Ferit", C: "Ali Rıza Paşa", D: "Talat Paşa" }, dogruCevap: "A" },

// Milli Mücadele ve Cumhuriyet Tarihi (86-100)
{ kategori: "Tarih", seviye: 3, soru: "Atatürk'ün 'Geldikleri gibi giderler' sözünü söylediği yer neresidir?", secenekler: { A: "İstanbul", B: "Samsun", C: "Ankara", D: "İzmir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Kurtuluş Savaşı'nın gerekçesi, amacı ve yöntemi ilk kez nerede belirtilmiştir?", secenekler: { A: "Amasya Tamimi", B: "Havza Genelgesi", C: "Erzurum Kongresi", D: "Sivas Kongresi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Milli sınırların (Misak-ı Milli) ilk kez bahsedildiği kongre hangisidir?", secenekler: { A: "Erzurum Kongresi", B: "Sivas", C: "Amasya", D: "Balıkesir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Milli Mücadele'nin haklılığını kanıtlayan ilk uluslararası rapor hangisidir?", secenekler: { A: "Amiral Bristol Raporu", B: "General Harbourd", C: "Milne Hattı", D: "Sandler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "TBMM'nin imzaladığı ilk siyasi antlaşma (Ermenistan ile) hangisidir?", secenekler: { A: "Gümrü Antlaşması", B: "Kars", C: "Moskova", D: "Ankara" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "İstiklal Marşı hangi savaşın kazanılmasından sonra kabul edilmiştir?", secenekler: { A: "I. İnönü Savaşı", B: "II. İnönü", C: "Sakarya", D: "Büyük Taarruz" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Atatürk'e 'Gazi' unvanı ve 'Mareşal' rütbesi hangi savaştan sonra verilmiştir?", secenekler: { A: "Sakarya Meydan Muharebesi", B: "Büyük Taarruz", C: "Çanakkale", D: "Trablusgarp" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Saltanat hangi tarihte kaldırılmıştır?", secenekler: { A: "1 Kasım 1922", B: "29 Ekim 1923", C: "3 Mart 1924", D: "23 Nisan 1920" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Yeni Türk devletinin tapusu sayılan antlaşma hangisidir?", secenekler: { A: "Lozan Antlaşması", B: "Sevr", C: "Montrö", D: "Mudanya" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Cumhuriyetin ilanından sonra ilk Başbakan kimdir?", secenekler: { A: "İsmet İnönü", B: "Ali Fethi Okyar", C: "Celal Bayar", D: "Adnan Menderes" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk kadınına seçme ve seçilme hakkı tam olarak hangi yıl verilmiştir?", secenekler: { A: "1934", B: "1930", C: "1923", D: "1945" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Boğazlar üzerinde tam hakimiyet sağladığımız antlaşma hangisidir?", secenekler: { A: "Montrö Boğazlar Sözleşmesi", B: "Lozan", C: "Londra", D: "Paris" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Atatürk'ün naaşı Etnoğrafya Müzesi'nden Anıtkabir'e hangi yıl nakledilmiştir?", secenekler: { A: "1953", B: "1938", C: "1945", D: "1960" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Cumhuriyet döneminin ilk muhalefet partisi hangisidir?", secenekler: { A: "Terakkiperver Cumhuriyet Fırkası", B: "Serbest Cumhuriyet Fırkası", C: "Demokrat Parti", D: "Millet Partisi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Atatürk Dönemi'nde Türkiye'nin üye olduğu ilk uluslararası kuruluş hangisidir?", secenekler: { A: "Milletler Cemiyeti", B: "Birleşmiş Milletler", C: "Sadabat Paktı", D: "Balkan Antantı" }, dogruCevap: "A" },

// --- EKLEME: 101-300 ARASI YENİ SORULAR ---

// İslamiyet Öncesi Ek Sorular (101-140)
{ kategori: "Tarih", seviye: 4, soru: "İslamiyet öncesi Türklerde 'kurgan' adı verilen yapılar ne amaçla kullanılırdı?", secenekler: { A: "Mezar", B: "Tapınak", C: "Saray", D: "Kışla" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Uygurların başkenti olan şehir hangisidir?", secenekler: { A: "Ötüken", B: "Karabalgasun", C: "Balasagun", D: "Merv" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 8, soru: "Oğuz Kağan Destanı hangi Türk devletine aittir?", secenekler: { A: "Asya Hun", B: "Avrupa Hun", C: "Göktürk", D: "Uygur" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "İslamiyet öncesi Türklerde dokunan dünyaca ünlü halı hangi kurgan'dan çıkarılmıştır?", secenekler: { A: "Pazırık", B: "Esik", C: "Noin-Ula", D: "Kültepe" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Türklerin kullandığı ilk takvim hangisidir?", secenekler: { A: "12 Hayvanlı Türk Takvimi", B: "Hicri Takvim", C: "Celali Takvim", D: "Rumi Takvim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Altın Elbiseli Adam zırhı hangi Türk topluluğuna ait bir kurganda bulunmuştur?", secenekler: { A: "İskitler", B: "Hunlar", C: "Avarlar", D: "Hazarlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Eski Türklerde 'ayguci' ne demektir?", secenekler: { A: "Hükümdar", B: "Vezir/Başbakan", C: "Komutan", D: "Din adamı" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 4, soru: "Türklerin ilk ana yurdu neresidir?", secenekler: { A: "Orta Asya", B: "Mezopotamya", C: "Anadolu", D: "Kafkasya" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Yenisey Yazıtları hangi Türk topluluğuna aittir?", secenekler: { A: "Kırgızlar", B: "Uygurlar", C: "Karluklar", D: "Oğuzlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İslamiyeti kabul eden ilk Türk boyu hangisidir?", secenekler: { A: "Karluklar", B: "Kıpçaklar", C: "Oğuzlar", D: "Peçenekler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Rusların ünlü 'İgor Destanı'na konu olan Türk boyu hangisidir?", secenekler: { A: "Kıpçaklar (Kumanlar)", B: "Peçenekler", C: "Hazarlar", D: "Bulgarlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Eski Türklerde din adamlarına ne ad verilirdi?", secenekler: { A: "Şaman/Kam/Baksı", B: "Toygun", C: "Tigin", D: "Yabgu" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Tarihte ilk kez 'Türk' adını siyasi bir isim olarak kullanan devlet?", secenekler: { A: "I. Göktürk", B: "Asya Hun", C: "Karahanlı", D: "Uygur" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Hangi Türk topluluğu hem Asya'da hem Avrupa'da devlet kurmuştur?", secenekler: { A: "Hunlar ve Avarlar", B: "Uygurlar", C: "Karluklar", D: "Türgişler" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Uygurlarda kütüphanecilik ve matbaanın gelişmesi hangisinin sonucudur?", secenekler: { A: "Yerleşik yaşam", B: "Savaşlar", C: "Ticaret", D: "Hayvancılık" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Türklerin İslamiyetten önce inandıkları 'Gök Tanrı' inancına ne ad verilir?", secenekler: { A: "Tengrizm", B: "Maniheizm", C: "Budizm", D: "Şamanizm" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Eski Türklerde devletin iki kol halinde (Doğu-Batı) yönetilmesine ne denir?", secenekler: { A: "İkili Teşkilat", B: "Kurultay", C: "Kut", D: "Töre" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Kürşat İsyanı hangi devlete karşı yapılmıştır?", secenekler: { A: "Çin", B: "Bizans", C: "Sasani", D: "Moğol" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "İslamiyet öncesi Türklerde toplumsal hiyerarşinin en küçük birimi hangisidir?", secenekler: { A: "Oguş (Aile)", B: "Urug", C: "Boy", D: "Budun" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Codex Cumanicus adlı sözlük hangi Türk boyuna aittir?", secenekler: { A: "Kıpçaklar", B: "Peçenekler", C: "Hazarlar", D: "Bulgarlar" }, dogruCevap: "A" },

// Türk-İslam ve Selçuklu Devamı (141-180)
{ kategori: "Tarih", seviye: 6, soru: "Türklerin kitleler halinde İslamiyet'e geçmeye başladığı savaş hangisidir?", secenekler: { A: "Talas Savaşı", B: "Nihavend", C: "Kadisiye", D: "Yermük" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İlk Türk-İslam edebi eseri olan Kutadgu Bilig'in yazarı kimdir?", secenekler: { A: "Yusuf Has Hacib", B: "Kaşgarlı Mahmut", C: "Edip Ahmet Yükneki", D: "Ahmet Yesevi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Divan-ı Lügati't-Türk adlı eserin yazarı kimdir?", secenekler: { A: "Kaşgarlı Mahmut", B: "Yusuf Has Hacib", C: "Firdevsi", D: "Zemahşeri" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Büyük Selçuklu Devleti'nde resmi dil hangisidir?", secenekler: { A: "Farsça", B: "Türkçe", C: "Arapça", D: "Çince" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Anadolu'da kurulan ilk medrese hangisidir?", secenekler: { A: "Yağıbasan Medresesi", B: "Nizamiye", C: "Cacabey", D: "Gökmedrese" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Selçuklularda kervansaraylara verilen genel ad nedir?", secenekler: { A: "Ribat", B: "Külliye", C: "İmaret", D: "Bedesten" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Divan-ı Hikmet adlı eseriyle tasavvufun öncüsü olan isim?", secenekler: { A: "Ahmet Yesevi", B: "Hacı Bektaş Veli", C: "Mevlana", D: "Yunus Emre" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Büyük Selçuklu Devleti'ni en çok uğraştıran 'Batınilik' hareketinin lideri kimdir?", secenekler: { A: "Hasan Sabbah", B: "İbn-i Rüşd", C: "Baba İshak", D: "Nizami Gencevi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Anadolu Selçuklu Devleti'nin ilk başkenti neresidir?", secenekler: { A: "İznik", B: "Konya", C: "Kayseri", D: "Sivas" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Türk-İslam devletlerinde toprak yönetim sistemine ne denir?", secenekler: { A: "İkta Sistemi", B: "Miri Toprak", C: "İltizam", D: "Tımar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Gazneli Devleti nerede kurulmuştur?", secenekler: { A: "Afganistan", B: "İran", C: "Mısır", D: "Anadolu" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Bağdat'ı Şii Büveyhoğulları baskısından kurtaran ve 'Doğu'nun ve Batı'nın Sultanı' unvanını alan?", secenekler: { A: "Tuğrul Bey", B: "Alp Arslan", C: "Melikşah", D: "Gazneli Mahmut" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Anadolu Selçuklularında ticareti geliştirmek için yapılan sigorta sistemi ilk kez hangi devlette görülür?", secenekler: { A: "Anadolu Selçuklu", B: "Büyük Selçuklu", C: "Gazneli", D: "Karahanlı" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "İslam dünyasında 'Muallim-i Sani' (İkinci Öğretmen) olarak bilinen bilgin?", secenekler: { A: "Farabi", B: "İbn-i Sina", C: "Gazali", D: "Ömer Hayyam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Anadolu'da kurulan ilk denizci beylik hangisidir?", secenekler: { A: "Çaka Beyliği", B: "Karesioğulları", C: "Aydınoğulları", D: "Saruhanoğulları" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Selçuklu mimarisinde anıt mezarlara ne ad verilir?", secenekler: { A: "Kümbet", B: "Türbe", C: "Külliye", D: "Mescit" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Moğol İmparatorluğu'nun kurucusu Cengiz Han'ın asıl adı nedir?", secenekler: { A: "Temuçin", B: "Batu Han", C: "Hülagü", D: "Kubilay" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Selçuklularda 'Hacibü'l-Hüccab' ne iş yapar?", secenekler: { A: "Saray protokolü", B: "Ordu komutanı", C: "Hazine sorumlusu", D: "Dış işleri" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Anadolu'nun kapılarını Türklere açan Malazgirt Savaşı hangi yıl yapılmıştır?", secenekler: { A: "1071", B: "1040", C: "1048", D: "1176" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Anadolu Selçuklu Devleti'nde donanma komutanına ne ad verilir?", secenekler: { A: "Reisü'l Bahr/Melikü's Sevahil", B: "Kaptan-ı Derya", C: "Beylerbeyi", D: "Subaşı" }, dogruCevap: "A" },

// Osmanlı Kuruluş-Yükselme Detay (181-220)
{ kategori: "Tarih", seviye: 5, soru: "Osmanlı Devleti'nin Rumeli'ye geçişini sağlayan askeri üs hangisidir?", secenekler: { A: "Çimpe Kalesi", B: "Gelibolu", C: "Tekirdağ", D: "Edirne" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Sancak sistemini kaldıran (Sancaktan gelen son padişah) kimdir?", secenekler: { A: "III. Mehmet", B: "I. Ahmet", C: "III. Murat", D: "II. Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'da 'Kardeş Katli' yasasını yasallaştıran belge hangisidir?", secenekler: { A: "Kanunname-i Ali Osman", B: "Fatih Kanunnamesi", C: "Sened-i İttifak", D: "Islahat" }, dogruCevap: "B" },
{ kategori: "Tarih", seviye: 4, soru: "Osmanlı'nın Anadolu Türk siyasi birliğini büyük ölçüde sağlayan padişah?", secenekler: { A: "Yıldırım Bayezid", B: "Fatih", C: "Kanuni", D: "Yavuz" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Şah İsmail ile Yavuz Sultan Selim arasında yapılan savaş hangisidir?", secenekler: { A: "Çaldıran", B: "Turnadağ", C: "Mercidabık", D: "Ridaniye" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Cezayir hangi padişah döneminde Osmanlı topraklarına katılmıştır?", secenekler: { A: "Kanuni Sultan Süleyman", B: "Yavuz Sultan Selim", C: "Fatih", D: "II. Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı'da ilk şeyhülislam kimdir?", secenekler: { A: "Molla Fenari", B: "Ebusuud Efendi", C: "Akşemseddin", D: "Zenbilli Ali Efendi" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Kanuni Sultan Süleyman'ın son seferi hangisidir?", secenekler: { A: "Zigetvar Seferi", B: "Viyana Seferi", C: "Rodos", D: "Bağdat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Yeniçerilerin üç ayda bir aldığı maaşa ne denir?", secenekler: { A: "Ulufe", B: "Cülus", C: "İltizam", D: "Tımar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Osmanlı Devleti'nin haçlılarla yaptığı ilk büyük meydan savaşı?", secenekler: { A: "Sırpsındığı", B: "I. Kosova", C: "Niğbolu", D: "Varna" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Mimar Sinan'ın 'Çıraklık Eserim' dediği yapı hangisidir?", secenekler: { A: "Şehzade Camii", B: "Süleymaniye", C: "Selimiye", D: "Mihrimah Sultan" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'da devletin mali kayıtlarını tutan deftere ne denir?", secenekler: { A: "Tahrir Defteri", B: "Şer'iyye Sicili", C: "Mühimme", D: "Ruznamçe" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Kıbrıs'ın fethi (1571) hangi padişah döneminde gerçekleşmiştir?", secenekler: { A: "II. Selim", B: "Kanuni", C: "III. Murat", D: "Yavuz" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı Devleti'nde sadrazam öldüğünde veya savaşa gittiğinde yerine kim vekalet eder?", secenekler: { A: "Sadaret Kaymakamı", B: "Nişancı", C: "Kazasker", D: "Yeniçeri Ağası" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Padişahın tuğrasını çekmekle görevli divan üyesi kimdir?", secenekler: { A: "Nişancı", B: "Reisü'l-Küttab", C: "Defterdar", D: "Vezir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Safevi Devleti'ne son darbeyi vuran ve Tebriz'i alan padişah?", secenekler: { A: "Yavuz Sultan Selim", B: "Fatih", C: "IV. Murat", D: "I. Ahmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı'da 'Hükümdar ve oğullarının malıdır' anlayışını kim getirdi?", secenekler: { A: "I. Murat", B: "Osman Bey", C: "Orhan Bey", D: "II. Murat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Topkapı Sarayı'nda padişahın özel hayatının geçtiği bölüme ne denir?", secenekler: { A: "Harem", B: "Enderun", C: "Birun", D: "Arz Odası" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Hint Deniz Seferleri hangi padişah döneminde düzenlenmiştir?", secenekler: { A: "Kanuni Sultan Süleyman", B: "Yavuz", C: "II. Selim", D: "II. Bayezid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Fatih'in hocası ve mikroplardan bahseden ilk bilim insanı?", secenekler: { A: "Akşemseddin", B: "Ali Kuşçu", C: "Molla Gürani", D: "Kadızade-i Rumi" }, dogruCevap: "A" },

// Osmanlı Duraklama-Dağılma Devamı (221-260)
{ kategori: "Tarih", seviye: 7, soru: "Osmanlı Devleti'nde Ekber ve Erşed sistemini getiren padişah kimdir?", secenekler: { A: "I. Ahmet", B: "IV. Murat", C: "Genç Osman", D: "III. Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "II. Viyana Kuşatması'nı gerçekleştiren ancak başarısız olan sadrazam?", secenekler: { A: "Merzifonlu Kara Mustafa Paşa", B: "Köprülü Fazıl Ahmet", C: "Tarhuncu Ahmet", D: "Baltacı Mehmet" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Rusya'ya ilk kez kapitülasyonların verildiği antlaşma hangisidir?", secenekler: { A: "Küçük Kaynarca", B: "Yaş", C: "Prut", D: "Belgrad" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı'da 'Esvab-ı Hayriye' olarak bilinen padişah?", secenekler: { A: "II. Mahmud", B: "III. Selim", C: "Abdülaziz", D: "II. Abdülhamid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "İstibdat Dönemi hangi padişah zamanında yaşanmıştır?", secenekler: { A: "II. Abdülhamid", B: "Sultan Reşad", C: "Vahdettin", D: "Abdülmecid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Ermeni meselesinin uluslararası bir sorun haline geldiği antlaşma?", secenekler: { A: "Berlin Antlaşması", B: "Paris", C: "Londra", D: "Ayastefanos" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Bağdat Demiryolu projesini başlatan Osmanlı padişahı?", secenekler: { A: "II. Abdülhamid", B: "II. Mahmud", C: "Abdülaziz", D: "III. Selim" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Sultan Abdülaziz döneminde açılan, halkın eğitimine katkı sağlayan okul?", secenekler: { A: "Darüşşafaka", B: "Galatasaray Sultanisi", C: "Mülkiye", D: "Sanayi-i Nefise" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Dünya tarihinin ilk denizaltısı (Tahtülbahir) hangi Osmanlı padişahı dönemindedir?", secenekler: { A: "III. Ahmet", B: "I. Mahmud", C: "III. Selim", D: "II. Abdülhamid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Osmanlı'da matbaanın (İbrahim Müteferrika) kurulduğu dönem?", secenekler: { A: "Lale Devri", B: "Tanzimat", C: "Meşrutiyet", D: "Nizam-ı Cedid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Plevne Kahramanı olarak bilinen Osmanlı komutanı kimdir?", secenekler: { A: "Gazi Osman Paşa", B: "Gazi Ahmet Muhtar Paşa", C: "Enver Paşa", D: "Mustafa Kemal" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı'da 'Mecelle'yi (Medeni Kanun) hazırlayan komisyonun başkanı?", secenekler: { A: "Ahmet Cevdet Paşa", B: "Mithat Paşa", C: "Namık Kemal", D: "Ziya Paşa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Hamidiye Kahramanı olarak bilinen ve Mondros'u imzalayan devlet adamı?", secenekler: { A: "Rauf Orbay", B: "Kazım Karabekir", C: "Refet Bele", D: "Ali Fuat" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "II. Mahmud döneminde kurulan modern tıp okulunun adı?", secenekler: { A: "Mekteb-i Tıbbiye", B: "Darülfünun", C: "Hendesehane", D: "Mühendishane" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Osmanlı'da iflasın açıklandığı ve borçların ödeneceği 'Muharrem Kararnamesi' hangi dönem?", secenekler: { A: "II. Abdülhamid", B: "Abdülaziz", C: "V. Murad", D: "Abdülmecid" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Balkan Savaşları'nda kaybettiğimiz ancak II. Balkan'da geri aldığımız şehir?", secenekler: { A: "Edirne", B: "Selanik", C: "Yanya", D: "İşkodra" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Kutü'l Amare zaferi hangi cephede kazanılmıştır?", secenekler: { A: "Irak Cephesi", B: "Kafkas", C: "Kanal", D: "Suriye" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Medine Müdafii ve Çöl Kaplanı lakabıyla bilinen komutan?", secenekler: { A: "Fahreddin Paşa", B: "Nuri Paşa", C: "Halil Paşa", D: "Cemal Paşa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Trablusgarp Savaşı'nda Mustafa Kemal hangi takma adla savaşmıştır?", secenekler: { A: "Gazeteci Şerif Bey", B: "Tüccar Hamdi", C: "Şerif Ali", D: "Yüzbaşı Kemal" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Osmanlı'nın fiilen sona erdiği mütareke hangisidir?", secenekler: { A: "Mondros", B: "Mudanya", C: "Londra", D: "Lozan" }, dogruCevap: "A" },

// Milli Mücadele ve Cumhuriyet Ek Sorular (261-300)
{ kategori: "Tarih", seviye: 4, soru: "Atatürk'ün nüfusa kayıtlı olduğu şehir hangisidir?", secenekler: { A: "Gaziantep", B: "Selanik", C: "İstanbul", D: "Ankara" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Mustafa Kemal'in katıldığı ilk savaş hangisidir?", secenekler: { A: "Trablusgarp Savaşı", B: "Balkan Savaşları", C: "I. Dünya Savaşı", D: "31 Mart Vakası" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Atatürk'ün 'Ben size taarruzu değil, ölmeyi emrediyorum' dediği yer?", secenekler: { A: "Conkbayırı", B: "Arıburnu", C: "Anafartalar", D: "Kilitbahir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Doğu Cephesi komutanı kimdir?", secenekler: { A: "Kazım Karabekir", B: "İsmet İnönü", C: "Fevzi Çakmak", D: "Rauf Orbay" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Şark Fatihi olarak anılan Milli Mücadele kahramanı kimdir?", secenekler: { A: "Kazım Karabekir", B: "Ali Fuat Cebesoy", C: "Musa Kazım", D: "Refet Bele" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Sivas Kongresi'nde çıkarılan milli gazetenin adı nedir?", secenekler: { A: "İrade-i Milliye", B: "Hakimiyet-i Milliye", C: "Tercüman-ı Hakikat", D: "Peyam-ı Sabah" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Milli Mücadele'de Batı Cephesi'ni kuran kongre hangisidir?", secenekler: { A: "Balıkesir-Alaşehir Kongreleri", B: "Erzurum", C: "Sivas", D: "Nazilli" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Lozan'a giden Türk heyetinin başkanı kimdir?", secenekler: { A: "İsmet İnönü", B: "Rauf Orbay", C: "Bekir Sami Bey", D: "Yusuf Kemal Tengirşenk" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Milli Mücadele'nin son askeri safhası hangisidir?", secenekler: { A: "Büyük Taarruz", B: "Sakarya", C: "II. İnönü", D: "Kütahya-Eskişehir" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Cumhuriyet döneminde eğitim birliğini sağlayan kanun?", secenekler: { A: "Tevhid-i Tedrisat", B: "Maarif Teşkilatı", C: "Medeni Kanun", D: "Şapka Kanunu" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Atatürk'ün 'Şahsi Meselem' dediği şehir hangisidir?", secenekler: { A: "Hatay", B: "Musul", C: "Kerkük", D: "Boğazlar" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 4, soru: "Saltanatın kaldırılmasıyla hangi devlet sona ermiştir?", secenekler: { A: "Osmanlı Devleti", B: "Selçuklu", C: "Karahanlı", D: "Bizans" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Türkiye Cumhuriyeti'nin ilk Genelkurmay Başkanı kimdir?", secenekler: { A: "Fevzi Çakmak", B: "Kazım Karabekir", C: "İsmet İnönü", D: "Cevat Çobanlı" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Mustafa Kemal'e 'Atatürk' soyadı hangi yıl verilmiştir?", secenekler: { A: "1934", B: "1923", C: "1930", D: "1938" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Atatürk'ün vefatından hemen sonra TBMM tarafından seçilen ikinci Cumhurbaşkanı?", secenekler: { A: "İsmet İnönü", B: "Celal Bayar", C: "Fevzi Çakmak", D: "Refik Saydam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Kabotaj Kanunu neyi düzenlemiştir?", secenekler: { A: "Deniz ticareti ve hakları", B: "Eğitim", C: "Kıyafet", D: "Tarım" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Türk Tarih Kurumu ve Türk Dil Kurumu hangi ilke doğrultusunda kurulmuştur?", secenekler: { A: "Milliyetçilik", B: "Halkçılık", C: "Laiklik", D: "Cumhuriyetçilik" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Menemen Olayı'nda şehit edilen öğretmen subay kimdir?", secenekler: { A: "Mustafa Fehmi Kubilay", B: "Şahin Bey", C: "Yörük Ali", D: "Sütçü İmam" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 9, soru: "Millet Mektepleri ne amaçla açılmıştır?", secenekler: { A: "Yeni harfleri halka öğretmek", B: "Üniversite eğitimi", C: "Askeri eğitim", D: "Meslek edindirme" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 10, soru: "Atatürk'ün Nutuk adlı eseri hangi yılları kapsamaktadır?", secenekler: { A: "1919-1927", B: "1923-1938", C: "1914-1923", D: "1881-1938" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 7, soru: "Sümerbank ve Etibank hangi ilkenin sonucunda kurulmuştur?", secenekler: { A: "Devletçilik", B: "Laiklik", C: "Halkçılık", D: "Cumhuriyetçilik" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 6, soru: "Balkan Antantı'na hangi komşu devlet katılmamıştır?", secenekler: { A: "Bulgaristan", B: "Yunanistan", C: "Yugoslavya", D: "Romanya" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 8, soru: "Sadabat Paktı hangi tehlikeye karşı kurulmuştur?", secenekler: { A: "İtalya ve Almanya", B: "Rusya", C: "İngiltere", D: "Fransa" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 5, soru: "Atatürk'ün 'En büyük eserim' dediği şey nedir?", secenekler: { A: "Türkiye Cumhuriyeti", B: "Nutuk", C: "Harf İnkılabı", D: "Ordular" }, dogruCevap: "A" },
{ kategori: "Tarih", seviye: 11, soru: "Modern Türkiye'nin inşasında 'Köylü milletin efendisidir' diyerek önem verilen sektör?", secenekler: { A: "Tarım", B: "Sanayi", C: "Ticaret", D: "Turizm" }, dogruCevap: "A" }

);

 
